ALTER TABLE EZJOBS4O.EZ_HOST ADD CERTIFY_GUBUN VARCHAR2(1) DEFAULT 'P' NULL;


ALTER TABLE EZJOBS4O.EZ_SEND_LOG ADD RERUN_COUNTER NUMBER(38,0) NULL;
ALTER TABLE EZJOBS4O.EZ_SEND_LOG ADD ODATE VARCHAR2(8) NULL;
ALTER TABLE EZJOBS4O.EZ_SEND_LOG ADD SEND_DESCRIPTION VARCHAR2(100) NULL;
ALTER TABLE EZJOBS4O.EZ_DOC_03 ADD deleted_yn VARCHAR2(2) NULL;
ALTER TABLE EZJOBS4O.EZ_DOC_03 ADD del_sms_yn VARCHAR2(2) NULL;

ALTER TABLE EZJOBS4O.EZ_DOC_07 MODIFY BEFORE_STATUS VARCHAR2(40);


ALTER TABLE EZJOBS4O.EZ_DOC_01 MODIFY DESCRIPTION VARCHAR2(4000);
ALTER TABLE EZJOBS4O.EZ_DOC_02 MODIFY DESCRIPTION VARCHAR2(4000);
ALTER TABLE EZJOBS4O.EZ_DOC_03 MODIFY DESCRIPTION VARCHAR2(4000);
ALTER TABLE EZJOBS4O.EZ_DOC_04 MODIFY DESCRIPTION VARCHAR2(4000);
ALTER TABLE EZJOBS4O.EZ_DOC_04_ORIGINAL MODIFY DESCRIPTION VARCHAR2(4000);
ALTER TABLE EZJOBS4O.EZ_DOC_05 MODIFY DESCRIPTION VARCHAR2(4000);
ALTER TABLE EZJOBS4O.EZ_DOC_06_DETAIL MODIFY DESCRIPTION VARCHAR2(4000);

-- CTM 에서 만든 작업은 APPLICATION, GROUP_NAME 항목이 없을 수 있는데,
-- 상태 변경을 진행하면 EZ_DOC_07 테이블에 NOT NULL 컬럼이어서 필수라고 오류 발생하기 때문에 NULL 로 속성 변경. (2024.12.27 강명준)
ALTER TABLE EZJOBS4O.EZ_DOC_07 MODIFY APPLICATION VARCHAR2(50) NULL;
ALTER TABLE EZJOBS4O.EZ_DOC_07 MODIFY GROUP_NAME VARCHAR2(50) NULL;