-- EZJOBS.EZ_ADMIN_APPROVAL_GROUP definition

CREATE TABLE "EZJOBS"."EZ_ADMIN_APPROVAL_GROUP"
(	"ADMIN_LINE_GRP_CD" NUMBER NOT NULL ENABLE,
     "ADMIN_LINE_GRP_NM" VARCHAR2(100) NOT NULL ENABLE,
     "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
     "OWNER_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_DATE" DATE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "DOC_GUBUN" CHAR(2),
     "TOP_LEVEL_YN" CHAR(1),
     "SCHEDULE_YN" CHAR(1),
     "POST_APPROVAL_YN" CHAR(1)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ADMIN_APPROVAL_GROUP" ON "EZJOBS"."EZ_ADMIN_APPROVAL_GROUP" ("ADMIN_LINE_GRP_CD")
;
ALTER TABLE "EZJOBS"."EZ_ADMIN_APPROVAL_GROUP" ADD CONSTRAINT "PK_EZ_ADMIN_APPROVAL_GROUP" PRIMARY KEY ("ADMIN_LINE_GRP_CD")
    USING INDEX "EZJOBS"."PK_EZ_ADMIN_APPROVAL_GROUP"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ADMIN_APPROVAL_GROUP" ON "EZJOBS"."EZ_ADMIN_APPROVAL_GROUP" ("ADMIN_LINE_GRP_CD")
;


-- EZJOBS.EZ_ADMIN_APPROVAL_LINE definition

CREATE TABLE "EZJOBS"."EZ_ADMIN_APPROVAL_LINE"
(	"ADMIN_LINE_CD" NUMBER NOT NULL ENABLE,
     "ADMIN_LINE_GRP_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_CD" NUMBER,
     "APPROVAL_SEQ" NUMBER NOT NULL ENABLE,
     "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
     "INS_DATE" DATE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_GB" CHAR(2) NOT NULL ENABLE,
     "APPROVAL_TYPE" CHAR(2) NOT NULL ENABLE,
     "GROUP_LINE_GRP_CD" NUMBER
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ADMIN_APPROVAL_LINE" ON "EZJOBS"."EZ_ADMIN_APPROVAL_LINE" ("ADMIN_LINE_CD")
;
ALTER TABLE "EZJOBS"."EZ_ADMIN_APPROVAL_LINE" ADD CONSTRAINT "PK_EZ_ADMIN_APPROVAL_LINE" PRIMARY KEY ("ADMIN_LINE_CD")
    USING INDEX "EZJOBS"."PK_EZ_ADMIN_APPROVAL_LINE"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ADMIN_APPROVAL_LINE" ON "EZJOBS"."EZ_ADMIN_APPROVAL_LINE" ("ADMIN_LINE_CD")
;


-- EZJOBS.EZ_ALARM definition

CREATE TABLE "EZJOBS"."EZ_ALARM"
(	"ALARM_CD" NUMBER NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(20),
     "HOST_TIME" DATE NOT NULL ENABLE,
     "JOB_NAME" VARCHAR2(64),
     "APPLICATION" VARCHAR2(64),
     "GROUP_NAME" VARCHAR2(64),
     "MEMNAME" VARCHAR2(64),
     "ORDER_ID" VARCHAR2(5),
     "NODE_ID" VARCHAR2(50),
     "RUN_COUNTER" NUMBER,
     "MESSAGE" VARCHAR2(50),
     "ACTION_YN" VARCHAR2(1),
     "ACTION_DATE" DATE,
     "RECUR_YN" VARCHAR2(1),
     "ERROR_GUBUN" VARCHAR2(10),
     "ERROR_DESCRIPTION" VARCHAR2(4000),
     "SOLUTION_DESCRIPTION" VARCHAR2(4000),
     "USER_CD" NUMBER,
     "DEL_YN" VARCHAR2(1),
     "UPDATE_TIME" DATE,
     "UPDATE_USER_CD" NUMBER,
     "ACTION_GUBUN" VARCHAR2(20),
     "ORDER_TABLE" VARCHAR2(770),
     "CONFIRM_USER_CD" NUMBER,
     "CONFIRM_YN" VARCHAR2(40),
     "CONFIRM_TIME" DATE,
     "ODATE" VARCHAR2(6),
     "DESCRIPTION" VARCHAR2(4000),
     "CYCLIC" VARCHAR2(1)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ALARM" ON "EZJOBS"."EZ_ALARM" ("ALARM_CD")
;
ALTER TABLE "EZJOBS"."EZ_ALARM" ADD CONSTRAINT "PK_EZ_ALARM" PRIMARY KEY ("ALARM_CD")
    USING INDEX "EZJOBS"."PK_EZ_ALARM"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ALARM" ON "EZJOBS"."EZ_ALARM" ("ALARM_CD")
;


-- EZJOBS.EZ_ALARM_INFO definition

CREATE TABLE "EZJOBS"."EZ_ALARM_INFO"
(	"ALARM_SEQ" NUMBER NOT NULL ENABLE,
     "ALARM_STANDARD" VARCHAR2(64),
     "ALARM_MIN" VARCHAR2(10),
     "ALARM_MAX" VARCHAR2(10),
     "ALARM_UNIT" VARCHAR2(10),
     "ALARM_TIME" VARCHAR2(64),
     "ALARM_OVER" VARCHAR2(64),
     "ALARM_OVER_TIME" VARCHAR2(64)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ALARM_INFO" ON "EZJOBS"."EZ_ALARM_INFO" ("ALARM_SEQ")
;
ALTER TABLE "EZJOBS"."EZ_ALARM_INFO" ADD CONSTRAINT "PK_EZ_ALARM_INFO" PRIMARY KEY ("ALARM_SEQ")
    USING INDEX "EZJOBS"."PK_EZ_ALARM_INFO"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_ALARM_INFO" ON "EZJOBS"."EZ_ALARM_INFO" ("ALARM_SEQ")
;


-- EZJOBS.EZ_APPROVAL_DOC definition

CREATE TABLE "EZJOBS"."EZ_APPROVAL_DOC"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "SEQ" NUMBER NOT NULL ENABLE,
     "USER_CD" NUMBER,
     "DEPT_NM" VARCHAR2(200),
     "DUTY_NM" VARCHAR2(200),
     "APPROVAL_CD" VARCHAR2(2) NOT NULL ENABLE,
     "APPROVAL_DATE" DATE,
     "APPROVAL_COMMENT" VARCHAR2(4000),
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "LINE_GB" CHAR(1),
     "APPROVAL_GB" CHAR(2),
     "GROUP_LINE_GRP_CD" NUMBER,
     "APPROVAL_TYPE" CHAR(2),
     "GRP_APPROVAL_USERLIST" VARCHAR2(200),
     "GRP_ALARM_USERLIST" VARCHAR2(200)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_APPROVAL_DOC" ON "EZJOBS"."EZ_APPROVAL_DOC" ("DOC_CD", "SEQ")
;
ALTER TABLE "EZJOBS"."EZ_APPROVAL_DOC" ADD CONSTRAINT "PK_EZ_APPROVAL_DOC" PRIMARY KEY ("DOC_CD", "SEQ")
    USING INDEX "EZJOBS"."PK_EZ_APPROVAL_DOC"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_APPROVAL_DOC" ON "EZJOBS"."EZ_APPROVAL_DOC" ("DOC_CD", "SEQ")
;


-- EZJOBS.EZ_APP_GRP_CODE definition

CREATE TABLE "EZJOBS"."EZ_APP_GRP_CODE"
(	"GRP_CD" NUMBER NOT NULL ENABLE,
     "GRP_NM" VARCHAR2(100),
     "GRP_ENG_NM" VARCHAR2(100) NOT NULL ENABLE,
     "GRP_DEPTH" NUMBER NOT NULL ENABLE,
     "GRP_PARENT_CD" VARCHAR2(100) NOT NULL ENABLE,
     "GRP_USE_YN" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
     "GRP_DESC" VARCHAR2(4000),
     "GRP_INS_DATE" CHAR(14) NOT NULL ENABLE,
     "GRP_INS_USER_CD" NUMBER NOT NULL ENABLE,
     "GRP_UDT_DATE" VARCHAR2(14),
     "GRP_UDT_USER_CD" NUMBER,
     "SCODE_CD" VARCHAR2(10),
     "HOST_CD" NUMBER,
     "USER_DAILY" VARCHAR2(100)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_APP_GRP_CODE" ON "EZJOBS"."EZ_APP_GRP_CODE" ("GRP_CD")
;
ALTER TABLE "EZJOBS"."EZ_APP_GRP_CODE" ADD CONSTRAINT "PK_EZ_APP_GRP_CODE" PRIMARY KEY ("GRP_CD")
    USING INDEX "EZJOBS"."PK_EZ_APP_GRP_CODE"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_APP_GRP_CODE" ON "EZJOBS"."EZ_APP_GRP_CODE" ("GRP_CD")
;


-- EZJOBS.EZ_AVG_INFO definition

CREATE TABLE "EZJOBS"."EZ_AVG_INFO"
(	"DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE,
     "ORDER_ID" VARCHAR2(5) NOT NULL ENABLE,
     "JOB_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "ORDER_TABLE" VARCHAR2(770),
     "APPLICATION" VARCHAR2(64) NOT NULL ENABLE,
     "GROUP_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "ODATE" VARCHAR2(6) NOT NULL ENABLE,
     "AVG_RUNTIME" VARCHAR2(6),
     "START_TIME" VARCHAR2(14),
     "END_TIME" VARCHAR2(14)
) ;


-- EZJOBS.EZ_AVG_TIME definition

CREATE TABLE "EZJOBS"."EZ_AVG_TIME"
(	"JOB_NAME" VARCHAR2(64),
     "AVG_RUN_TIME" NUMBER,
     "AVG_START_TIME" NUMBER,
     "AVG_END_TIME" NUMBER,
     "INS_DATE" DATE,
     "UDT_DATE" DATE,
     "DATA_CENTER" VARCHAR2(20),
     CONSTRAINT "SYS_C00302675" CHECK ("DATA_CENTER" IS NOT NULL) ENABLE NOVALIDATE,
     CONSTRAINT "SYS_C00302676" CHECK ("JOB_NAME" IS NOT NULL) ENABLE NOVALIDATE,
     CONSTRAINT "EZ_AVG_TIME_PK" PRIMARY KEY ("JOB_NAME", "DATA_CENTER")
         USING INDEX  ENABLE
) ;

CREATE UNIQUE INDEX "EZJOBS"."EZ_AVG_TIME_PK" ON "EZJOBS"."EZ_AVG_TIME" ("JOB_NAME", "DATA_CENTER")
;


-- EZJOBS.EZ_AVG_TIME_ALL definition

CREATE TABLE "EZJOBS"."EZ_AVG_TIME_ALL"
(	"JOB_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "START_TIME" DATE,
     "END_TIME" DATE,
     "INS_DATE" DATE,
     "DATA_CENTER" VARCHAR2(20) NOT NULL ENABLE,
     "ORDER_ID" VARCHAR2(5) NOT NULL ENABLE,
     "ORDER_DATE" VARCHAR2(8) NOT NULL ENABLE,
     "RERUN_COUNTER" NUMBER(38,0) NOT NULL ENABLE
) ;

CREATE INDEX "EZJOBS"."EZ_AVG_TIME_ALL_START_TIME_IDX" ON "EZJOBS"."EZ_AVG_TIME_ALL" ("START_TIME")
;
CREATE INDEX "EZJOBS"."EZ_AVG_TIME_ALL_END_TIME_IDX" ON "EZJOBS"."EZ_AVG_TIME_ALL" ("END_TIME")
;
CREATE INDEX "EZJOBS"."EZ_AVG_TIME_ALL_JOB_NAME_IDX" ON "EZJOBS"."EZ_AVG_TIME_ALL" ("JOB_NAME")
;


-- EZJOBS.EZ_BOARD definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE EZJOBS.EZ_BOARD;

CREATE TABLE EZJOBS.EZ_BOARD (
                                   BOARD_CD NUMBER,
                                   TITLE VARCHAR2(200),
                                   CONTENT CLOB,
                                   STATUS CHAR(2) DEFAULT '01' ,
                                   DEL_YN CHAR(1) DEFAULT 'N' ,
                                   FILE_NM VARCHAR2(200),
                                   FILE_PATH VARCHAR2(500),
                                   NOTI_YN CHAR(1) DEFAULT 'N' ,
                                   APP_USER_CD NUMBER,
                                   INS_USER_CD NUMBER,
                                   INS_DATE DATE,
                                   BOARD_GB CHAR(2),
                                   SEQ NUMBER,
                                   POPUP_YN CHAR(1),
                                   POPUP_S_DATE CHAR(8),
                                   POPUP_E_DATE CHAR(8),
                                   CONSTRAINT PK_EZ_BOARD PRIMARY KEY (BOARD_CD),
                                   CONSTRAINT SYS_C008373 CHECK ("BOARD_CD" IS NOT NULL),
                                   CONSTRAINT SYS_C008374 CHECK ("TITLE" IS NOT NULL),
                                   CONSTRAINT SYS_C008375 CHECK ("STATUS" IS NOT NULL),
                                   CONSTRAINT SYS_C008376 CHECK ("DEL_YN" IS NOT NULL),
                                   CONSTRAINT SYS_C008377 CHECK ("NOTI_YN" IS NOT NULL),
                                   CONSTRAINT SYS_C008378 CHECK ("INS_USER_CD" IS NOT NULL),
                                   CONSTRAINT SYS_C008379 CHECK ("INS_DATE" IS NOT NULL),
                                   CONSTRAINT SYS_C008380 CHECK ("BOARD_GB" IS NOT NULL)
);
CREATE UNIQUE INDEX PK_EZ_BOARD ON EZJOBS.EZ_BOARD (BOARD_CD);


-- EZJOBS.EZ_CMR_RPLN definition

CREATE TABLE "EZJOBS"."EZ_CMR_RPLN"
(	"DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE,
     "JOB_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "ODATE" VARCHAR2(8) NOT NULL ENABLE
) ;


-- EZJOBS.EZ_COND_HISTORY definition

CREATE TABLE "EZJOBS"."EZ_COND_HISTORY"
(	"GUBUN" VARCHAR2(20) NOT NULL ENABLE,
     "CONDITION_NAME" VARCHAR2(4000),
     "ODATE" VARCHAR2(6) NOT NULL ENABLE,
     "INS_USER_CD" NUMBER,
     "INS_DATE" DATE NOT NULL ENABLE
) ;


-- EZJOBS.EZ_DEPT definition

CREATE TABLE "EZJOBS"."EZ_DEPT"
(	"DEPT_CD" NUMBER NOT NULL ENABLE,
     "DEPT_NM" VARCHAR2(200) NOT NULL ENABLE,
     "DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "DEPT_ID" VARCHAR2(200)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DEPT" ON "EZJOBS"."EZ_DEPT" ("DEPT_CD")
;
ALTER TABLE "EZJOBS"."EZ_DEPT" ADD CONSTRAINT "PK_EZ_DEPT" PRIMARY KEY ("DEPT_CD")
    USING INDEX "EZJOBS"."PK_EZ_DEPT"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DEPT" ON "EZJOBS"."EZ_DEPT" ("DEPT_CD")
;


-- EZJOBS.EZ_DEPT_RELAY definition

CREATE TABLE "EZJOBS"."EZ_DEPT_RELAY"
(	"DEPT_CD" VARCHAR2(100),
     "DEPT_NM" VARCHAR2(100),
     "INS_DATE" DATE NOT NULL ENABLE
) ;


-- EZJOBS.EZ_DOC_01 definition

CREATE TABLE "EZJOBS"."EZ_DOC_01"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(2000),
     "CONTENT" VARCHAR2(4000),
     "TABLE_ID" NUMBER,
     "JOB_ID" NUMBER,
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "MEM_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "DESCRIPTION" VARCHAR2(4000),
     "AUTHOR" VARCHAR2(50),
     "OWNER" VARCHAR2(50),
     "PRIORITY" VARCHAR2(2),
     "CRITICAL" VARCHAR2(1),
     "TASK_TYPE" VARCHAR2(21),
     "CYCLIC" VARCHAR2(1),
     "NODE_ID" VARCHAR2(50),
     "RERUN_INTERVAL" VARCHAR2(6),
     "RERUN_INTERVAL_TIME" VARCHAR2(1),
     "MEM_LIB" VARCHAR2(255),
     "COMMAND" VARCHAR2(512),
     "CONFIRM_FLAG" VARCHAR2(1),
     "DAYS_CAL" VARCHAR2(50),
     "WEEKS_CAL" VARCHAR2(50),
     "RETRO" VARCHAR2(1),
     "MAX_WAIT" NUMBER,
     "RERUN_MAX" NUMBER,
     "TIME_FROM" VARCHAR2(4),
     "TIME_UNTIL" VARCHAR2(4),
     "MONTH_DAYS" VARCHAR2(160),
     "WEEK_DAYS" VARCHAR2(50),
     "MONTH_1" VARCHAR2(1),
     "MONTH_2" VARCHAR2(1),
     "MONTH_3" VARCHAR2(1),
     "MONTH_4" VARCHAR2(1),
     "MONTH_5" VARCHAR2(1),
     "MONTH_6" VARCHAR2(1),
     "MONTH_7" VARCHAR2(1),
     "MONTH_8" VARCHAR2(1),
     "MONTH_9" VARCHAR2(1),
     "MONTH_10" VARCHAR2(1),
     "MONTH_11" VARCHAR2(1),
     "MONTH_12" VARCHAR2(1),
     "COUNT_CYCLIC_FROM" VARCHAR2(10),
     "TIME_ZONE" VARCHAR2(9),
     "MULTIAGENT" VARCHAR2(1),
     "USER_DAILY" VARCHAR2(20),
     "SCHEDULE_AND_OR" VARCHAR2(1),
     "IN_CONDITIONS_OPT" VARCHAR2(10),
     "T_GENERAL_DATE" VARCHAR2(4000),
     "T_CONDITIONS_IN" VARCHAR2(4000),
     "T_CONDITIONS_OUT" VARCHAR2(4000),
     "T_RESOURCES_Q" VARCHAR2(4000),
     "T_RESOURCES_C" VARCHAR2(4000),
     "T_SET" VARCHAR2(4000),
     "T_STEPS" VARCHAR2(4000),
     "T_POSTPROC" VARCHAR2(4000),
     "T_SFILE" VARCHAR2(4000),
     "CONF_CAL" VARCHAR2(30),
     "SHIFT" VARCHAR2(10),
     "SHIFT_NUM" VARCHAR2(3),
     "T_TAG_NAME" VARCHAR2(4000),
     "INTERVAL_SEQUENCE" VARCHAR2(4000),
     "SPECIFIC_TIMES" VARCHAR2(4000),
     "TOLERANCE" NUMBER,
     "CYCLIC_TYPE" VARCHAR2(1),
     "ACTIVE_FROM" VARCHAR2(8),
     "ACTIVE_TILL" VARCHAR2(8),
     "APPLY_DATE" VARCHAR2(8),
     "APPLY_CHECK" VARCHAR2(1),
     "SR_CODE" CHAR(1),
     "DATES_STR" VARCHAR2(255),
     "MONITOR_TIME" VARCHAR2(10),
     "MONITOR_INTERVAL" VARCHAR2(10),
     "FILESIZE_COMPARISON" VARCHAR2(10),
     "NUM_OF_ITERATIONS" VARCHAR2(10),
     "STOP_TIME" VARCHAR2(10)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_01" ON "EZJOBS"."EZ_DOC_01" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_01" ADD CONSTRAINT "PK_EZ_DOC_01" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_01"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_01" ON "EZJOBS"."EZ_DOC_01" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_02 definition

CREATE TABLE "EZJOBS"."EZ_DOC_02"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(2000),
     "CONTENT" VARCHAR2(4000),
     "TABLE_ID" NUMBER,
     "JOB_ID" NUMBER,
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "MEM_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "DESCRIPTION" VARCHAR2(4000),
     "AUTHOR" VARCHAR2(50),
     "OWNER" VARCHAR2(50),
     "PRIORITY" VARCHAR2(2),
     "CRITICAL" VARCHAR2(1),
     "TASK_TYPE" VARCHAR2(21),
     "CYCLIC" VARCHAR2(1),
     "NODE_ID" VARCHAR2(50),
     "RERUN_INTERVAL" VARCHAR2(6),
     "RERUN_INTERVAL_TIME" VARCHAR2(1),
     "MEM_LIB" VARCHAR2(255),
     "COMMAND" VARCHAR2(512),
     "CONFIRM_FLAG" VARCHAR2(1),
     "DAYS_CAL" VARCHAR2(50),
     "WEEKS_CAL" VARCHAR2(50),
     "RETRO" VARCHAR2(1),
     "MAX_WAIT" NUMBER,
     "RERUN_MAX" NUMBER,
     "TIME_FROM" VARCHAR2(4),
     "TIME_UNTIL" VARCHAR2(4),
     "MONTH_DAYS" VARCHAR2(160),
     "WEEK_DAYS" VARCHAR2(50),
     "MONTH_1" VARCHAR2(1),
     "MONTH_2" VARCHAR2(1),
     "MONTH_3" VARCHAR2(1),
     "MONTH_4" VARCHAR2(1),
     "MONTH_5" VARCHAR2(1),
     "MONTH_6" VARCHAR2(1),
     "MONTH_7" VARCHAR2(1),
     "MONTH_8" VARCHAR2(1),
     "MONTH_9" VARCHAR2(1),
     "MONTH_10" VARCHAR2(1),
     "MONTH_11" VARCHAR2(1),
     "MONTH_12" VARCHAR2(1),
     "COUNT_CYCLIC_FROM" VARCHAR2(10),
     "TIME_ZONE" VARCHAR2(9),
     "MULTIAGENT" VARCHAR2(1),
     "USER_DAILY" VARCHAR2(20),
     "SCHEDULE_AND_OR" VARCHAR2(1),
     "IN_CONDITIONS_OPT" VARCHAR2(10),
     "T_GENERAL_DATE" VARCHAR2(4000),
     "T_CONDITIONS_IN" VARCHAR2(4000),
     "T_CONDITIONS_OUT" VARCHAR2(4000),
     "T_RESOURCES_Q" VARCHAR2(4000),
     "T_RESOURCES_C" VARCHAR2(4000),
     "T_SET" VARCHAR2(4000),
     "T_STEPS" VARCHAR2(4000),
     "T_POSTPROC" VARCHAR2(4000),
     "T_SFILE" VARCHAR2(4000),
     "CONF_CAL" VARCHAR2(30),
     "SHIFT" VARCHAR2(10),
     "SHIFT_NUM" VARCHAR2(3),
     "T_TAG_NAME" VARCHAR2(4000),
     "INTERVAL_SEQUENCE" VARCHAR2(4000),
     "SPECIFIC_TIMES" VARCHAR2(4000),
     "TOLERANCE" NUMBER,
     "CYCLIC_TYPE" VARCHAR2(1),
     "ACTIVE_FROM" VARCHAR2(8),
     "ACTIVE_TILL" VARCHAR2(8),
     "APPLY_DATE" VARCHAR2(8),
     "APPLY_CHECK" VARCHAR2(1),
     "SR_CODE" CHAR(1),
     "DATES_STR" VARCHAR2(255),
     "MONITOR_TIME" VARCHAR2(10),
     "MONITOR_INTERVAL" VARCHAR2(10),
     "FILESIZE_COMPARISON" VARCHAR2(10),
     "NUM_OF_ITERATIONS" VARCHAR2(10),
     "STOP_TIME" VARCHAR2(10),
     "ORDER_ID" VARCHAR2(5)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_02" ON "EZJOBS"."EZ_DOC_02" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_02" ADD CONSTRAINT "PK_EZ_DOC_02" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_02"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_02" ON "EZJOBS"."EZ_DOC_02" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_03 definition

CREATE TABLE "EZJOBS"."EZ_DOC_03"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(2000),
     "CONTENT" VARCHAR2(4000),
     "TABLE_ID" NUMBER,
     "JOB_ID" NUMBER,
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "MEM_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "TASK_TYPE" VARCHAR2(21),
     "USER_DAILY" VARCHAR2(20),
     "DESCRIPTION" VARCHAR2(4000),
     "OWNER" VARCHAR2(50),
     "AUTHOR" VARCHAR2(50),
     "MEM_LIB" VARCHAR2(255),
     "COMMAND" VARCHAR2(512),
     "IN_CONDITION" VARCHAR2(4000),
     "OUT_CONDITION" VARCHAR2(4000),
     "APPLY_DATE" VARCHAR2(8),
     "APPLY_CHECK" VARCHAR2(1),
     "NODE_ID" VARCHAR2(50),
     "DELETED_YN" VARCHAR2(2),
     "DEL_SMS_YN" VARCHAR2(2)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_03" ON "EZJOBS"."EZ_DOC_03" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_03" ADD CONSTRAINT "PK_EZ_DOC_03" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_03"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_03" ON "EZJOBS"."EZ_DOC_03" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_04 definition

CREATE TABLE "EZJOBS"."EZ_DOC_04"
(	"DOC_CD" VARCHAR2(16),
     "TITLE" VARCHAR2(2000),
     "CONTENT" VARCHAR2(4000),
     "TABLE_ID" NUMBER,
     "JOB_ID" NUMBER,
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "MEM_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "DESCRIPTION" VARCHAR2(4000),
     "AUTHOR" VARCHAR2(50),
     "OWNER" VARCHAR2(50),
     "PRIORITY" VARCHAR2(2),
     "CRITICAL" VARCHAR2(1),
     "TASK_TYPE" VARCHAR2(21),
     "CYCLIC" VARCHAR2(1),
     "NODE_ID" VARCHAR2(50),
     "RERUN_INTERVAL" VARCHAR2(6),
     "RERUN_INTERVAL_TIME" VARCHAR2(1),
     "MEM_LIB" VARCHAR2(255),
     "COMMAND" VARCHAR2(512),
     "CONFIRM_FLAG" VARCHAR2(1),
     "DAYS_CAL" VARCHAR2(50),
     "WEEKS_CAL" VARCHAR2(50),
     "RETRO" VARCHAR2(1),
     "MAX_WAIT" NUMBER,
     "RERUN_MAX" NUMBER,
     "TIME_FROM" VARCHAR2(4),
     "TIME_UNTIL" VARCHAR2(4),
     "MONTH_DAYS" VARCHAR2(160),
     "WEEK_DAYS" VARCHAR2(50),
     "MONTH_1" VARCHAR2(1),
     "MONTH_2" VARCHAR2(1),
     "MONTH_3" VARCHAR2(1),
     "MONTH_4" VARCHAR2(1),
     "MONTH_5" VARCHAR2(1),
     "MONTH_6" VARCHAR2(1),
     "MONTH_7" VARCHAR2(1),
     "MONTH_8" VARCHAR2(1),
     "MONTH_9" VARCHAR2(1),
     "MONTH_10" VARCHAR2(1),
     "MONTH_11" VARCHAR2(1),
     "MONTH_12" VARCHAR2(1),
     "COUNT_CYCLIC_FROM" VARCHAR2(10),
     "TIME_ZONE" VARCHAR2(9),
     "MULTIAGENT" VARCHAR2(1),
     "USER_DAILY" VARCHAR2(20),
     "SCHEDULE_AND_OR" VARCHAR2(1),
     "IN_CONDITIONS_OPT" VARCHAR2(10),
     "T_GENERAL_DATE" VARCHAR2(4000),
     "T_CONDITIONS_IN" VARCHAR2(4000),
     "T_CONDITIONS_OUT" VARCHAR2(4000),
     "T_RESOURCES_Q" VARCHAR2(4000),
     "T_RESOURCES_C" VARCHAR2(4000),
     "T_SET" VARCHAR2(4000),
     "T_STEPS" VARCHAR2(4000),
     "T_POSTPROC" VARCHAR2(4000),
     "BEFORE_TABLE_NAME" VARCHAR2(770),
     "BEFORE_APPLICATION" VARCHAR2(50),
     "BEFORE_GROUP_NAME" VARCHAR2(50),
     "T_TAG_NAME" VARCHAR2(4000),
     "INTERVAL_SEQUENCE" VARCHAR2(4000),
     "SPECIFIC_TIMES" VARCHAR2(4000),
     "TOLERANCE" NUMBER,
     "CYCLIC_TYPE" VARCHAR2(1),
     "ACTIVE_FROM" VARCHAR2(8),
     "ACTIVE_TILL" VARCHAR2(8),
     "APPLY_DATE" VARCHAR2(8),
     "APPLY_CHECK" VARCHAR2(1),
     "SR_CODE" CHAR(1),
     "DATES_STR" VARCHAR2(255),
     "MONITOR_TIME" VARCHAR2(10),
     "MONITOR_INTERVAL" VARCHAR2(10),
     "CONF_CAL" VARCHAR2(30),
     "SHIFT" VARCHAR2(10),
     "SHIFT_NUM" VARCHAR2(3),
     "FILESIZE_COMPARISON" VARCHAR2(10),
     "NUM_OF_ITERATIONS" VARCHAR2(10),
     "STOP_TIME" VARCHAR2(10)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_04" ON "EZJOBS"."EZ_DOC_04" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_04" ADD CONSTRAINT "PK_EZ_DOC_04" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_04"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_04" ON "EZJOBS"."EZ_DOC_04" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_04_ORIGINAL definition

CREATE TABLE "EZJOBS"."EZ_DOC_04_ORIGINAL"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(2000),
     "CONTENT" VARCHAR2(4000),
     "TABLE_ID" NUMBER,
     "JOB_ID" NUMBER,
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "MEM_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "DESCRIPTION" VARCHAR2(4000),
     "AUTHOR" VARCHAR2(50),
     "OWNER" VARCHAR2(50),
     "PRIORITY" VARCHAR2(2),
     "CRITICAL" VARCHAR2(1),
     "TASK_TYPE" VARCHAR2(21),
     "CYCLIC" VARCHAR2(1),
     "NODE_ID" VARCHAR2(50),
     "RERUN_INTERVAL" VARCHAR2(6),
     "RERUN_INTERVAL_TIME" VARCHAR2(1),
     "MEM_LIB" VARCHAR2(255),
     "COMMAND" VARCHAR2(512),
     "CONFIRM_FLAG" VARCHAR2(1),
     "DAYS_CAL" VARCHAR2(50),
     "WEEKS_CAL" VARCHAR2(50),
     "RETRO" VARCHAR2(1),
     "MAX_WAIT" NUMBER,
     "RERUN_MAX" NUMBER,
     "TIME_FROM" VARCHAR2(4),
     "TIME_UNTIL" VARCHAR2(4),
     "MONTH_DAYS" VARCHAR2(160),
     "WEEK_DAYS" VARCHAR2(50),
     "MONTH_1" VARCHAR2(1),
     "MONTH_2" VARCHAR2(1),
     "MONTH_3" VARCHAR2(1),
     "MONTH_4" VARCHAR2(1),
     "MONTH_5" VARCHAR2(1),
     "MONTH_6" VARCHAR2(1),
     "MONTH_7" VARCHAR2(1),
     "MONTH_8" VARCHAR2(1),
     "MONTH_9" VARCHAR2(1),
     "MONTH_10" VARCHAR2(1),
     "MONTH_11" VARCHAR2(1),
     "MONTH_12" VARCHAR2(1),
     "COUNT_CYCLIC_FROM" VARCHAR2(10),
     "TIME_ZONE" VARCHAR2(9),
     "MULTIAGENT" VARCHAR2(1),
     "USER_DAILY" VARCHAR2(20),
     "SCHEDULE_AND_OR" VARCHAR2(1),
     "IN_CONDITIONS_OPT" VARCHAR2(10),
     "T_GENERAL_DATE" VARCHAR2(4000),
     "T_CONDITIONS_IN" VARCHAR2(4000),
     "T_CONDITIONS_OUT" VARCHAR2(4000),
     "T_RESOURCES_Q" VARCHAR2(4000),
     "T_RESOURCES_C" VARCHAR2(4000),
     "T_SET" VARCHAR2(4000),
     "T_STEPS" VARCHAR2(4000),
     "T_POSTPROC" VARCHAR2(4000),
     "BEFORE_TABLE_NAME" VARCHAR2(770),
     "BEFORE_APPLICATION" VARCHAR2(50),
     "BEFORE_GROUP_NAME" VARCHAR2(50),
     "T_TAG_NAME" VARCHAR2(4000),
     "INTERVAL_SEQUENCE" VARCHAR2(4000),
     "SPECIFIC_TIMES" VARCHAR2(4000),
     "TOLERANCE" NUMBER,
     "CYCLIC_TYPE" VARCHAR2(1),
     "ACTIVE_FROM" VARCHAR2(8),
     "ACTIVE_TILL" VARCHAR2(8),
     "APPLY_DATE" VARCHAR2(8),
     "APPLY_CHECK" VARCHAR2(1),
     "SR_CODE" CHAR(1),
     "DATES_STR" VARCHAR2(255),
     "MONITOR_TIME" VARCHAR2(10),
     "MONITOR_INTERVAL" VARCHAR2(10),
     "CONF_CAL" VARCHAR2(30),
     "SHIFT" VARCHAR2(10),
     "SHIFT_NUM" VARCHAR2(3),
     "FILESIZE_COMPARISON" VARCHAR2(10),
     "NUM_OF_ITERATIONS" VARCHAR2(10),
     "STOP_TIME" VARCHAR2(10)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_04_ORIGINAL" ON "EZJOBS"."EZ_DOC_04_ORIGINAL" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_04_ORIGINAL" ADD CONSTRAINT "PK_EZ_DOC_04_ORIGINAL" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_04_ORIGINAL"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_04_ORIGINAL" ON "EZJOBS"."EZ_DOC_04_ORIGINAL" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_05 definition

CREATE TABLE "EZJOBS"."EZ_DOC_05"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "DOC_GROUP_ID" VARCHAR2(10),
     "TITLE" VARCHAR2(2000) NOT NULL ENABLE,
     "CONTENT" VARCHAR2(4000),
     "TABLE_ID" NUMBER,
     "JOB_ID" NUMBER,
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "MEM_NAME" VARCHAR2(50),
     "JOB_NAME" VARCHAR2(64),
     "HOLD_YN" VARCHAR2(1),
     "FORCE_YN" VARCHAR2(1),
     "ORDER_DATE" VARCHAR2(8),
     "FROM_TIME" VARCHAR2(4),
     "CMD_LINE2" VARCHAR2(8),
     "T_SET" VARCHAR2(4000),
     "APPLY_CHECK" VARCHAR2(1),
     "WAIT_FOR_ODATE_YN" CHAR(1),
     "ORDER_ID" VARCHAR2(5),
     "STATUS" VARCHAR2(16),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "DESCRIPTION" VARCHAR2(4000),
     "ORDER_INTO_FOLDER" VARCHAR2(5)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_05" ON "EZJOBS"."EZ_DOC_05" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_05" ADD CONSTRAINT "PK_EZ_DOC_05" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_05"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_05" ON "EZJOBS"."EZ_DOC_05" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_06 definition

CREATE TABLE "EZJOBS"."EZ_DOC_06"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(2000),
     "CONTENT" VARCHAR2(4000),
     "DATA_CENTER" VARCHAR2(50),
     "TABLE_NAME" VARCHAR2(770),
     "FILE_NM" VARCHAR2(255),
     "APPLY_DATE" VARCHAR2(8),
     "APPLY_CHECK" VARCHAR2(1),
     "ACT_GB" VARCHAR2(1)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_06" ON "EZJOBS"."EZ_DOC_06" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_06" ADD CONSTRAINT "PK_EZ_DOC_06" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_06"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_06" ON "EZJOBS"."EZ_DOC_06" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_06_DETAIL definition

CREATE TABLE "EZJOBS"."EZ_DOC_06_DETAIL"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "SEQ" NUMBER NOT NULL ENABLE,
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "MEM_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "DESCRIPTION" VARCHAR2(4000),
     "AUTHOR" VARCHAR2(50),
     "OWNER" VARCHAR2(50),
     "PRIORITY" VARCHAR2(2),
     "CRITICAL" VARCHAR2(1),
     "TASK_TYPE" VARCHAR2(21),
     "CYCLIC" VARCHAR2(1),
     "NODE_ID" VARCHAR2(50),
     "RERUN_INTERVAL" VARCHAR2(6),
     "RERUN_INTERVAL_TIME" VARCHAR2(1),
     "MEM_LIB" VARCHAR2(255),
     "COMMAND" VARCHAR2(512),
     "CONFIRM_FLAG" VARCHAR2(1),
     "DAYS_CAL" VARCHAR2(50),
     "WEEKS_CAL" VARCHAR2(50),
     "RETRO" VARCHAR2(1),
     "MAX_WAIT" NUMBER,
     "RERUN_MAX" NUMBER,
     "TIME_FROM" VARCHAR2(4),
     "TIME_UNTIL" VARCHAR2(4),
     "MONTH_DAYS" VARCHAR2(160),
     "WEEK_DAYS" VARCHAR2(50),
     "MONTH_1" VARCHAR2(1),
     "MONTH_2" VARCHAR2(1),
     "MONTH_3" VARCHAR2(1),
     "MONTH_4" VARCHAR2(1),
     "MONTH_5" VARCHAR2(1),
     "MONTH_6" VARCHAR2(1),
     "MONTH_7" VARCHAR2(1),
     "MONTH_8" VARCHAR2(1),
     "MONTH_9" VARCHAR2(1),
     "MONTH_10" VARCHAR2(1),
     "MONTH_11" VARCHAR2(1),
     "MONTH_12" VARCHAR2(1),
     "COUNT_CYCLIC_FROM" VARCHAR2(10),
     "TIME_ZONE" VARCHAR2(9),
     "MULTIAGENT" VARCHAR2(1),
     "USER_DAILY" VARCHAR2(20),
     "SCHEDULE_AND_OR" VARCHAR2(1),
     "IN_CONDITIONS_OPT" VARCHAR2(10),
     "T_GENERAL_DATE" VARCHAR2(4000),
     "T_CONDITIONS_IN" VARCHAR2(4000),
     "T_CONDITIONS_OUT" VARCHAR2(4000),
     "T_RESOURCES_Q" VARCHAR2(4000),
     "T_RESOURCES_C" VARCHAR2(4000),
     "T_SET" VARCHAR2(4000),
     "T_STEPS" VARCHAR2(4000),
     "T_POSTPROC" VARCHAR2(4000),
     "T_SFILE" VARCHAR2(4000),
     "CONF_CAL" VARCHAR2(30),
     "SHIFT" VARCHAR2(10),
     "SHIFT_NUM" VARCHAR2(3),
     "T_TAG_NAME" VARCHAR2(4000),
     "INTERVAL_SEQUENCE" VARCHAR2(4000),
     "SPECIFIC_TIMES" VARCHAR2(4000),
     "TOLERANCE" NUMBER,
     "CYCLIC_TYPE" VARCHAR2(1),
     "ACTIVE_FROM" VARCHAR2(8),
     "ACTIVE_TILL" VARCHAR2(8),
     "DATES_STR" VARCHAR2(255),
     "APPLY_DATE" VARCHAR2(14),
     "APPLY_CHECK" VARCHAR2(1),
     "R_MSG" VARCHAR2(1000),
     "MONITOR_TIME" VARCHAR2(10),
     "MONITOR_INTERVAL" VARCHAR2(10),
     "FILESIZE_COMPARISON" VARCHAR2(10),
     "NUM_OF_ITERATIONS" VARCHAR2(10),
     "STOP_TIME" VARCHAR2(10),
     "IND_CYCLIC" VARCHAR2(1),
     "TABLE_NAME" VARCHAR2(770)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_06_DETAIL" ON "EZJOBS"."EZ_DOC_06_DETAIL" ("DOC_CD", "SEQ")
;
ALTER TABLE "EZJOBS"."EZ_DOC_06_DETAIL" ADD CONSTRAINT "PK_EZ_DOC_06_DETAIL" PRIMARY KEY ("DOC_CD", "SEQ")
    USING INDEX "EZJOBS"."PK_EZ_DOC_06_DETAIL"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_06_DETAIL" ON "EZJOBS"."EZ_DOC_06_DETAIL" ("DOC_CD", "SEQ")
;


-- EZJOBS.EZ_DOC_07 definition

CREATE TABLE "EZJOBS"."EZ_DOC_07"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(2000) NOT NULL ENABLE,
     "CONTENT" VARCHAR2(4000),
     "ORDER_ID" VARCHAR2(5) NOT NULL ENABLE,
     "ODATE" VARCHAR2(6) NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE,
     "TABLE_NAME" VARCHAR2(770) NOT NULL ENABLE,
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50),
     "JOB_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "BEFORE_STATUS" VARCHAR2(40) NOT NULL ENABLE,
     "AFTER_STATUS" VARCHAR2(15) NOT NULL ENABLE,
     "DESCRIPTION" VARCHAR2(4000),
     "APPLY_DATE" VARCHAR2(8)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_07" ON "EZJOBS"."EZ_DOC_07" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_07" ADD CONSTRAINT "PK_EZ_DOC_07" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_07"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_07" ON "EZJOBS"."EZ_DOC_07" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_08 definition

CREATE TABLE "EZJOBS"."EZ_DOC_08"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "TITLE" VARCHAR2(200) NOT NULL ENABLE,
     "CONTENT" VARCHAR2(4000),
     "DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE,
     "TABLE_NAME" VARCHAR2(770) NOT NULL ENABLE,
     "APPLICATION" VARCHAR2(50) NOT NULL ENABLE,
     "GROUP_NAME" VARCHAR2(50) NOT NULL ENABLE,
     "JOB_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "DESCRIPTION" VARCHAR2(4000),
     "ORDER_DATE" VARCHAR2(8) NOT NULL ENABLE,
     "FROM_TIME" VARCHAR2(5) NOT NULL ENABLE,
     "AFTER_STATUS" VARCHAR2(15) NOT NULL ENABLE,
     "ORDER_ID" VARCHAR2(10)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_08" ON "EZJOBS"."EZ_DOC_08" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_08" ADD CONSTRAINT "PK_EZ_DOC_08" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_08"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_08" ON "EZJOBS"."EZ_DOC_08" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_09 definition

CREATE TABLE "EZJOBS"."EZ_DOC_09"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "DOC_GB" VARCHAR2(2),
     "JOB_NAME" VARCHAR2(64),
     "TITLE" VARCHAR2(200),
     "DATA_CENTER" VARCHAR2(50),
     "APPLY_DATE" VARCHAR2(8)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_09" ON "EZJOBS"."EZ_DOC_09" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_09" ADD CONSTRAINT "PK_EZ_DOC_09" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_09"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_09" ON "EZJOBS"."EZ_DOC_09" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_10 definition

CREATE TABLE "EZJOBS"."EZ_DOC_10"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "ALARM_CD" NUMBER(38,0) NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(50),
     "JOB_NAME" VARCHAR2(64),
     "ERROR_DESCRIPTION" VARCHAR2(200),
     "MAIN_DOC_CD" VARCHAR2(16),
     "USER_CD" NUMBER,
     CONSTRAINT "PK_EZ_DOC_10_PK" PRIMARY KEY ("DOC_CD", "ALARM_CD")
         USING INDEX  ENABLE
) ;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_10_PK" ON "EZJOBS"."EZ_DOC_10" ("DOC_CD", "ALARM_CD")
;


-- EZJOBS.EZ_DOC_GROUP definition

CREATE TABLE "EZJOBS"."EZ_DOC_GROUP"
(	"DOC_GROUP_ID" VARCHAR2(10) NOT NULL ENABLE,
     "JOBGROUP_ID" VARCHAR2(5) NOT NULL ENABLE,
     "DOC_GROUP_NAME" VARCHAR2(100)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_GROUP" ON "EZJOBS"."EZ_DOC_GROUP" ("DOC_GROUP_ID")
;
ALTER TABLE "EZJOBS"."EZ_DOC_GROUP" ADD CONSTRAINT "PK_EZ_DOC_GROUP" PRIMARY KEY ("DOC_GROUP_ID")
    USING INDEX "EZJOBS"."PK_EZ_DOC_GROUP"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_GROUP" ON "EZJOBS"."EZ_DOC_GROUP" ("DOC_GROUP_ID")
;


-- EZJOBS.EZ_DOC_MASTER definition

CREATE TABLE "EZJOBS"."EZ_DOC_MASTER"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "DOC_GB" VARCHAR2(2) NOT NULL ENABLE,
     "USER_CD" NUMBER NOT NULL ENABLE,
     "DEPT_NM" VARCHAR2(200),
     "DUTY_NM" VARCHAR2(200),
     "STATE_CD" VARCHAR2(2) NOT NULL ENABLE,
     "DRAFT_DATE" DATE,
     "CUR_APPROVAL_SEQ" NUMBER,
     "DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "JOBGROUP_ID" VARCHAR2(5),
     "DOC_GROUP_ID" VARCHAR2(10),
     "APPLY_CD" VARCHAR2(2),
     "APPLY_DATE" DATE,
     "CANCEL_COMMENT" VARCHAR2(1000),
     "FAIL_COMMENT" VARCHAR2(4000),
     "MAIN_DOC_CD" VARCHAR2(16),
     "POST_APPROVAL_YN" CHAR(1),
     "ADMIN_APPROVAL_YN" VARCHAR2(1)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_MASTER" ON "EZJOBS"."EZ_DOC_MASTER" ("DOC_CD")
;
ALTER TABLE "EZJOBS"."EZ_DOC_MASTER" ADD CONSTRAINT "PK_EZ_DOC_MASTER" PRIMARY KEY ("DOC_CD")
    USING INDEX "EZJOBS"."PK_EZ_DOC_MASTER"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_MASTER" ON "EZJOBS"."EZ_DOC_MASTER" ("DOC_CD")
;


-- EZJOBS.EZ_DOC_SETVAR definition

CREATE TABLE "EZJOBS"."EZ_DOC_SETVAR"
(	"DOC_CD" VARCHAR2(16) NOT NULL ENABLE,
     "SEQ" NUMBER(38,0) NOT NULL ENABLE,
     "VAR_NAME" VARCHAR2(128) NOT NULL ENABLE,
     "VAR_VALUE" VARCHAR2(4000)
) ;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DOC_SETVAR" ON "EZJOBS"."EZ_DOC_SETVAR" ("DOC_CD", "SEQ")
;


-- EZJOBS.EZ_DUTY definition

CREATE TABLE "EZJOBS"."EZ_DUTY"
(	"DUTY_CD" NUMBER NOT NULL ENABLE,
     "DUTY_NM" VARCHAR2(200) NOT NULL ENABLE,
     "DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "DUTY_ID" VARCHAR2(200)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DUTY" ON "EZJOBS"."EZ_DUTY" ("DUTY_CD")
;
ALTER TABLE "EZJOBS"."EZ_DUTY" ADD CONSTRAINT "PK_EZ_DUTY" PRIMARY KEY ("DUTY_CD")
    USING INDEX "EZJOBS"."PK_EZ_DUTY"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_DUTY" ON "EZJOBS"."EZ_DUTY" ("DUTY_CD")
;


-- EZJOBS.EZ_DUTY_RELAY definition

CREATE TABLE "EZJOBS"."EZ_DUTY_RELAY"
(	"DUTY_CD" VARCHAR2(100),
     "DUTY_NM" VARCHAR2(100),
     "INS_DATE" DATE NOT NULL ENABLE
) ;


-- EZJOBS.EZ_GROUP_APPROVAL_GROUP definition

CREATE TABLE "EZJOBS"."EZ_GROUP_APPROVAL_GROUP"
(	"GROUP_LINE_GRP_CD" NUMBER NOT NULL ENABLE,
     "GROUP_LINE_GRP_NM" VARCHAR2(100) NOT NULL ENABLE,
     "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
     "OWNER_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_GROUP_APPROVAL_GROUP" ON "EZJOBS"."EZ_GROUP_APPROVAL_GROUP" ("GROUP_LINE_GRP_CD")
;
ALTER TABLE "EZJOBS"."EZ_GROUP_APPROVAL_GROUP" ADD CONSTRAINT "PK_EZ_GROUP_APPROVAL_GROUP" PRIMARY KEY ("GROUP_LINE_GRP_CD")
    USING INDEX "EZJOBS"."PK_EZ_GROUP_APPROVAL_GROUP"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_GROUP_APPROVAL_GROUP" ON "EZJOBS"."EZ_GROUP_APPROVAL_GROUP" ("GROUP_LINE_GRP_CD")
;


-- EZJOBS.EZ_GROUP_APPROVAL_LINE definition

CREATE TABLE "EZJOBS"."EZ_GROUP_APPROVAL_LINE"
(	"GROUP_LINE_CD" NUMBER NOT NULL ENABLE,
     "GROUP_LINE_GRP_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_SEQ" NUMBER NOT NULL ENABLE,
     "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_GROUP_APPROVAL_LINE" ON "EZJOBS"."EZ_GROUP_APPROVAL_LINE" ("GROUP_LINE_CD")
;
ALTER TABLE "EZJOBS"."EZ_GROUP_APPROVAL_LINE" ADD CONSTRAINT "PK_EZ_GROUP_APPROVAL_LINE" PRIMARY KEY ("GROUP_LINE_CD")
    USING INDEX "EZJOBS"."PK_EZ_GROUP_APPROVAL_LINE"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_GROUP_APPROVAL_LINE" ON "EZJOBS"."EZ_GROUP_APPROVAL_LINE" ("GROUP_LINE_CD")
;


-- EZJOBS.EZ_GRP_HOST definition

CREATE TABLE "EZJOBS"."EZ_GRP_HOST"
(	"GRP_CD" NUMBER NOT NULL ENABLE,
     "HOST_CD" NUMBER NOT NULL ENABLE,
     "INS_DATE" CHAR(14) NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_GRP_HOST" ON "EZJOBS"."EZ_GRP_HOST" ("GRP_CD", "HOST_CD")
;
ALTER TABLE "EZJOBS"."EZ_GRP_HOST" ADD CONSTRAINT "PK_EZ_GRP_HOST" PRIMARY KEY ("GRP_CD", "HOST_CD")
    USING INDEX "EZJOBS"."PK_EZ_GRP_HOST"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_GRP_HOST" ON "EZJOBS"."EZ_GRP_HOST" ("GRP_CD", "HOST_CD")
;


-- EZJOBS.EZ_HISTORY_001 definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE EZJOBS.EZ_HISTORY_001;

CREATE TABLE EZJOBS.EZ_HISTORY_001 (
                                         ORDER_ID VARCHAR2(5),
                                         APPLICATION VARCHAR2(64),
                                         GROUP_NAME VARCHAR2(64),
                                         MEMNAME VARCHAR2(64),
                                         RBA VARCHAR2(6),
                                         GRP_RBA VARCHAR2(6),
                                         MEM_LIB VARCHAR2(255),
                                         OWNER VARCHAR2(30),
                                         TASK_TYPE VARCHAR2(21),
                                         JOB_NAME VARCHAR2(64),
                                         JOB_ID VARCHAR2(17),
                                         ODATE VARCHAR2(6),
                                         MAX_WAIT NUMBER,
                                         DESCRIPTION VARCHAR2(4000),
                                         FROM_PGMSTEP VARCHAR2(8),
                                         FROM_PROCSTEP VARCHAR2(8),
                                         TO_PGMSTEP VARCHAR2(8),
                                         TO_PROCSTEP VARCHAR2(8),
                                         CONFIRM_FLAG VARCHAR2(1),
                                         PREVENT_NCT2 VARCHAR2(1),
                                         DOC_MEM VARCHAR2(64),
                                         DOC_LIB VARCHAR2(255),
                                         FROM_TIME VARCHAR2(4),
                                         TO_TIME VARCHAR2(4),
                                         "INTERVAL" VARCHAR2(6),
                                         RERUN_MEM VARCHAR2(8),
                                         NEXT_TIME VARCHAR2(14),
                                         PRIORITY VARCHAR2(2),
                                         CPU_ID VARCHAR2(50),
                                         NJE VARCHAR2(1),
                                         SEARCH_COUNT NUMBER,
                                         MAX_RERUN NUMBER,
                                         AUTO_ARCHIVE VARCHAR2(1),
                                         SYSDB VARCHAR2(1),
                                         MAX_DAYS NUMBER,
                                         MAX_RUNS NUMBER,
                                         AVG_RUNTIME VARCHAR2(6),
                                         STD_DEV VARCHAR2(6),
                                         SYSOPT VARCHAR2(16),
                                         FROM_CLASS VARCHAR2(1),
                                         PARM VARCHAR2(255),
                                         STATE_DIGITS VARCHAR2(15),
                                         STATUS VARCHAR2(16),
                                         STATE VARCHAR2(40),
                                         DELETE_FLAG VARCHAR2(1),
                                         SEQ_CNT NUMBER,
                                         START_TIME VARCHAR2(14),
                                         END_TIME VARCHAR2(14),
                                         RERUN_COUNTER NUMBER,
                                         NR_RECORDS NUMBER,
                                         OVER_LIB VARCHAR2(255),
                                         CMD_LINE VARCHAR2(512),
                                         CRITICAL VARCHAR2(1),
                                         CYCLIC VARCHAR2(1),
                                         DUE_IN VARCHAR2(4),
                                         DUE_OUT VARCHAR2(4),
                                         ELAPSED NUMBER,
                                         NODEGROUP VARCHAR2(50),
                                         NJE_NODE VARCHAR2(8),
                                         TASK_CLASS VARCHAR2(3),
                                         IND_CYCLIC VARCHAR2(1),
                                         RETEN_DAYS VARCHAR2(3),
                                         RETEN_GEN VARCHAR2(2),
                                         ORDER_TABLE VARCHAR2(770),
                                         ORDER_LIB VARCHAR2(44),
                                         STICKY_IND VARCHAR2(1),
                                         SEQ_CNT_ADDED NUMBER,
                                         SHORT_FFU VARCHAR2(12),
                                         DSECT_FFU VARCHAR2(100),
                                         ISN_ NUMBER,
                                         TIME_REF VARCHAR2(1),
                                         TIME_ZONE VARCHAR2(9),
                                         APPL_TYPE VARCHAR2(10),
                                         APPL_VER VARCHAR2(10),
                                         APPL_FORM VARCHAR2(30),
                                         CM_VER VARCHAR2(10),
                                         STATE_MASK VARCHAR2(9),
                                         MULTY_AGENT VARCHAR2(1),
                                         SCHEDULE_ENV VARCHAR2(16),
                                         SYS_AFFINITY VARCHAR2(5),
                                         REQ_NJE_NODE VARCHAR2(8),
                                         ADJUST_COND VARCHAR2(1),
                                         IN_SERVICE VARCHAR2(255),
                                         STAT_CAL VARCHAR2(30),
                                         STAT_PERIOD VARCHAR2(1),
                                         INSTREAM_JCL CLOB,
                                         USE_INSTREAM_JCL VARCHAR2(1),
                                         LPAR VARCHAR2(8),
                                         DUE_OUT_DAYSOFFSET VARCHAR2(3),
                                         FROM_DAYSOFFSET VARCHAR2(3),
                                         TO_DAYSOFFSET VARCHAR2(3),
                                         ORDER_TIME VARCHAR2(14),
                                         AVG_START_TIME VARCHAR2(6),
                                         CPU_TIME NUMBER,
                                         EM_STAT_CAL_CTM VARCHAR2(20),
                                         EM_STAT_CAL VARCHAR2(30),
                                         EM_STAT_PERIOD VARCHAR2(1),
                                         INTERVAL_SEQUENCE VARCHAR2(4000),
                                         SPECIFIC_TIMES VARCHAR2(4000),
                                         TOLERANCE NUMBER,
                                         CYCLIC_TYPE VARCHAR2(1),
                                         CURRENT_RUN NUMBER,
                                         ELAPSED_RUNTIME NUMBER,
                                         WORKLOADS VARCHAR2(525),
                                         DEF_NODEGROUP VARCHAR2(50),
                                         NODEGROUP_SET_BY VARCHAR2(1),
                                         FAILURE_RC VARCHAR2(5),
                                         FAILURE_RC_STEP VARCHAR2(8),
                                         FAILURE_RC_PROCSTEP VARCHAR2(8),
                                         HIGHEST_RC VARCHAR2(5),
                                         HIGHEST_RC_STEP VARCHAR2(8),
                                         HIGHEST_RC_PROCSTEP VARCHAR2(8),
                                         HIGHEST_RC_MEMNAME VARCHAR2(8),
                                         ASSOCIATED_RBC VARCHAR2(20),
                                         CM_STATUS VARCHAR2(32),
                                         DEPEND_SERVICE_IN VARCHAR2(1),
                                         DEPEND_SERVICE_OUT VARCHAR2(1),
                                         EM_STAT_DETAIL_DATA VARCHAR2(1500),
                                         PREV_ODATE_RERUN_COUNTER NUMBER,
                                         JOBRC VARCHAR2(5),
                                         REMOVEATONCE VARCHAR2(1),
                                         DAYSKEEPINNOTOK NUMBER,
                                         DELAY NUMBER,
                                         BIMINFO VARCHAR2(20),
                                         STD_DEV_START_TIME VARCHAR2(11),
                                         END_FOLDER VARCHAR2(1),
                                         CONSTRAINT SYS_C008381 CHECK ("ORDER_ID" IS NOT NULL),
                                         CONSTRAINT SYS_C008382 CHECK ("CONFIRM_FLAG" IS NOT NULL),
                                         CONSTRAINT SYS_C008383 CHECK ("AUTO_ARCHIVE" IS NOT NULL),
                                         CONSTRAINT SYS_C008384 CHECK ("SYSDB" IS NOT NULL),
                                         CONSTRAINT SYS_C008385 CHECK ("STATUS" IS NOT NULL),
                                         CONSTRAINT SYS_C008386 CHECK ("DELETE_FLAG" IS NOT NULL),
                                         CONSTRAINT SYS_C008387 CHECK ("ISN_" IS NOT NULL)
);
CREATE INDEX EZ_HISTORY_001_0 ON EZJOBS.EZ_HISTORY_001 (ORDER_ID);
CREATE INDEX EZ_HISTORY_001_1 ON EZJOBS.EZ_HISTORY_001 (ODATE);
CREATE INDEX EZ_HISTORY_001_2 ON EZJOBS.EZ_HISTORY_001 (START_TIME);
CREATE INDEX EZ_HISTORY_001_3 ON EZJOBS.EZ_HISTORY_001 (END_TIME);


-- EZJOBS.EZ_HISTORY_I_001 definition

CREATE TABLE "EZJOBS"."EZ_HISTORY_I_001"
(	"ORDER_ID" VARCHAR2(5) NOT NULL ENABLE,
     "CONDITION" VARCHAR2(255) NOT NULL ENABLE,
     "ODATE" VARCHAR2(4) NOT NULL ENABLE,
     "AND_OR" VARCHAR2(1) NOT NULL ENABLE,
     "PARENTHESES" VARCHAR2(2),
     "IGNORE" VARCHAR2(1),
     "ORDER_" NUMBER,
     "ISN_" NUMBER
) ;


-- EZJOBS.EZ_HISTORY_O_001 definition

CREATE TABLE "EZJOBS"."EZ_HISTORY_O_001"
(	"ORDER_ID" VARCHAR2(5) NOT NULL ENABLE,
     "CONDITION" VARCHAR2(255) NOT NULL ENABLE,
     "ODATE" VARCHAR2(4) NOT NULL ENABLE,
     "SIGN" VARCHAR2(1) NOT NULL ENABLE,
     "ISN_" NUMBER NOT NULL ENABLE
) ;


-- EZJOBS.EZ_HISTORY_SETVAR_001 definition

CREATE TABLE "EZJOBS"."EZ_HISTORY_SETVAR_001"
(	"ORDER_ID" VARCHAR2(5),
     "NAME" VARCHAR2(128),
     "VALUE" VARCHAR2(4000),
     "GLOBAL_IND" VARCHAR2(1),
     "ORDER_" NUMBER,
     "ISN_" NUMBER
) ;


-- EZJOBS.EZ_HOST definition

CREATE TABLE "EZJOBS"."EZ_HOST"
(	"HOST_CD" NUMBER NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(64) NOT NULL ENABLE,
     "AGENT" VARCHAR2(100) NOT NULL ENABLE,
     "AGENT_NM" VARCHAR2(400),
     "AGENT_ID" VARCHAR2(100),
     "AGENT_PW" VARCHAR2(100),
     "FILE_PATH" VARCHAR2(256),
     "ACCESS_GUBUN" VARCHAR2(1),
     "ACCESS_PORT" NUMBER,
     "SERVER_GUBUN" VARCHAR2(1),
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "SCODE_CD" VARCHAR2(10),
     "SERVER_LANG" VARCHAR2(1),
     "CERTIFY_GUBUN" VARCHAR2(1) DEFAULT 'P'
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_HOST" ON "EZJOBS"."EZ_HOST" ("HOST_CD")
;
ALTER TABLE "EZJOBS"."EZ_HOST" ADD CONSTRAINT "PK_EZ_HOST" PRIMARY KEY ("HOST_CD")
    USING INDEX "EZJOBS"."PK_EZ_HOST"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_HOST" ON "EZJOBS"."EZ_HOST" ("HOST_CD")
;


-- EZJOBS.EZ_JOBGROUP definition

CREATE TABLE "EZJOBS"."EZ_JOBGROUP"
(	"JOBGROUP_ID" VARCHAR2(5) NOT NULL ENABLE,
     "JOBGROUP_NAME" VARCHAR2(100),
     "INS_USER_CD" NUMBER(*,0),
     "INS_DATE" TIMESTAMP (6),
     "UDT_USER_CD" NUMBER(*,0),
     "UDT_DATE" TIMESTAMP (6),
     "CONTENT" VARCHAR2(4000)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOBGROUP" ON "EZJOBS"."EZ_JOBGROUP" ("JOBGROUP_ID")
;
ALTER TABLE "EZJOBS"."EZ_JOBGROUP" ADD CONSTRAINT "PK_EZ_JOBGROUP" PRIMARY KEY ("JOBGROUP_ID")
    USING INDEX "EZJOBS"."PK_EZ_JOBGROUP"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOBGROUP" ON "EZJOBS"."EZ_JOBGROUP" ("JOBGROUP_ID")
;


-- EZJOBS.EZ_JOBGROUP_JOB definition

CREATE TABLE "EZJOBS"."EZ_JOBGROUP_JOB"
(	"JOBGROUP_ID" VARCHAR2(5) NOT NULL ENABLE,
     "TABLE_ID" NUMBER(*,0) NOT NULL ENABLE,
     "JOB_ID" NUMBER(*,0) NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE,
     "INS_DATE" TIMESTAMP (6),
     "JOB_NAME" VARCHAR2(64),
     "TABLE_NAME" VARCHAR2(50),
     "APPLICATION" VARCHAR2(50),
     "GROUP_NAME" VARCHAR2(50)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOBGROUP_JOB" ON "EZJOBS"."EZ_JOBGROUP_JOB" ("JOBGROUP_ID", "TABLE_ID", "JOB_ID", "DATA_CENTER")
;
ALTER TABLE "EZJOBS"."EZ_JOBGROUP_JOB" ADD CONSTRAINT "PK_EZ_JOBGROUP_JOB" PRIMARY KEY ("JOBGROUP_ID", "TABLE_ID", "JOB_ID", "DATA_CENTER")
    USING INDEX "EZJOBS"."PK_EZ_JOBGROUP_JOB"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOBGROUP_JOB" ON "EZJOBS"."EZ_JOBGROUP_JOB" ("JOBGROUP_ID", "TABLE_ID", "JOB_ID", "DATA_CENTER")
;


-- EZJOBS.EZ_JOB_MAPPER definition

CREATE TABLE "EZJOBS"."EZ_JOB_MAPPER"
(	"DATA_CENTER" VARCHAR2(64),
     "JOB" VARCHAR2(64),
     "USER_CD_1" NUMBER,
     "USER_CD_2" NUMBER,
     "USER_CD_3" NUMBER,
     "USER_CD_4" NUMBER,
     "USER_CD_5" NUMBER,
     "USER_CD_6" NUMBER,
     "USER_CD_7" NUMBER,
     "USER_CD_8" NUMBER,
     "USER_CD_9" NUMBER,
     "USER_CD_10" NUMBER,
     "SMS_1" VARCHAR2(1),
     "SMS_2" VARCHAR2(1),
     "SMS_3" VARCHAR2(1),
     "SMS_4" VARCHAR2(1),
     "SMS_5" VARCHAR2(1),
     "SMS_6" VARCHAR2(1),
     "SMS_7" VARCHAR2(1),
     "SMS_8" VARCHAR2(1),
     "SMS_9" VARCHAR2(1),
     "SMS_10" VARCHAR2(1),
     "MAIL_1" VARCHAR2(1),
     "MAIL_2" VARCHAR2(1),
     "MAIL_3" VARCHAR2(1),
     "MAIL_4" VARCHAR2(1),
     "MAIL_5" VARCHAR2(1),
     "MAIL_6" VARCHAR2(1),
     "MAIL_7" VARCHAR2(1),
     "MAIL_8" VARCHAR2(1),
     "MAIL_9" VARCHAR2(1),
     "MAIL_10" VARCHAR2(1),
     "GRP_CD_1" NUMBER,
     "GRP_CD_2" NUMBER,
     "GRP_SMS_1" VARCHAR2(1),
     "GRP_SMS_2" VARCHAR2(1),
     "GRP_MAIL_1" VARCHAR2(1),
     "GRP_MAIL_2" VARCHAR2(1),
     "ERROR_DESCRIPTION" VARCHAR2(4000),
     "LATE_SUB" VARCHAR2(4),
     "LATE_TIME" VARCHAR2(4),
     "LATE_EXEC" VARCHAR2(10),
     "SUCCESS_SMS_YN" CHAR(1),
     "BATCHJOBGRADE" VARCHAR2(100),
     "JOBSCHEDGB" VARCHAR2(20),
     "CC_COUNT" VARCHAR2(10),
     "INS_USER_CD" NUMBER,
     "INS_DATE" DATE,
     "INS_USER_IP" VARCHAR2(50),
     "UDT_USER_CD" NUMBER,
     "UDT_DATE" DATE,
     "UDT_USER_IP" VARCHAR2(50),
     CONSTRAINT "PK_EZ_JOB_MAPPER" PRIMARY KEY ("DATA_CENTER", "JOB")
         USING INDEX  ENABLE
) ;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOB_MAPPER" ON "EZJOBS"."EZ_JOB_MAPPER" ("DATA_CENTER", "JOB")
;


-- EZJOBS.EZ_JOB_MAPPER_DOC definition

CREATE TABLE "EZJOBS"."EZ_JOB_MAPPER_DOC"
(	"DOC_CD" VARCHAR2(64),
     "DATA_CENTER" VARCHAR2(64),
     "JOB" VARCHAR2(64),
     "USER_CD_1" NUMBER,
     "USER_CD_2" NUMBER,
     "USER_CD_3" NUMBER,
     "USER_CD_4" NUMBER,
     "USER_CD_5" NUMBER,
     "USER_CD_6" NUMBER,
     "USER_CD_7" NUMBER,
     "USER_CD_8" NUMBER,
     "USER_CD_9" NUMBER,
     "USER_CD_10" NUMBER,
     "SMS_1" VARCHAR2(1),
     "SMS_2" VARCHAR2(1),
     "SMS_3" VARCHAR2(1),
     "SMS_4" VARCHAR2(1),
     "SMS_5" VARCHAR2(1),
     "SMS_6" VARCHAR2(1),
     "SMS_7" VARCHAR2(1),
     "SMS_8" VARCHAR2(1),
     "SMS_9" VARCHAR2(1),
     "SMS_10" VARCHAR2(1),
     "MAIL_1" VARCHAR2(1),
     "MAIL_2" VARCHAR2(1),
     "MAIL_3" VARCHAR2(1),
     "MAIL_4" VARCHAR2(1),
     "MAIL_5" VARCHAR2(1),
     "MAIL_6" VARCHAR2(1),
     "MAIL_7" VARCHAR2(1),
     "MAIL_8" VARCHAR2(1),
     "MAIL_9" VARCHAR2(1),
     "MAIL_10" VARCHAR2(1),
     "GRP_CD_1" NUMBER,
     "GRP_CD_2" NUMBER,
     "GRP_SMS_1" VARCHAR2(1),
     "GRP_SMS_2" VARCHAR2(1),
     "GRP_MAIL_1" VARCHAR2(1),
     "GRP_MAIL_2" VARCHAR2(1),
     "ERROR_DESCRIPTION" VARCHAR2(4000),
     "LATE_SUB" VARCHAR2(4),
     "LATE_TIME" VARCHAR2(4),
     "LATE_EXEC" VARCHAR2(10),
     "SUCCESS_SMS_YN" CHAR(1),
     "BATCHJOBGRADE" VARCHAR2(100),
     "JOBSCHEDGB" VARCHAR2(20),
     "CC_COUNT" VARCHAR2(10),
     "INS_USER_CD" NUMBER,
     "INS_DATE" DATE,
     "INS_USER_IP" VARCHAR2(50),
     "UDT_USER_CD" NUMBER,
     "UDT_DATE" DATE,
     "UDT_USER_IP" VARCHAR2(50),
     CONSTRAINT "PK_EZ_JOB_MAPPER_DOC" PRIMARY KEY ("DOC_CD", "DATA_CENTER", "JOB")
         USING INDEX  ENABLE
) ;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOB_MAPPER_DOC" ON "EZJOBS"."EZ_JOB_MAPPER_DOC" ("DOC_CD", "DATA_CENTER", "JOB")
;


-- EZJOBS.EZ_JOB_MAPPER_ORIGINAL definition

CREATE TABLE "EZJOBS"."EZ_JOB_MAPPER_ORIGINAL"
(	"DOC_CD" VARCHAR2(64),
     "DATA_CENTER" VARCHAR2(64),
     "JOB" VARCHAR2(64),
     "USER_CD_1" NUMBER,
     "USER_CD_2" NUMBER,
     "USER_CD_3" NUMBER,
     "USER_CD_4" NUMBER,
     "USER_CD_5" NUMBER,
     "USER_CD_6" NUMBER,
     "USER_CD_7" NUMBER,
     "USER_CD_8" NUMBER,
     "USER_CD_9" NUMBER,
     "USER_CD_10" NUMBER,
     "SMS_1" VARCHAR2(1),
     "SMS_2" VARCHAR2(1),
     "SMS_3" VARCHAR2(1),
     "SMS_4" VARCHAR2(1),
     "SMS_5" VARCHAR2(1),
     "SMS_6" VARCHAR2(1),
     "SMS_7" VARCHAR2(1),
     "SMS_8" VARCHAR2(1),
     "SMS_9" VARCHAR2(1),
     "SMS_10" VARCHAR2(1),
     "MAIL_1" VARCHAR2(1),
     "MAIL_2" VARCHAR2(1),
     "MAIL_3" VARCHAR2(1),
     "MAIL_4" VARCHAR2(1),
     "MAIL_5" VARCHAR2(1),
     "MAIL_6" VARCHAR2(1),
     "MAIL_7" VARCHAR2(1),
     "MAIL_8" VARCHAR2(1),
     "MAIL_9" VARCHAR2(1),
     "MAIL_10" VARCHAR2(1),
     "GRP_CD_1" NUMBER,
     "GRP_CD_2" NUMBER,
     "GRP_SMS_1" VARCHAR2(1),
     "GRP_SMS_2" VARCHAR2(1),
     "GRP_MAIL_1" VARCHAR2(1),
     "GRP_MAIL_2" VARCHAR2(1),
     "ERROR_DESCRIPTION" VARCHAR2(4000),
     "LATE_SUB" VARCHAR2(4),
     "LATE_TIME" VARCHAR2(4),
     "LATE_EXEC" VARCHAR2(10),
     "SUCCESS_SMS_YN" CHAR(1),
     "BATCHJOBGRADE" VARCHAR2(100),
     "JOBSCHEDGB" VARCHAR2(20),
     "CC_COUNT" VARCHAR2(10),
     "INS_USER_CD" NUMBER,
     "INS_DATE" DATE,
     "INS_USER_IP" VARCHAR2(50),
     "UDT_USER_CD" NUMBER,
     "UDT_DATE" DATE,
     "UDT_USER_IP" VARCHAR2(50),
     CONSTRAINT "PK_EZ_JOB_MAPPER_ORIGINAL" PRIMARY KEY ("DOC_CD", "DATA_CENTER", "JOB")
         USING INDEX  ENABLE
) ;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_JOB_MAPPER_ORIGINAL" ON "EZJOBS"."EZ_JOB_MAPPER_ORIGINAL" ("DOC_CD", "DATA_CENTER", "JOB")
;


-- EZJOBS.EZ_LOGIN_LOG definition

CREATE TABLE "EZJOBS"."EZ_LOGIN_LOG"
(	"LOGIN_CD" NUMBER NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_LOGIN_LOG" ON "EZJOBS"."EZ_LOGIN_LOG" ("LOGIN_CD")
;
ALTER TABLE "EZJOBS"."EZ_LOGIN_LOG" ADD CONSTRAINT "PK_EZ_LOGIN_LOG" PRIMARY KEY ("LOGIN_CD")
    USING INDEX "EZJOBS"."PK_EZ_LOGIN_LOG"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_LOGIN_LOG" ON "EZJOBS"."EZ_LOGIN_LOG" ("LOGIN_CD")
;


-- EZJOBS.EZ_MCODE definition

CREATE TABLE "EZJOBS"."EZ_MCODE"
(	"MCODE_CD" VARCHAR2(5) NOT NULL ENABLE,
     "MCODE_NM" VARCHAR2(80) NOT NULL ENABLE,
     "DEL_YN" VARCHAR2(1) NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "MCODE_DESC" VARCHAR2(4000)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_MCODE" ON "EZJOBS"."EZ_MCODE" ("MCODE_CD")
;
ALTER TABLE "EZJOBS"."EZ_MCODE" ADD CONSTRAINT "PK_EZ_MCODE" PRIMARY KEY ("MCODE_CD")
    USING INDEX "EZJOBS"."PK_EZ_MCODE"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_MCODE" ON "EZJOBS"."EZ_MCODE" ("MCODE_CD")
;


-- EZJOBS.EZ_OTP definition

CREATE TABLE "EZJOBS"."EZ_OTP"
(	"OTP_CD" NUMBER NOT NULL ENABLE,
     "OTP" VARCHAR2(100) NOT NULL ENABLE,
     "OTP_TIME" VARCHAR2(10) NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_OTP" ON "EZJOBS"."EZ_OTP" ("OTP_CD")
;
ALTER TABLE "EZJOBS"."EZ_OTP" ADD CONSTRAINT "PK_EZ_OTP" PRIMARY KEY ("OTP_CD")
    USING INDEX "EZJOBS"."PK_EZ_OTP"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_OTP" ON "EZJOBS"."EZ_OTP" ("OTP_CD")
;


-- EZJOBS.EZ_OVER_SEND definition

CREATE TABLE "EZJOBS"."EZ_OVER_SEND"
(	"DATA_CENTER" VARCHAR2(20),
     "SEND_DATE" DATE,
     "JOB_NAME" VARCHAR2(64),
     "DESCRIPTION" VARCHAR2(4000),
     "AVG_RUNTIME" VARCHAR2(12),
     "ALARM_STANDARD" VARCHAR2(64),
     "ALARM_TIME" VARCHAR2(64),
     "ALARM_OVER" VARCHAR2(64),
     "ALARM_OVER_TIME" VARCHAR2(64),
     "ORDER_ID" VARCHAR2(50),
     "ODATE" VARCHAR2(8)
) ;


-- EZJOBS.EZ_QUARTZ_LOG definition

CREATE TABLE "EZJOBS"."EZ_QUARTZ_LOG"
(	"QUARTZ_CD" NUMBER NOT NULL ENABLE,
     "QUARTZ_NAME" VARCHAR2(200),
     "TRACE_LOG_PATH" VARCHAR2(200),
     "STATUS_CD" VARCHAR2(2),
     "STATUS_LOG" VARCHAR2(4000),
     "INS_DATE" DATE
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_QUARTZ_LOG" ON "EZJOBS"."EZ_QUARTZ_LOG" ("QUARTZ_CD")
;
ALTER TABLE "EZJOBS"."EZ_QUARTZ_LOG" ADD CONSTRAINT "PK_EZ_QUARTZ_LOG" PRIMARY KEY ("QUARTZ_CD")
    USING INDEX "EZJOBS"."PK_EZ_QUARTZ_LOG"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_QUARTZ_LOG" ON "EZJOBS"."EZ_QUARTZ_LOG" ("QUARTZ_CD")
;


-- EZJOBS.EZ_RESOURCE definition

CREATE TABLE "EZJOBS"."EZ_RESOURCE"
(	"QRESNAME" VARCHAR2(64),
     "QRTOTAL" NUMBER,
     "QRUSED" NUMBER DEFAULT 0,
     "INS_DATE" DATE,
     "DATA_CENTER" VARCHAR2(64)
) ;


-- EZJOBS.EZ_RUNINFO_HISTORY definition

CREATE TABLE "EZJOBS"."EZ_RUNINFO_HISTORY"
(	"ORDER_ID" VARCHAR2(5) NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(20) NOT NULL ENABLE,
     "SCHED_TABLE" VARCHAR2(770) NOT NULL ENABLE,
     "APPLICATION" VARCHAR2(64),
     "GROUP_NAME" VARCHAR2(64),
     "JOB_NAME" VARCHAR2(64),
     "OWNER" VARCHAR2(30),
     "NODE_GROUP" VARCHAR2(50),
     "NODE_ID" VARCHAR2(50),
     "START_TIME" DATE,
     "END_TIME" DATE,
     "ODATE" VARCHAR2(6) NOT NULL ENABLE,
     "RERUN_COUNTER" NUMBER NOT NULL ENABLE,
     "STATUS" VARCHAR2(50),
     "DESCRIPTION" VARCHAR2(4000),
     "SYSOUT_YN" VARCHAR2(1) DEFAULT 'N',
     "SYSOUT" VARCHAR2(4000),
     "APPL_TYPE" VARCHAR2(10)
) ;

CREATE INDEX "EZJOBS"."EZ_RUNINFO_HISTORY_0" ON "EZJOBS"."EZ_RUNINFO_HISTORY" ("START_TIME")
;
CREATE INDEX "EZJOBS"."EZ_RUNINFO_HISTORY_1" ON "EZJOBS"."EZ_RUNINFO_HISTORY" ("END_TIME")
;


-- EZJOBS.EZ_SCODE definition

CREATE TABLE "EZJOBS"."EZ_SCODE"
(	"MCODE_CD" VARCHAR2(10) NOT NULL ENABLE,
     "SCODE_CD" VARCHAR2(10) NOT NULL ENABLE,
     "SCODE_NM" VARCHAR2(200) NOT NULL ENABLE,
     "ORDER_NO" NUMBER NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "SCODE_ENG_NM" VARCHAR2(200),
     "SCODE_DESC" VARCHAR2(4000),
     "SCODE_USE_YN" CHAR(1),
     "HOST_CD" NUMBER
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_SCODE" ON "EZJOBS"."EZ_SCODE" ("MCODE_CD", "SCODE_CD")
;
ALTER TABLE "EZJOBS"."EZ_SCODE" ADD CONSTRAINT "PK_EZ_SCODE" PRIMARY KEY ("MCODE_CD", "SCODE_CD")
    USING INDEX "EZJOBS"."PK_EZ_SCODE"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_SCODE" ON "EZJOBS"."EZ_SCODE" ("MCODE_CD", "SCODE_CD")
;


-- EZJOBS.EZ_SEND_LOG definition

CREATE TABLE "EZJOBS"."EZ_SEND_LOG"
(	"SEND_CD" NUMBER NOT NULL ENABLE,
     "DATA_CENTER" VARCHAR2(20) NOT NULL ENABLE,
     "JOB_NAME" VARCHAR2(64) NOT NULL ENABLE,
     "ORDER_ID" VARCHAR2(50),
     "SEND_GUBUN" VARCHAR2(5) NOT NULL ENABLE,
     "MESSAGE" VARCHAR2(1000) NOT NULL ENABLE,
     "SEND_INFO" VARCHAR2(100) NOT NULL ENABLE,
     "SEND_USER_CD" NUMBER NOT NULL ENABLE,
     "SEND_DATE" DATE NOT NULL ENABLE,
     "RETURN_CODE" CHAR(2),
     "RETURN_DATE" DATE,
     "SEND_DESC" VARCHAR2(20),
     "RERUN_COUNTER" NUMBER(38,0),
     "ODATE" VARCHAR2(8),
     "SEND_DESCRIPTION" VARCHAR2(100)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_SEND_LOG" ON "EZJOBS"."EZ_SEND_LOG" ("SEND_CD")
;
ALTER TABLE "EZJOBS"."EZ_SEND_LOG" ADD CONSTRAINT "PK_EZ_SEND_LOG" PRIMARY KEY ("SEND_CD")
    USING INDEX "EZJOBS"."PK_EZ_SEND_LOG"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_SEND_LOG" ON "EZJOBS"."EZ_SEND_LOG" ("SEND_CD")
;


-- EZJOBS.EZ_USER definition

CREATE TABLE "EZJOBS"."EZ_USER"
(	"USER_CD" NUMBER NOT NULL ENABLE,
     "USER_ID" VARCHAR2(50) NOT NULL ENABLE,
     "USER_NM" VARCHAR2(50) NOT NULL ENABLE,
     "USER_PW" VARCHAR2(512) NOT NULL ENABLE,
     "USER_GB" VARCHAR2(2) DEFAULT 'N' NOT NULL ENABLE,
     "NO_AUTH" VARCHAR2(4000),
     "DEPT_CD" NUMBER NOT NULL ENABLE,
     "DUTY_CD" NUMBER NOT NULL ENABLE,
     "DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "RETIRE_YN" VARCHAR2(1) DEFAULT 'N',
     "RESET_YN" VARCHAR2(1),
     "USER_EMAIL" VARCHAR2(100),
     "USER_HP" VARCHAR2(20),
     "USER_TEL" VARCHAR2(50),
     "SELECT_DATA_CENTER_CODE" VARCHAR2(20),
     "PW_FAIL_CNT" VARCHAR2(2),
     "PW_DATE" DATE,
     "BEFORE_PW" VARCHAR2(4000),
     "ACCOUNT_LOCK" VARCHAR2(1),
     "ABSENCE_START_DATE" DATE,
     "ABSENCE_END_DATE" DATE,
     "ABSENCE_REASON" VARCHAR2(200),
     "ABSENCE_USER_CD" NUMBER,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "DEFAULT_PAGING" VARCHAR2(5),
     "SELECT_TABLE_NAME" VARCHAR2(50),
     "SELECT_APPLICATION" VARCHAR2(50),
     "SELECT_GROUP_NAME" VARCHAR2(50),
     "USER_APPR_GB" VARCHAR2(2),
     "USER_IP" VARCHAR2(100)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_USER" ON "EZJOBS"."EZ_USER" ("USER_CD")
;
ALTER TABLE "EZJOBS"."EZ_USER" ADD CONSTRAINT "PK_EZ_USER" PRIMARY KEY ("USER_CD")
    USING INDEX "EZJOBS"."PK_EZ_USER"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_USER" ON "EZJOBS"."EZ_USER" ("USER_CD")
;


-- EZJOBS.EZ_USER_APPROVAL_GROUP definition

CREATE TABLE "EZJOBS"."EZ_USER_APPROVAL_GROUP"
(	"LINE_GRP_CD" NUMBER NOT NULL ENABLE,
     "LINE_GRP_NM" VARCHAR2(100) NOT NULL ENABLE,
     "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
     "OWNER_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "DOC_GUBUN" CHAR(2)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_USER_APPROVAL_GROUP" ON "EZJOBS"."EZ_USER_APPROVAL_GROUP" ("LINE_GRP_CD")
;
ALTER TABLE "EZJOBS"."EZ_USER_APPROVAL_GROUP" ADD CONSTRAINT "PK_EZ_USER_APPROVAL_GROUP" PRIMARY KEY ("LINE_GRP_CD")
    USING INDEX "EZJOBS"."PK_EZ_USER_APPROVAL_GROUP"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_USER_APPROVAL_GROUP" ON "EZJOBS"."EZ_USER_APPROVAL_GROUP" ("LINE_GRP_CD")
;


-- EZJOBS.EZ_USER_APPROVAL_LINE definition

CREATE TABLE "EZJOBS"."EZ_USER_APPROVAL_LINE"
(	"LINE_CD" NUMBER NOT NULL ENABLE,
     "LINE_GRP_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_SEQ" NUMBER NOT NULL ENABLE,
     "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
     "INS_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "APPROVAL_GB" CHAR(2)
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_USER_APPROVAL_LINE" ON "EZJOBS"."EZ_USER_APPROVAL_LINE" ("LINE_CD")
;
ALTER TABLE "EZJOBS"."EZ_USER_APPROVAL_LINE" ADD CONSTRAINT "PK_EZ_USER_APPROVAL_LINE" PRIMARY KEY ("LINE_CD")
    USING INDEX "EZJOBS"."PK_EZ_USER_APPROVAL_LINE"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_USER_APPROVAL_LINE" ON "EZJOBS"."EZ_USER_APPROVAL_LINE" ("LINE_CD")
;


-- EZJOBS.EZ_USER_FOLDER definition

CREATE TABLE "EZJOBS"."EZ_USER_FOLDER"
(	"USER_CD" NUMBER NOT NULL ENABLE,
     "FOLDER_AUTH" VARCHAR2(4000),
     "DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE
) ;


-- EZJOBS.EZ_USER_FOLDER_HISTORY definition

CREATE TABLE "EZJOBS"."EZ_USER_FOLDER_HISTORY"
(	"USER_CD" NUMBER NOT NULL ENABLE,
     "FOLDER_AUTH" VARCHAR2(4000),
     "DATA_CENTER" VARCHAR2(50) NOT NULL ENABLE,
     "STATUS_GB" VARCHAR2(10) NOT NULL ENABLE,
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE
) ;


-- EZJOBS.EZ_USER_HISTORY definition

CREATE TABLE "EZJOBS"."EZ_USER_HISTORY"
(	"USER_CD" NUMBER NOT NULL ENABLE,
     "USER_ID" VARCHAR2(50) NOT NULL ENABLE,
     "USER_NM" VARCHAR2(50) NOT NULL ENABLE,
     "FLAG" VARCHAR2(50),
     "USER_GB" VARCHAR2(2) DEFAULT 'N' NOT NULL ENABLE,
     "DEPT_CD" NUMBER NOT NULL ENABLE,
     "DUTY_CD" NUMBER NOT NULL ENABLE,
     "DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "RETIRE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
     "USER_EMAIL" VARCHAR2(100),
     "USER_HP" VARCHAR2(20),
     "USER_TEL" VARCHAR2(50),
     "SELECT_DATA_CENTER_CODE" VARCHAR2(20),
     "ACCOUNT_LOCK" VARCHAR2(1),
     "INS_DATE" DATE NOT NULL ENABLE,
     "INS_USER_CD" NUMBER NOT NULL ENABLE,
     "INS_USER_IP" VARCHAR2(50) NOT NULL ENABLE,
     "UDT_DATE" DATE,
     "UDT_USER_CD" NUMBER,
     "UDT_USER_IP" VARCHAR2(50),
     "SELECT_TABLE_NAME" VARCHAR2(50),
     "SELECT_APPLICATION" VARCHAR2(50),
     "SELECT_GROUP_NAME" VARCHAR2(50),
     "USER_APPR_GB" VARCHAR2(2),
     "REG_DATE" DATE NOT NULL ENABLE,
     "USER_IP" VARCHAR2(100)
) ;


-- EZJOBS.EZ_USER_RELAY definition

CREATE TABLE "EZJOBS"."EZ_USER_RELAY"
(	"USER_ID" VARCHAR2(100),
     "USER_NM" VARCHAR2(100),
     "DUTY_NM" VARCHAR2(100),
     "DEPT_NM" VARCHAR2(100),
     "USER_EMAIL" VARCHAR2(100),
     "USER_HP" VARCHAR2(100),
     "STATE_CD" VARCHAR2(100),
     "INS_DATE" DATE NOT NULL ENABLE
) ;


-- EZJOBS.EZ_WORK definition

CREATE TABLE "EZJOBS"."EZ_WORK"
(	"WORK_CD" NUMBER NOT NULL ENABLE,
     "WORK_DATE" VARCHAR2(8),
     "CONTENT" VARCHAR2(64),
     "USER_CD" NUMBER
) ;
CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_WORK" ON "EZJOBS"."EZ_WORK" ("WORK_CD")
;
ALTER TABLE "EZJOBS"."EZ_WORK" ADD CONSTRAINT "PK_EZ_WORK" PRIMARY KEY ("WORK_CD")
    USING INDEX "EZJOBS"."PK_EZ_WORK"  ENABLE;

CREATE UNIQUE INDEX "EZJOBS"."PK_EZ_WORK" ON "EZJOBS"."EZ_WORK" ("WORK_CD")
;