//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for active_task_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="active_task_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SMART_folder"/>
 *     &lt;enumeration value="sub_folder"/>
 *     &lt;enumeration value="job"/>
 *     &lt;enumeration value="cyclic_job"/>
 *     &lt;enumeration value="emergency_job"/>
 *     &lt;enumeration value="emergency_cyclic_job"/>
 *     &lt;enumeration value="task"/>
 *     &lt;enumeration value="cyclic_task"/>
 *     &lt;enumeration value="emergency_task"/>
 *     &lt;enumeration value="emergency_cyclic_task"/>
 *     &lt;enumeration value="command"/>
 *     &lt;enumeration value="dummy"/>
 *     &lt;enumeration value="detached"/>
 *     &lt;enumeration value="external"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "active_task_type")
@XmlEnum
public enum ActiveTaskType {

    @XmlEnumValue("SMART_folder")
    SMART_FOLDER("SMART_folder"),
    @XmlEnumValue("sub_folder")
    SUB_FOLDER("sub_folder"),
    @XmlEnumValue("job")
    JOB("job"),
    @XmlEnumValue("cyclic_job")
    CYCLIC_JOB("cyclic_job"),
    @XmlEnumValue("emergency_job")
    EMERGENCY_JOB("emergency_job"),
    @XmlEnumValue("emergency_cyclic_job")
    EMERGENCY_CYCLIC_JOB("emergency_cyclic_job"),
    @XmlEnumValue("task")
    TASK("task"),
    @XmlEnumValue("cyclic_task")
    CYCLIC_TASK("cyclic_task"),
    @XmlEnumValue("emergency_task")
    EMERGENCY_TASK("emergency_task"),
    @XmlEnumValue("emergency_cyclic_task")
    EMERGENCY_CYCLIC_TASK("emergency_cyclic_task"),
    @XmlEnumValue("command")
    COMMAND("command"),
    @XmlEnumValue("dummy")
    DUMMY("dummy"),
    @XmlEnumValue("detached")
    DETACHED("detached"),
    @XmlEnumValue("external")
    EXTERNAL("external");
    private final String value;

    ActiveTaskType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActiveTaskType fromValue(String v) {
        for (ActiveTaskType c: ActiveTaskType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
