//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bim_service_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bim_service_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="odate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="service_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="due_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="min_end_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="num_jobs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="complete_percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jobs_completed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jobs_without_stats" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="data_center" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="min_slack_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status_color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bim_service_type", propOrder = {
    "odate",
    "serviceName",
    "status",
    "dueTime",
    "minEndTime",
    "description",
    "numJobs",
    "completePercentage",
    "jobsCompleted",
    "jobsWithoutStats",
    "timeZone",
    "dataCenter",
    "priority",
    "minSlackTime",
    "statusColor"
})
public class BimServiceType {

    @XmlElement(required = true)
    protected String odate;
    @XmlElement(name = "service_name", required = true)
    protected String serviceName;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "due_time", required = true)
    protected String dueTime;
    @XmlElement(name = "min_end_time", required = true)
    protected String minEndTime;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "num_jobs", required = true)
    protected String numJobs;
    @XmlElement(name = "complete_percentage", required = true)
    protected String completePercentage;
    @XmlElement(name = "jobs_completed", required = true)
    protected String jobsCompleted;
    @XmlElement(name = "jobs_without_stats", required = true)
    protected String jobsWithoutStats;
    @XmlElement(name = "time_zone", required = true)
    protected String timeZone;
    @XmlElement(name = "data_center", required = true)
    protected String dataCenter;
    @XmlElement(required = true)
    protected String priority;
    @XmlElement(name = "min_slack_time", required = true)
    protected String minSlackTime;
    @XmlElement(name = "status_color", required = true)
    protected String statusColor;

    /**
     * Gets the value of the odate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdate() {
        return odate;
    }

    /**
     * Sets the value of the odate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdate(String value) {
        this.odate = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the dueTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueTime() {
        return dueTime;
    }

    /**
     * Sets the value of the dueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueTime(String value) {
        this.dueTime = value;
    }

    /**
     * Gets the value of the minEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinEndTime() {
        return minEndTime;
    }

    /**
     * Sets the value of the minEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinEndTime(String value) {
        this.minEndTime = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the numJobs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumJobs() {
        return numJobs;
    }

    /**
     * Sets the value of the numJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumJobs(String value) {
        this.numJobs = value;
    }

    /**
     * Gets the value of the completePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletePercentage() {
        return completePercentage;
    }

    /**
     * Sets the value of the completePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletePercentage(String value) {
        this.completePercentage = value;
    }

    /**
     * Gets the value of the jobsCompleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobsCompleted() {
        return jobsCompleted;
    }

    /**
     * Sets the value of the jobsCompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobsCompleted(String value) {
        this.jobsCompleted = value;
    }

    /**
     * Gets the value of the jobsWithoutStats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobsWithoutStats() {
        return jobsWithoutStats;
    }

    /**
     * Sets the value of the jobsWithoutStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobsWithoutStats(String value) {
        this.jobsWithoutStats = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the dataCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCenter() {
        return dataCenter;
    }

    /**
     * Sets the value of the dataCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCenter(String value) {
        this.dataCenter = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the minSlackTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinSlackTime() {
        return minSlackTime;
    }

    /**
     * Sets the value of the minSlackTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinSlackTime(String value) {
        this.minSlackTime = value;
    }

    /**
     * Gets the value of the statusColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusColor() {
        return statusColor;
    }

    /**
     * Sets the value of the statusColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusColor(String value) {
        this.statusColor = value;
    }

}
