//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for capture_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="capture_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="search_string" type="{http://www.bmc.com/ctmem/schema900}capture_string_type"/>
 *         &lt;element name="skip_lines" type="{http://www.bmc.com/ctmem/schema900}nine_digits_type" minOccurs="0"/>
 *         &lt;element name="skip_columns" type="{http://www.bmc.com/ctmem/schema900}nine_digits_type" minOccurs="0"/>
 *         &lt;element name="capture_by" type="{http://www.bmc.com/ctmem/schema900}capture_by_type" minOccurs="0"/>
 *         &lt;element name="delimiter" type="{http://www.bmc.com/ctmem/schema900}delimiter_type"/>
 *         &lt;element name="count_to_take" type="{http://www.bmc.com/ctmem/schema900}nine_digits_type" minOccurs="0"/>
 *         &lt;element name="variable" type="{http://www.bmc.com/ctmem/schema900}capture_var_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "capture_type", propOrder = {
    "searchString",
    "skipLines",
    "skipColumns",
    "captureBy",
    "delimiter",
    "countToTake",
    "variable"
})
public class CaptureType {

    @XmlElement(name = "search_string", required = true)
    protected String searchString;
    @XmlElement(name = "skip_lines")
    protected BigInteger skipLines;
    @XmlElement(name = "skip_columns")
    protected BigInteger skipColumns;
    @XmlElement(name = "capture_by")
    protected CaptureByType captureBy;
    @XmlElement(required = true)
    protected String delimiter;
    @XmlElement(name = "count_to_take")
    protected BigInteger countToTake;
    @XmlElement(required = true)
    protected String variable;

    /**
     * Gets the value of the searchString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchString() {
        return searchString;
    }

    /**
     * Sets the value of the searchString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchString(String value) {
        this.searchString = value;
    }

    /**
     * Gets the value of the skipLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSkipLines() {
        return skipLines;
    }

    /**
     * Sets the value of the skipLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSkipLines(BigInteger value) {
        this.skipLines = value;
    }

    /**
     * Gets the value of the skipColumns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSkipColumns() {
        return skipColumns;
    }

    /**
     * Sets the value of the skipColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSkipColumns(BigInteger value) {
        this.skipColumns = value;
    }

    /**
     * Gets the value of the captureBy property.
     * 
     * @return
     *     possible object is
     *     {@link CaptureByType }
     *     
     */
    public CaptureByType getCaptureBy() {
        return captureBy;
    }

    /**
     * Sets the value of the captureBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaptureByType }
     *     
     */
    public void setCaptureBy(CaptureByType value) {
        this.captureBy = value;
    }

    /**
     * Gets the value of the delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelimiter() {
        return delimiter;
    }

    /**
     * Sets the value of the delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelimiter(String value) {
        this.delimiter = value;
    }

    /**
     * Gets the value of the countToTake property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCountToTake() {
        return countToTake;
    }

    /**
     * Sets the value of the countToTake property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCountToTake(BigInteger value) {
        this.countToTake = value;
    }

    /**
     * Gets the value of the variable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariable() {
        return variable;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariable(String value) {
        this.variable = value;
    }

}
