//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for control_resource_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="control_resource_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.bmc.com/ctmem/schema900}exclusive_shared_type"/>
 *         &lt;element name="on_fail" type="{http://www.bmc.com/ctmem/schema900}keep_release_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "control_resource_type", propOrder = {
    "resource",
    "type",
    "onFail"
})
public class ControlResourceType {

    @XmlElement(required = true)
    protected String resource;
    @XmlElement(required = true)
    protected ExclusiveSharedType type;
    @XmlElement(name = "on_fail")
    protected String onFail;

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ExclusiveSharedType }
     *     
     */
    public ExclusiveSharedType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExclusiveSharedType }
     *     
     */
    public void setType(ExclusiveSharedType value) {
        this.type = value;
    }

    /**
     * Gets the value of the onFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnFail() {
        return onFail;
    }

    /**
     * Sets the value of the onFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnFail(String value) {
        this.onFail = value;
    }

}
