//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctb_step_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctb_step_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ctb_step_position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctb_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctb_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctb_arguments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctb_step_type", propOrder = {
    "ctbStepPosition",
    "ctbType",
    "ctbName",
    "ctbArguments"
})
public class CtbStepType {

    @XmlElement(name = "ctb_step_position", required = true)
    protected String ctbStepPosition;
    @XmlElement(name = "ctb_type", required = true)
    protected String ctbType;
    @XmlElement(name = "ctb_name", required = true)
    protected String ctbName;
    @XmlElement(name = "ctb_arguments", required = true)
    protected String ctbArguments;

    /**
     * Gets the value of the ctbStepPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtbStepPosition() {
        return ctbStepPosition;
    }

    /**
     * Sets the value of the ctbStepPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtbStepPosition(String value) {
        this.ctbStepPosition = value;
    }

    /**
     * Gets the value of the ctbType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtbType() {
        return ctbType;
    }

    /**
     * Sets the value of the ctbType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtbType(String value) {
        this.ctbType = value;
    }

    /**
     * Gets the value of the ctbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtbName() {
        return ctbName;
    }

    /**
     * Sets the value of the ctbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtbName(String value) {
        this.ctbName = value;
    }

    /**
     * Gets the value of the ctbArguments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtbArguments() {
        return ctbArguments;
    }

    /**
     * Sets the value of the ctbArguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtbArguments(String value) {
        this.ctbArguments = value;
    }

}
