//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for folder_info_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="folder_info_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="into_folder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="folder_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allow_dup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "folder_info_type", propOrder = {
    "intoFolder",
    "folderId",
    "allowDup"
})
public class FolderInfoType {

    @XmlElement(name = "into_folder", required = true)
    protected String intoFolder;
    @XmlElement(name = "folder_id")
    protected String folderId;
    @XmlElement(name = "allow_dup")
    protected String allowDup;

    /**
     * Gets the value of the intoFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntoFolder() {
        return intoFolder;
    }

    /**
     * Sets the value of the intoFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntoFolder(String value) {
        this.intoFolder = value;
    }

    /**
     * Gets the value of the folderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * Sets the value of the folderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderId(String value) {
        this.folderId = value;
    }

    /**
     * Gets the value of the allowDup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowDup() {
        return allowDup;
    }

    /**
     * Sets the value of the allowDup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowDup(String value) {
        this.allowDup = value;
    }

}
