//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bmc.ctmem.schema900 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestPollAjHold_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_aj_hold");
    private final static QName _FaultChangeAlertStatus_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_change_alert_status");
    private final static QName _RequestAjSetToOk_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_aj_set_to_ok");
    private final static QName _RequestPollAjKill_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_aj_kill");
    private final static QName _FaultAjSetToOk_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_aj_set_to_ok");
    private final static QName _FaultDefCreateSchedSubApplication_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_create_sched_sub_application");
    private final static QName _ResponsePollAjKill_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_aj_kill");
    private final static QName _ResponsePollDefUploadFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_def_upload_folder");
    private final static QName _FaultDefAddFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_add_folder");
    private final static QName _ResponseAddCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_add_condition");
    private final static QName _ResponseUnregister_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_unregister");
    private final static QName _RequestPollDefUploadFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_def_upload_folder");
    private final static QName _RequestAddCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_add_condition");
    private final static QName _FaultPollDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_delete_condition");
    private final static QName _FaultCheckUserToken_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_check_user_token");
    private final static QName _FaultDefCreateJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_create_jobs");
    private final static QName _FaultDefDeleteFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_delete_folder");
    private final static QName _ResponsePollDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_delete_condition");
    private final static QName _FaultAjFree_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_aj_free");
    private final static QName _ResponseAjSetToOk_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_aj_set_to_ok");
    private final static QName _RequestAjRerun_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_aj_rerun");
    private final static QName _RequestDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_delete_condition");
    private final static QName _FaultActRetrieveJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_act_retrieve_jobs");
    private final static QName _ResponsePollDefDeleteFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_def_delete_folder");
    private final static QName _ResponsePollOrderForce_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_order_force");
    private final static QName _ResponseCreateAj_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_create_aj");
    private final static QName _RequestJobTrack_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_job_track");
    private final static QName _FaultBimServicesInfo_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_bim_services_info");
    private final static QName _ResponseCheckUserToken_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_check_user_token");
    private final static QName _ResponseBimServicesInfo_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_bim_services_info");
    private final static QName _RequestPollOrderForce_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_order_force");
    private final static QName _ResponseClientKeepAlive_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_client_keep_alive");
    private final static QName _FaultDefAddJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_add_jobs");
    private final static QName _RequestPollDefDeleteFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_def_delete_folder");
    private final static QName _FaultUnknownRequest_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_unknown_request");
    private final static QName _FaultPollDefUploadFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_def_upload_folder");
    private final static QName _ResponseDefDeleteJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_def_delete_jobs");
    private final static QName _FaultJobTrack_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_job_track");
    private final static QName _RequestCreateAj_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_create_aj");
    private final static QName _FaultOrderForce_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_order_force");
    private final static QName _RequestChangeAlertStatus_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_change_alert_status");
    private final static QName _FaultCreateAj_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_create_aj");
    private final static QName _ResponseChangeAlertStatus_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_change_alert_status");
    private final static QName _FaultPollDefDeleteFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_def_delete_folder");
    private final static QName _FaultPollAjHold_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_aj_hold");
    private final static QName _ResponseDefCreateFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_def_create_folder");
    private final static QName _RequestPollAjSetToOk_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_aj_set_to_ok");
    private final static QName _RequestPollCreateAj_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_create_aj");
    private final static QName _RequestOrderForce_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_order_force");
    private final static QName _FaultDefUploadFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_upload_folder");
    private final static QName _ResponsePollAjHold_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_aj_hold");
    private final static QName _RequestPollAjRerun_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_aj_rerun");
    private final static QName _ResponseDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_delete_condition");
    private final static QName _RequestPollAddCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_add_condition");
    private final static QName _FaultDefCreateFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_create_folder");
    private final static QName _RequestPollAjFree_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_aj_free");
    private final static QName _RequestDefAddFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_def_add_folder");
    private final static QName _RequestDefUploadFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_def_upload_folder");
    private final static QName _ResponsePollAddDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_add_delete_condition");
    private final static QName _FaultPollAjSetToOk_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_aj_set_to_ok");
    private final static QName _ResponseListConditions_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_list_conditions");
    private final static QName _RequestDefCreateFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_def_create_folder");
    private final static QName _FaultPollAjFree_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_aj_free");
    private final static QName _FaultAddCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_add_condition");
    private final static QName _RequestDefDeleteJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_def_delete_jobs");
    private final static QName _ResponseActRetrieveJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_act_retrieve_jobs");
    private final static QName _RequestCheckUserToken_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_check_user_token");
    private final static QName _ResponsePollAddCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_add_condition");
    private final static QName _RequestAjConfirm_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_aj_confirm");
    private final static QName _ResponseAjRerun_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_aj_rerun");
    private final static QName _RequestBimServicesInfo_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_bim_services_info");
    private final static QName _RequestAjHold_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_aj_hold");
    private final static QName _FaultPollAjKill_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_aj_kill");
    private final static QName _ResponseDefDeleteFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_def_delete_folder");
    private final static QName _FaultPollAjRerun_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_aj_rerun");
    private final static QName _FaultDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_delete_condition");
    private final static QName _ResponseAjFree_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_aj_free");
    private final static QName _RequestDefAddJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_def_add_jobs");
    private final static QName _FaultAjHold_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_aj_hold");
    private final static QName _FaultAjConfirm_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_aj_confirm");
    private final static QName _FaultGetBimServicesInfo_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_get_bim_services_info");
    private final static QName _FaultRegister_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_register");
    private final static QName _RequestAjKill_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_aj_kill");
    private final static QName _RequestListConditions_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_list_conditions");
    private final static QName _ResponsePollAjFree_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_aj_free");
    private final static QName _FaultPollAjConfirm_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_aj_confirm");
    private final static QName _RequestClientKeepAlive_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_client_keep_alive");
    private final static QName _FaultPollAddDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_add_delete_condition");
    private final static QName _RequestPollAjConfirm_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_aj_confirm");
    private final static QName _RequestDefDeleteFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_def_delete_folder");
    private final static QName _ResponsePollCreateAj_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_create_aj");
    private final static QName _RequestPollDeleteCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll_delete_condition");
    private final static QName _ResponseJobTrack_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_job_track");
    private final static QName _FaultPollCreateAj_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_create_aj");
    private final static QName _FaultAjKill_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_aj_kill");
    private final static QName _FaultPollOrderForce_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_order_force");
    private final static QName _RequestPoll_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_poll");
    private final static QName _RequestAjFree_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_aj_free");
    private final static QName _RequestRegister_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_register");
    private final static QName _ResponseOrderForce_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_order_force");
    private final static QName _ResponseAjKill_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_aj_kill");
    private final static QName _ResponseRegister_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_register");
    private final static QName _FaultClientKeepAlive_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_client_keep_alive");
    private final static QName _FaultUnregister_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_unregister");
    private final static QName _FaultDefDeleteJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_def_delete_jobs");
    private final static QName _ResponsePollAjRerun_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_aj_rerun");
    private final static QName _ResponseDefAddFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_def_add_folder");
    private final static QName _ResponsePollAjSetToOk_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_aj_set_to_ok");
    private final static QName _ResponseAjHold_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_aj_hold");
    private final static QName _RequestActRetrieveJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_act_retrieve_jobs");
    private final static QName _ResponsePollAjConfirm_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_poll_aj_confirm");
    private final static QName _RequestUnregister_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "request_unregister");
    private final static QName _ResponseDefUploadFolder_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_def_upload_folder");
    private final static QName _ResponseDefAddJobs_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_def_add_jobs");
    private final static QName _FaultAjRerun_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_aj_rerun");
    private final static QName _FaultPollAddCondition_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "fault_poll_add_condition");
    private final static QName _ResponseAjConfirm_QNAME = new QName("http://www.bmc.com/ctmem/schema900", "response_aj_confirm");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bmc.ctmem.schema900
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link SimpleTokenResponseType }
     * 
     */
    public SimpleTokenResponseType createSimpleTokenResponseType() {
        return new SimpleTokenResponseType();
    }

    /**
     * Create an instance of {@link ResponsePollDefUploadFolderType }
     * 
     */
    public ResponsePollDefUploadFolderType createResponsePollDefUploadFolderType() {
        return new ResponsePollDefUploadFolderType();
    }

    /**
     * Create an instance of {@link ResponsePollGenActionType }
     * 
     */
    public ResponsePollGenActionType createResponsePollGenActionType() {
        return new ResponsePollGenActionType();
    }

    /**
     * Create an instance of {@link RequestPollType }
     * 
     */
    public RequestPollType createRequestPollType() {
        return new RequestPollType();
    }

    /**
     * Create an instance of {@link RequestGenActionType }
     * 
     */
    public RequestGenActionType createRequestGenActionType() {
        return new RequestGenActionType();
    }

    /**
     * Create an instance of {@link ResponsePollDefDeleteFolderType }
     * 
     */
    public ResponsePollDefDeleteFolderType createResponsePollDefDeleteFolderType() {
        return new ResponsePollDefDeleteFolderType();
    }

    /**
     * Create an instance of {@link RequestDeleteConditionType }
     * 
     */
    public RequestDeleteConditionType createRequestDeleteConditionType() {
        return new RequestDeleteConditionType();
    }

    /**
     * Create an instance of {@link ResponsePollAddDeleteConditionType }
     * 
     */
    public ResponsePollAddDeleteConditionType createResponsePollAddDeleteConditionType() {
        return new ResponsePollAddDeleteConditionType();
    }

    /**
     * Create an instance of {@link ResponseUserUnregistrationType }
     * 
     */
    public ResponseUserUnregistrationType createResponseUserUnregistrationType() {
        return new ResponseUserUnregistrationType();
    }

    /**
     * Create an instance of {@link RequestAddConditionType }
     * 
     */
    public RequestAddConditionType createRequestAddConditionType() {
        return new RequestAddConditionType();
    }

    /**
     * Create an instance of {@link ResponseGetBimServicesInfoType }
     * 
     */
    public ResponseGetBimServicesInfoType createResponseGetBimServicesInfoType() {
        return new ResponseGetBimServicesInfoType();
    }

    /**
     * Create an instance of {@link ResponseCheckUserTokenType }
     * 
     */
    public ResponseCheckUserTokenType createResponseCheckUserTokenType() {
        return new ResponseCheckUserTokenType();
    }

    /**
     * Create an instance of {@link RequestJobTrackType }
     * 
     */
    public RequestJobTrackType createRequestJobTrackType() {
        return new RequestJobTrackType();
    }

    /**
     * Create an instance of {@link ResponseOrderForceJobType }
     * 
     */
    public ResponseOrderForceJobType createResponseOrderForceJobType() {
        return new ResponseOrderForceJobType();
    }

    /**
     * Create an instance of {@link SimpleStatusResponseType }
     * 
     */
    public SimpleStatusResponseType createSimpleStatusResponseType() {
        return new SimpleStatusResponseType();
    }

    /**
     * Create an instance of {@link RequestCreateJobType }
     * 
     */
    public RequestCreateJobType createRequestCreateJobType() {
        return new RequestCreateJobType();
    }

    /**
     * Create an instance of {@link FaultJobTrackType }
     * 
     */
    public FaultJobTrackType createFaultJobTrackType() {
        return new FaultJobTrackType();
    }

    /**
     * Create an instance of {@link ResponseDefDeleteJobsType }
     * 
     */
    public ResponseDefDeleteJobsType createResponseDefDeleteJobsType() {
        return new ResponseDefDeleteJobsType();
    }

    /**
     * Create an instance of {@link ResponseDefCreateFolderType }
     * 
     */
    public ResponseDefCreateFolderType createResponseDefCreateFolderType() {
        return new ResponseDefCreateFolderType();
    }

    /**
     * Create an instance of {@link ResponseChangeAlertStatusType }
     * 
     */
    public ResponseChangeAlertStatusType createResponseChangeAlertStatusType() {
        return new ResponseChangeAlertStatusType();
    }

    /**
     * Create an instance of {@link RequestChangeAlertStatusType }
     * 
     */
    public RequestChangeAlertStatusType createRequestChangeAlertStatusType() {
        return new RequestChangeAlertStatusType();
    }

    /**
     * Create an instance of {@link RequestOrderForceJobType }
     * 
     */
    public RequestOrderForceJobType createRequestOrderForceJobType() {
        return new RequestOrderForceJobType();
    }

    /**
     * Create an instance of {@link RequestDefAddFolderType }
     * 
     */
    public RequestDefAddFolderType createRequestDefAddFolderType() {
        return new RequestDefAddFolderType();
    }

    /**
     * Create an instance of {@link RequestDefCreateFolderType }
     * 
     */
    public RequestDefCreateFolderType createRequestDefCreateFolderType() {
        return new RequestDefCreateFolderType();
    }

    /**
     * Create an instance of {@link ResponseListConditionsType }
     * 
     */
    public ResponseListConditionsType createResponseListConditionsType() {
        return new ResponseListConditionsType();
    }

    /**
     * Create an instance of {@link RequestDefUploadFolderType }
     * 
     */
    public RequestDefUploadFolderType createRequestDefUploadFolderType() {
        return new RequestDefUploadFolderType();
    }

    /**
     * Create an instance of {@link RequestGetBimServicesInfoType }
     * 
     */
    public RequestGetBimServicesInfoType createRequestGetBimServicesInfoType() {
        return new RequestGetBimServicesInfoType();
    }

    /**
     * Create an instance of {@link RequestCheckUserTokenType }
     * 
     */
    public RequestCheckUserTokenType createRequestCheckUserTokenType() {
        return new RequestCheckUserTokenType();
    }

    /**
     * Create an instance of {@link ResponseActRetrieveJobsType }
     * 
     */
    public ResponseActRetrieveJobsType createResponseActRetrieveJobsType() {
        return new ResponseActRetrieveJobsType();
    }

    /**
     * Create an instance of {@link RequestDefDeleteJobsType }
     * 
     */
    public RequestDefDeleteJobsType createRequestDefDeleteJobsType() {
        return new RequestDefDeleteJobsType();
    }

    /**
     * Create an instance of {@link RequestDefAddJobsType }
     * 
     */
    public RequestDefAddJobsType createRequestDefAddJobsType() {
        return new RequestDefAddJobsType();
    }

    /**
     * Create an instance of {@link RequestClientKeepAliveType }
     * 
     */
    public RequestClientKeepAliveType createRequestClientKeepAliveType() {
        return new RequestClientKeepAliveType();
    }

    /**
     * Create an instance of {@link RequestListConditionsType }
     * 
     */
    public RequestListConditionsType createRequestListConditionsType() {
        return new RequestListConditionsType();
    }

    /**
     * Create an instance of {@link ResponseJobTrackType }
     * 
     */
    public ResponseJobTrackType createResponseJobTrackType() {
        return new ResponseJobTrackType();
    }

    /**
     * Create an instance of {@link ResponseCreateJobType }
     * 
     */
    public ResponseCreateJobType createResponseCreateJobType() {
        return new ResponseCreateJobType();
    }

    /**
     * Create an instance of {@link RequestDefDeleteFolderType }
     * 
     */
    public RequestDefDeleteFolderType createRequestDefDeleteFolderType() {
        return new RequestDefDeleteFolderType();
    }

    /**
     * Create an instance of {@link ResponseUserRegistrationType }
     * 
     */
    public ResponseUserRegistrationType createResponseUserRegistrationType() {
        return new ResponseUserRegistrationType();
    }

    /**
     * Create an instance of {@link RequestUserRegistrationType }
     * 
     */
    public RequestUserRegistrationType createRequestUserRegistrationType() {
        return new RequestUserRegistrationType();
    }

    /**
     * Create an instance of {@link FaultPollOrderForceWithJobsType }
     * 
     */
    public FaultPollOrderForceWithJobsType createFaultPollOrderForceWithJobsType() {
        return new FaultPollOrderForceWithJobsType();
    }

    /**
     * Create an instance of {@link ResponseDefAddJobsType }
     * 
     */
    public ResponseDefAddJobsType createResponseDefAddJobsType() {
        return new ResponseDefAddJobsType();
    }

    /**
     * Create an instance of {@link RequestUserUnregistrationType }
     * 
     */
    public RequestUserUnregistrationType createRequestUserUnregistrationType() {
        return new RequestUserUnregistrationType();
    }

    /**
     * Create an instance of {@link RequestActRetrieveJobsType }
     * 
     */
    public RequestActRetrieveJobsType createRequestActRetrieveJobsType() {
        return new RequestActRetrieveJobsType();
    }

    /**
     * Create an instance of {@link ResponseDefAddFolderType }
     * 
     */
    public ResponseDefAddFolderType createResponseDefAddFolderType() {
        return new ResponseDefAddFolderType();
    }

    /**
     * Create an instance of {@link ResponseDataJobsJobJobDataCreateJobType }
     * 
     */
    public ResponseDataJobsJobJobDataCreateJobType createResponseDataJobsJobJobDataCreateJobType() {
        return new ResponseDataJobsJobJobDataCreateJobType();
    }

    /**
     * Create an instance of {@link DoCtbruleType }
     * 
     */
    public DoCtbruleType createDoCtbruleType() {
        return new DoCtbruleType();
    }

    /**
     * Create an instance of {@link DoCondType }
     * 
     */
    public DoCondType createDoCondType() {
        return new DoCondType();
    }

    /**
     * Create an instance of {@link ResponseDataJobsJobCreateJobType }
     * 
     */
    public ResponseDataJobsJobCreateJobType createResponseDataJobsJobCreateJobType() {
        return new ResponseDataJobsJobCreateJobType();
    }

    /**
     * Create an instance of {@link CaptureType }
     * 
     */
    public CaptureType createCaptureType() {
        return new CaptureType();
    }

    /**
     * Create an instance of {@link JobRuleBasedCalsType }
     * 
     */
    public JobRuleBasedCalsType createJobRuleBasedCalsType() {
        return new JobRuleBasedCalsType();
    }

    /**
     * Create an instance of {@link OnDoStatementType }
     * 
     */
    public OnDoStatementType createOnDoStatementType() {
        return new OnDoStatementType();
    }

    /**
     * Create an instance of {@link BimServicesSeqType }
     * 
     */
    public BimServicesSeqType createBimServicesSeqType() {
        return new BimServicesSeqType();
    }

    /**
     * Create an instance of {@link DoIfrerunType }
     * 
     */
    public DoIfrerunType createDoIfrerunType() {
        return new DoIfrerunType();
    }

    /**
     * Create an instance of {@link ControlResourcesType }
     * 
     */
    public ControlResourcesType createControlResourcesType() {
        return new ControlResourcesType();
    }

    /**
     * Create an instance of {@link DoType }
     * 
     */
    public DoType createDoType() {
        return new DoType();
    }

    /**
     * Create an instance of {@link CtbStepsType }
     * 
     */
    public CtbStepsType createCtbStepsType() {
        return new CtbStepsType();
    }

    /**
     * Create an instance of {@link FolderInfoType }
     * 
     */
    public FolderInfoType createFolderInfoType() {
        return new FolderInfoType();
    }

    /**
     * Create an instance of {@link ControlResourceType }
     * 
     */
    public ControlResourceType createControlResourceType() {
        return new ControlResourceType();
    }

    /**
     * Create an instance of {@link ActiveJobType }
     * 
     */
    public ActiveJobType createActiveJobType() {
        return new ActiveJobType();
    }

    /**
     * Create an instance of {@link ShoutType }
     * 
     */
    public ShoutType createShoutType() {
        return new ShoutType();
    }

    /**
     * Create an instance of {@link DoOutputType }
     * 
     */
    public DoOutputType createDoOutputType() {
        return new DoOutputType();
    }

    /**
     * Create an instance of {@link ResponseJobsActRetrieveJobsType }
     * 
     */
    public ResponseJobsActRetrieveJobsType createResponseJobsActRetrieveJobsType() {
        return new ResponseJobsActRetrieveJobsType();
    }

    /**
     * Create an instance of {@link OnDoStatementsType }
     * 
     */
    public OnDoStatementsType createOnDoStatementsType() {
        return new OnDoStatementsType();
    }

    /**
     * Create an instance of {@link JobsType }
     * 
     */
    public JobsType createJobsType() {
        return new JobsType();
    }

    /**
     * Create an instance of {@link DatesType }
     * 
     */
    public DatesType createDatesType() {
        return new DatesType();
    }

    /**
     * Create an instance of {@link DoRemedyType }
     * 
     */
    public DoRemedyType createDoRemedyType() {
        return new DoRemedyType();
    }

    /**
     * Create an instance of {@link VariableAssignmentsType }
     * 
     */
    public VariableAssignmentsType createVariableAssignmentsType() {
        return new VariableAssignmentsType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link ListConditionType }
     * 
     */
    public ListConditionType createListConditionType() {
        return new ListConditionType();
    }

    /**
     * Create an instance of {@link StepRangesType }
     * 
     */
    public StepRangesType createStepRangesType() {
        return new StepRangesType();
    }

    /**
     * Create an instance of {@link ResponseDataJobsOrderForceJobType }
     * 
     */
    public ResponseDataJobsOrderForceJobType createResponseDataJobsOrderForceJobType() {
        return new ResponseDataJobsOrderForceJobType();
    }

    /**
     * Create an instance of {@link ResponseJobsJobJobDataJobTrackType }
     * 
     */
    public ResponseJobsJobJobDataJobTrackType createResponseJobsJobJobDataJobTrackType() {
        return new ResponseJobsJobJobDataJobTrackType();
    }

    /**
     * Create an instance of {@link FolderType }
     * 
     */
    public FolderType createFolderType() {
        return new FolderType();
    }

    /**
     * Create an instance of {@link DefJobType }
     * 
     */
    public DefJobType createDefJobType() {
        return new DefJobType();
    }

    /**
     * Create an instance of {@link ResponseDataJobsCreateJobType }
     * 
     */
    public ResponseDataJobsCreateJobType createResponseDataJobsCreateJobType() {
        return new ResponseDataJobsCreateJobType();
    }

    /**
     * Create an instance of {@link IntervalSequenceType }
     * 
     */
    public IntervalSequenceType createIntervalSequenceType() {
        return new IntervalSequenceType();
    }

    /**
     * Create an instance of {@link SmartFolderType }
     * 
     */
    public SmartFolderType createSmartFolderType() {
        return new SmartFolderType();
    }

    /**
     * Create an instance of {@link OnStatementOutputType }
     * 
     */
    public OnStatementOutputType createOnStatementOutputType() {
        return new OnStatementOutputType();
    }

    /**
     * Create an instance of {@link AnyFolderType }
     * 
     */
    public AnyFolderType createAnyFolderType() {
        return new AnyFolderType();
    }

    /**
     * Create an instance of {@link OutConditionsType }
     * 
     */
    public OutConditionsType createOutConditionsType() {
        return new OutConditionsType();
    }

    /**
     * Create an instance of {@link SubFolderAttributesType }
     * 
     */
    public SubFolderAttributesType createSubFolderAttributesType() {
        return new SubFolderAttributesType();
    }

    /**
     * Create an instance of {@link StepRangeType }
     * 
     */
    public StepRangeType createStepRangeType() {
        return new StepRangeType();
    }

    /**
     * Create an instance of {@link SubFoldersType }
     * 
     */
    public SubFoldersType createSubFoldersType() {
        return new SubFoldersType();
    }

    /**
     * Create an instance of {@link SearchCriterionType }
     * 
     */
    public SearchCriterionType createSearchCriterionType() {
        return new SearchCriterionType();
    }

    /**
     * Create an instance of {@link FolderRuleBasedCalsType }
     * 
     */
    public FolderRuleBasedCalsType createFolderRuleBasedCalsType() {
        return new FolderRuleBasedCalsType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link ResponseJobDataActRetrieveJobsType }
     * 
     */
    public ResponseJobDataActRetrieveJobsType createResponseJobDataActRetrieveJobsType() {
        return new ResponseJobDataActRetrieveJobsType();
    }

    /**
     * Create an instance of {@link CtbStepType }
     * 
     */
    public CtbStepType createCtbStepType() {
        return new CtbStepType();
    }

    /**
     * Create an instance of {@link QuantitativeResourcesType }
     * 
     */
    public QuantitativeResourcesType createQuantitativeResourcesType() {
        return new QuantitativeResourcesType();
    }

    /**
     * Create an instance of {@link RuleBasedCalType }
     * 
     */
    public RuleBasedCalType createRuleBasedCalType() {
        return new RuleBasedCalType();
    }

    /**
     * Create an instance of {@link OnStatementsType }
     * 
     */
    public OnStatementsType createOnStatementsType() {
        return new OnStatementsType();
    }

    /**
     * Create an instance of {@link JobRuleBasedCalType }
     * 
     */
    public JobRuleBasedCalType createJobRuleBasedCalType() {
        return new JobRuleBasedCalType();
    }

    /**
     * Create an instance of {@link CriterionType }
     * 
     */
    public CriterionType createCriterionType() {
        return new CriterionType();
    }

    /**
     * Create an instance of {@link SubRuleBasedCalType }
     * 
     */
    public SubRuleBasedCalType createSubRuleBasedCalType() {
        return new SubRuleBasedCalType();
    }

    /**
     * Create an instance of {@link ResponseDataJobsJobDataOrderForceJobType }
     * 
     */
    public ResponseDataJobsJobDataOrderForceJobType createResponseDataJobsJobDataOrderForceJobType() {
        return new ResponseDataJobsJobDataOrderForceJobType();
    }

    /**
     * Create an instance of {@link ErrorListType }
     * 
     */
    public ErrorListType createErrorListType() {
        return new ErrorListType();
    }

    /**
     * Create an instance of {@link OnStatementType }
     * 
     */
    public OnStatementType createOnStatementType() {
        return new OnStatementType();
    }

    /**
     * Create an instance of {@link InConditionType }
     * 
     */
    public InConditionType createInConditionType() {
        return new InConditionType();
    }

    /**
     * Create an instance of {@link ResponseJobActRetrieveJobsType }
     * 
     */
    public ResponseJobActRetrieveJobsType createResponseJobActRetrieveJobsType() {
        return new ResponseJobActRetrieveJobsType();
    }

    /**
     * Create an instance of {@link DoVariableType }
     * 
     */
    public DoVariableType createDoVariableType() {
        return new DoVariableType();
    }

    /**
     * Create an instance of {@link InConditionsType }
     * 
     */
    public InConditionsType createInConditionsType() {
        return new InConditionsType();
    }

    /**
     * Create an instance of {@link DoForcejobType }
     * 
     */
    public DoForcejobType createDoForcejobType() {
        return new DoForcejobType();
    }

    /**
     * Create an instance of {@link ResponseJobsJobJobTrackType }
     * 
     */
    public ResponseJobsJobJobTrackType createResponseJobsJobJobTrackType() {
        return new ResponseJobsJobJobTrackType();
    }

    /**
     * Create an instance of {@link SubFolderType }
     * 
     */
    public SubFolderType createSubFolderType() {
        return new SubFolderType();
    }

    /**
     * Create an instance of {@link PipeType }
     * 
     */
    public PipeType createPipeType() {
        return new PipeType();
    }

    /**
     * Create an instance of {@link ShoutsType }
     * 
     */
    public ShoutsType createShoutsType() {
        return new ShoutsType();
    }

    /**
     * Create an instance of {@link DoShoutType }
     * 
     */
    public DoShoutType createDoShoutType() {
        return new DoShoutType();
    }

    /**
     * Create an instance of {@link DoMailType }
     * 
     */
    public DoMailType createDoMailType() {
        return new DoMailType();
    }

    /**
     * Create an instance of {@link ResponseDataJobsJobOrderForceJobType }
     * 
     */
    public ResponseDataJobsJobOrderForceJobType createResponseDataJobsJobOrderForceJobType() {
        return new ResponseDataJobsJobOrderForceJobType();
    }

    /**
     * Create an instance of {@link FaultOrderForceWithJobsType }
     * 
     */
    public FaultOrderForceWithJobsType createFaultOrderForceWithJobsType() {
        return new FaultOrderForceWithJobsType();
    }

    /**
     * Create an instance of {@link OutConditionType }
     * 
     */
    public OutConditionType createOutConditionType() {
        return new OutConditionType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link VariableAssignmentType }
     * 
     */
    public VariableAssignmentType createVariableAssignmentType() {
        return new VariableAssignmentType();
    }

    /**
     * Create an instance of {@link FaultJobTrackSingleJobType }
     * 
     */
    public FaultJobTrackSingleJobType createFaultJobTrackSingleJobType() {
        return new FaultJobTrackSingleJobType();
    }

    /**
     * Create an instance of {@link RequestAddDeleteConditionType }
     * 
     */
    public RequestAddDeleteConditionType createRequestAddDeleteConditionType() {
        return new RequestAddDeleteConditionType();
    }

    /**
     * Create an instance of {@link DefJobsType }
     * 
     */
    public DefJobsType createDefJobsType() {
        return new DefJobsType();
    }

    /**
     * Create an instance of {@link SmartFolderAttributesType }
     * 
     */
    public SmartFolderAttributesType createSmartFolderAttributesType() {
        return new SmartFolderAttributesType();
    }

    /**
     * Create an instance of {@link SpecificTimesType }
     * 
     */
    public SpecificTimesType createSpecificTimesType() {
        return new SpecificTimesType();
    }

    /**
     * Create an instance of {@link CapturesType }
     * 
     */
    public CapturesType createCapturesType() {
        return new CapturesType();
    }

    /**
     * Create an instance of {@link ResponseJobsJobTrackType }
     * 
     */
    public ResponseJobsJobTrackType createResponseJobsJobTrackType() {
        return new ResponseJobsJobTrackType();
    }

    /**
     * Create an instance of {@link DoStatementsType }
     * 
     */
    public DoStatementsType createDoStatementsType() {
        return new DoStatementsType();
    }

    /**
     * Create an instance of {@link FaultJobTrackSingleJobDataType }
     * 
     */
    public FaultJobTrackSingleJobDataType createFaultJobTrackSingleJobDataType() {
        return new FaultJobTrackSingleJobDataType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link PipesType }
     * 
     */
    public PipesType createPipesType() {
        return new PipesType();
    }

    /**
     * Create an instance of {@link QuantitativeResourceType }
     * 
     */
    public QuantitativeResourceType createQuantitativeResourceType() {
        return new QuantitativeResourceType();
    }

    /**
     * Create an instance of {@link BimServiceType }
     * 
     */
    public BimServiceType createBimServiceType() {
        return new BimServiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_aj_hold")
    public JAXBElement<RequestPollType> createRequestPollAjHold(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAjHold_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_change_alert_status")
    public JAXBElement<FaultType> createFaultChangeAlertStatus(FaultType value) {
        return new JAXBElement<FaultType>(_FaultChangeAlertStatus_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_aj_set_to_ok")
    public JAXBElement<RequestGenActionType> createRequestAjSetToOk(RequestGenActionType value) {
        return new JAXBElement<RequestGenActionType>(_RequestAjSetToOk_QNAME, RequestGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_aj_kill")
    public JAXBElement<RequestPollType> createRequestPollAjKill(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAjKill_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_aj_set_to_ok")
    public JAXBElement<FaultType> createFaultAjSetToOk(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAjSetToOk_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_create_sched_sub_application")
    public JAXBElement<FaultType> createFaultDefCreateSchedSubApplication(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefCreateSchedSubApplication_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_aj_kill")
    public JAXBElement<ResponsePollGenActionType> createResponsePollAjKill(ResponsePollGenActionType value) {
        return new JAXBElement<ResponsePollGenActionType>(_ResponsePollAjKill_QNAME, ResponsePollGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollDefUploadFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_def_upload_folder")
    public JAXBElement<ResponsePollDefUploadFolderType> createResponsePollDefUploadFolder(ResponsePollDefUploadFolderType value) {
        return new JAXBElement<ResponsePollDefUploadFolderType>(_ResponsePollDefUploadFolder_QNAME, ResponsePollDefUploadFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_add_folder")
    public JAXBElement<FaultType> createFaultDefAddFolder(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefAddFolder_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_add_condition")
    public JAXBElement<SimpleTokenResponseType> createResponseAddCondition(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAddCondition_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseUserUnregistrationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_unregister")
    public JAXBElement<ResponseUserUnregistrationType> createResponseUnregister(ResponseUserUnregistrationType value) {
        return new JAXBElement<ResponseUserUnregistrationType>(_ResponseUnregister_QNAME, ResponseUserUnregistrationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_def_upload_folder")
    public JAXBElement<RequestPollType> createRequestPollDefUploadFolder(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollDefUploadFolder_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestAddConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_add_condition")
    public JAXBElement<RequestAddConditionType> createRequestAddCondition(RequestAddConditionType value) {
        return new JAXBElement<RequestAddConditionType>(_RequestAddCondition_QNAME, RequestAddConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_delete_condition")
    public JAXBElement<FaultType> createFaultPollDeleteCondition(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollDeleteCondition_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_check_user_token")
    public JAXBElement<FaultType> createFaultCheckUserToken(FaultType value) {
        return new JAXBElement<FaultType>(_FaultCheckUserToken_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_create_jobs")
    public JAXBElement<FaultType> createFaultDefCreateJobs(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefCreateJobs_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_delete_folder")
    public JAXBElement<FaultType> createFaultDefDeleteFolder(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefDeleteFolder_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollAddDeleteConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_delete_condition")
    public JAXBElement<ResponsePollAddDeleteConditionType> createResponsePollDeleteCondition(ResponsePollAddDeleteConditionType value) {
        return new JAXBElement<ResponsePollAddDeleteConditionType>(_ResponsePollDeleteCondition_QNAME, ResponsePollAddDeleteConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_aj_free")
    public JAXBElement<FaultType> createFaultAjFree(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAjFree_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_aj_set_to_ok")
    public JAXBElement<SimpleTokenResponseType> createResponseAjSetToOk(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAjSetToOk_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_aj_rerun")
    public JAXBElement<RequestGenActionType> createRequestAjRerun(RequestGenActionType value) {
        return new JAXBElement<RequestGenActionType>(_RequestAjRerun_QNAME, RequestGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDeleteConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_delete_condition")
    public JAXBElement<RequestDeleteConditionType> createRequestDeleteCondition(RequestDeleteConditionType value) {
        return new JAXBElement<RequestDeleteConditionType>(_RequestDeleteCondition_QNAME, RequestDeleteConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_act_retrieve_jobs")
    public JAXBElement<FaultType> createFaultActRetrieveJobs(FaultType value) {
        return new JAXBElement<FaultType>(_FaultActRetrieveJobs_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollDefDeleteFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_def_delete_folder")
    public JAXBElement<ResponsePollDefDeleteFolderType> createResponsePollDefDeleteFolder(ResponsePollDefDeleteFolderType value) {
        return new JAXBElement<ResponsePollDefDeleteFolderType>(_ResponsePollDefDeleteFolder_QNAME, ResponsePollDefDeleteFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseOrderForceJobType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_order_force")
    public JAXBElement<ResponseOrderForceJobType> createResponsePollOrderForce(ResponseOrderForceJobType value) {
        return new JAXBElement<ResponseOrderForceJobType>(_ResponsePollOrderForce_QNAME, ResponseOrderForceJobType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_create_aj")
    public JAXBElement<SimpleTokenResponseType> createResponseCreateAj(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseCreateAj_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestJobTrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_job_track")
    public JAXBElement<RequestJobTrackType> createRequestJobTrack(RequestJobTrackType value) {
        return new JAXBElement<RequestJobTrackType>(_RequestJobTrack_QNAME, RequestJobTrackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_bim_services_info")
    public JAXBElement<FaultType> createFaultBimServicesInfo(FaultType value) {
        return new JAXBElement<FaultType>(_FaultBimServicesInfo_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseCheckUserTokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_check_user_token")
    public JAXBElement<ResponseCheckUserTokenType> createResponseCheckUserToken(ResponseCheckUserTokenType value) {
        return new JAXBElement<ResponseCheckUserTokenType>(_ResponseCheckUserToken_QNAME, ResponseCheckUserTokenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseGetBimServicesInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_bim_services_info")
    public JAXBElement<ResponseGetBimServicesInfoType> createResponseBimServicesInfo(ResponseGetBimServicesInfoType value) {
        return new JAXBElement<ResponseGetBimServicesInfoType>(_ResponseBimServicesInfo_QNAME, ResponseGetBimServicesInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_order_force")
    public JAXBElement<RequestPollType> createRequestPollOrderForce(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollOrderForce_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_client_keep_alive")
    public JAXBElement<SimpleStatusResponseType> createResponseClientKeepAlive(SimpleStatusResponseType value) {
        return new JAXBElement<SimpleStatusResponseType>(_ResponseClientKeepAlive_QNAME, SimpleStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_add_jobs")
    public JAXBElement<FaultType> createFaultDefAddJobs(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefAddJobs_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_def_delete_folder")
    public JAXBElement<RequestPollType> createRequestPollDefDeleteFolder(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollDefDeleteFolder_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_unknown_request")
    public JAXBElement<FaultType> createFaultUnknownRequest(FaultType value) {
        return new JAXBElement<FaultType>(_FaultUnknownRequest_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_def_upload_folder")
    public JAXBElement<FaultType> createFaultPollDefUploadFolder(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollDefUploadFolder_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseDefDeleteJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_def_delete_jobs")
    public JAXBElement<ResponseDefDeleteJobsType> createResponseDefDeleteJobs(ResponseDefDeleteJobsType value) {
        return new JAXBElement<ResponseDefDeleteJobsType>(_ResponseDefDeleteJobs_QNAME, ResponseDefDeleteJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultJobTrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_job_track")
    public JAXBElement<FaultJobTrackType> createFaultJobTrack(FaultJobTrackType value) {
        return new JAXBElement<FaultJobTrackType>(_FaultJobTrack_QNAME, FaultJobTrackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestCreateJobType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_create_aj")
    public JAXBElement<RequestCreateJobType> createRequestCreateAj(RequestCreateJobType value) {
        return new JAXBElement<RequestCreateJobType>(_RequestCreateAj_QNAME, RequestCreateJobType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_order_force")
    public JAXBElement<FaultType> createFaultOrderForce(FaultType value) {
        return new JAXBElement<FaultType>(_FaultOrderForce_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestChangeAlertStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_change_alert_status")
    public JAXBElement<RequestChangeAlertStatusType> createRequestChangeAlertStatus(RequestChangeAlertStatusType value) {
        return new JAXBElement<RequestChangeAlertStatusType>(_RequestChangeAlertStatus_QNAME, RequestChangeAlertStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_create_aj")
    public JAXBElement<FaultType> createFaultCreateAj(FaultType value) {
        return new JAXBElement<FaultType>(_FaultCreateAj_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseChangeAlertStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_change_alert_status")
    public JAXBElement<ResponseChangeAlertStatusType> createResponseChangeAlertStatus(ResponseChangeAlertStatusType value) {
        return new JAXBElement<ResponseChangeAlertStatusType>(_ResponseChangeAlertStatus_QNAME, ResponseChangeAlertStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_def_delete_folder")
    public JAXBElement<FaultType> createFaultPollDefDeleteFolder(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollDefDeleteFolder_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_aj_hold")
    public JAXBElement<FaultType> createFaultPollAjHold(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAjHold_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseDefCreateFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_def_create_folder")
    public JAXBElement<ResponseDefCreateFolderType> createResponseDefCreateFolder(ResponseDefCreateFolderType value) {
        return new JAXBElement<ResponseDefCreateFolderType>(_ResponseDefCreateFolder_QNAME, ResponseDefCreateFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_aj_set_to_ok")
    public JAXBElement<RequestPollType> createRequestPollAjSetToOk(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAjSetToOk_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_create_aj")
    public JAXBElement<RequestPollType> createRequestPollCreateAj(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollCreateAj_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestOrderForceJobType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_order_force")
    public JAXBElement<RequestOrderForceJobType> createRequestOrderForce(RequestOrderForceJobType value) {
        return new JAXBElement<RequestOrderForceJobType>(_RequestOrderForce_QNAME, RequestOrderForceJobType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_upload_folder")
    public JAXBElement<FaultType> createFaultDefUploadFolder(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefUploadFolder_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_aj_hold")
    public JAXBElement<ResponsePollGenActionType> createResponsePollAjHold(ResponsePollGenActionType value) {
        return new JAXBElement<ResponsePollGenActionType>(_ResponsePollAjHold_QNAME, ResponsePollGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_aj_rerun")
    public JAXBElement<RequestPollType> createRequestPollAjRerun(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAjRerun_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_delete_condition")
    public JAXBElement<SimpleTokenResponseType> createResponseDeleteCondition(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseDeleteCondition_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_add_condition")
    public JAXBElement<RequestPollType> createRequestPollAddCondition(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAddCondition_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_create_folder")
    public JAXBElement<FaultType> createFaultDefCreateFolder(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefCreateFolder_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_aj_free")
    public JAXBElement<RequestPollType> createRequestPollAjFree(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAjFree_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDefAddFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_def_add_folder")
    public JAXBElement<RequestDefAddFolderType> createRequestDefAddFolder(RequestDefAddFolderType value) {
        return new JAXBElement<RequestDefAddFolderType>(_RequestDefAddFolder_QNAME, RequestDefAddFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDefUploadFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_def_upload_folder")
    public JAXBElement<RequestDefUploadFolderType> createRequestDefUploadFolder(RequestDefUploadFolderType value) {
        return new JAXBElement<RequestDefUploadFolderType>(_RequestDefUploadFolder_QNAME, RequestDefUploadFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollAddDeleteConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_add_delete_condition")
    public JAXBElement<ResponsePollAddDeleteConditionType> createResponsePollAddDeleteCondition(ResponsePollAddDeleteConditionType value) {
        return new JAXBElement<ResponsePollAddDeleteConditionType>(_ResponsePollAddDeleteCondition_QNAME, ResponsePollAddDeleteConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_aj_set_to_ok")
    public JAXBElement<FaultType> createFaultPollAjSetToOk(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAjSetToOk_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseListConditionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_list_conditions")
    public JAXBElement<ResponseListConditionsType> createResponseListConditions(ResponseListConditionsType value) {
        return new JAXBElement<ResponseListConditionsType>(_ResponseListConditions_QNAME, ResponseListConditionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDefCreateFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_def_create_folder")
    public JAXBElement<RequestDefCreateFolderType> createRequestDefCreateFolder(RequestDefCreateFolderType value) {
        return new JAXBElement<RequestDefCreateFolderType>(_RequestDefCreateFolder_QNAME, RequestDefCreateFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_aj_free")
    public JAXBElement<FaultType> createFaultPollAjFree(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAjFree_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_add_condition")
    public JAXBElement<FaultType> createFaultAddCondition(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAddCondition_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDefDeleteJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_def_delete_jobs")
    public JAXBElement<RequestDefDeleteJobsType> createRequestDefDeleteJobs(RequestDefDeleteJobsType value) {
        return new JAXBElement<RequestDefDeleteJobsType>(_RequestDefDeleteJobs_QNAME, RequestDefDeleteJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseActRetrieveJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_act_retrieve_jobs")
    public JAXBElement<ResponseActRetrieveJobsType> createResponseActRetrieveJobs(ResponseActRetrieveJobsType value) {
        return new JAXBElement<ResponseActRetrieveJobsType>(_ResponseActRetrieveJobs_QNAME, ResponseActRetrieveJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestCheckUserTokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_check_user_token")
    public JAXBElement<RequestCheckUserTokenType> createRequestCheckUserToken(RequestCheckUserTokenType value) {
        return new JAXBElement<RequestCheckUserTokenType>(_RequestCheckUserToken_QNAME, RequestCheckUserTokenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollAddDeleteConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_add_condition")
    public JAXBElement<ResponsePollAddDeleteConditionType> createResponsePollAddCondition(ResponsePollAddDeleteConditionType value) {
        return new JAXBElement<ResponsePollAddDeleteConditionType>(_ResponsePollAddCondition_QNAME, ResponsePollAddDeleteConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_aj_confirm")
    public JAXBElement<RequestGenActionType> createRequestAjConfirm(RequestGenActionType value) {
        return new JAXBElement<RequestGenActionType>(_RequestAjConfirm_QNAME, RequestGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_aj_rerun")
    public JAXBElement<SimpleTokenResponseType> createResponseAjRerun(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAjRerun_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGetBimServicesInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_bim_services_info")
    public JAXBElement<RequestGetBimServicesInfoType> createRequestBimServicesInfo(RequestGetBimServicesInfoType value) {
        return new JAXBElement<RequestGetBimServicesInfoType>(_RequestBimServicesInfo_QNAME, RequestGetBimServicesInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_aj_hold")
    public JAXBElement<RequestGenActionType> createRequestAjHold(RequestGenActionType value) {
        return new JAXBElement<RequestGenActionType>(_RequestAjHold_QNAME, RequestGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_aj_kill")
    public JAXBElement<FaultType> createFaultPollAjKill(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAjKill_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_def_delete_folder")
    public JAXBElement<SimpleTokenResponseType> createResponseDefDeleteFolder(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseDefDeleteFolder_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_aj_rerun")
    public JAXBElement<FaultType> createFaultPollAjRerun(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAjRerun_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_delete_condition")
    public JAXBElement<FaultType> createFaultDeleteCondition(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDeleteCondition_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_aj_free")
    public JAXBElement<SimpleTokenResponseType> createResponseAjFree(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAjFree_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDefAddJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_def_add_jobs")
    public JAXBElement<RequestDefAddJobsType> createRequestDefAddJobs(RequestDefAddJobsType value) {
        return new JAXBElement<RequestDefAddJobsType>(_RequestDefAddJobs_QNAME, RequestDefAddJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_aj_hold")
    public JAXBElement<FaultType> createFaultAjHold(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAjHold_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_aj_confirm")
    public JAXBElement<FaultType> createFaultAjConfirm(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAjConfirm_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_get_bim_services_info")
    public JAXBElement<FaultType> createFaultGetBimServicesInfo(FaultType value) {
        return new JAXBElement<FaultType>(_FaultGetBimServicesInfo_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_register")
    public JAXBElement<FaultType> createFaultRegister(FaultType value) {
        return new JAXBElement<FaultType>(_FaultRegister_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_aj_kill")
    public JAXBElement<RequestGenActionType> createRequestAjKill(RequestGenActionType value) {
        return new JAXBElement<RequestGenActionType>(_RequestAjKill_QNAME, RequestGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestListConditionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_list_conditions")
    public JAXBElement<RequestListConditionsType> createRequestListConditions(RequestListConditionsType value) {
        return new JAXBElement<RequestListConditionsType>(_RequestListConditions_QNAME, RequestListConditionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_aj_free")
    public JAXBElement<ResponsePollGenActionType> createResponsePollAjFree(ResponsePollGenActionType value) {
        return new JAXBElement<ResponsePollGenActionType>(_ResponsePollAjFree_QNAME, ResponsePollGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_aj_confirm")
    public JAXBElement<FaultType> createFaultPollAjConfirm(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAjConfirm_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestClientKeepAliveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_client_keep_alive")
    public JAXBElement<RequestClientKeepAliveType> createRequestClientKeepAlive(RequestClientKeepAliveType value) {
        return new JAXBElement<RequestClientKeepAliveType>(_RequestClientKeepAlive_QNAME, RequestClientKeepAliveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_add_delete_condition")
    public JAXBElement<FaultType> createFaultPollAddDeleteCondition(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAddDeleteCondition_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_aj_confirm")
    public JAXBElement<RequestPollType> createRequestPollAjConfirm(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollAjConfirm_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDefDeleteFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_def_delete_folder")
    public JAXBElement<RequestDefDeleteFolderType> createRequestDefDeleteFolder(RequestDefDeleteFolderType value) {
        return new JAXBElement<RequestDefDeleteFolderType>(_RequestDefDeleteFolder_QNAME, RequestDefDeleteFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseCreateJobType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_create_aj")
    public JAXBElement<ResponseCreateJobType> createResponsePollCreateAj(ResponseCreateJobType value) {
        return new JAXBElement<ResponseCreateJobType>(_ResponsePollCreateAj_QNAME, ResponseCreateJobType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll_delete_condition")
    public JAXBElement<RequestPollType> createRequestPollDeleteCondition(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPollDeleteCondition_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseJobTrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_job_track")
    public JAXBElement<ResponseJobTrackType> createResponseJobTrack(ResponseJobTrackType value) {
        return new JAXBElement<ResponseJobTrackType>(_ResponseJobTrack_QNAME, ResponseJobTrackType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_create_aj")
    public JAXBElement<FaultType> createFaultPollCreateAj(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollCreateAj_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_aj_kill")
    public JAXBElement<FaultType> createFaultAjKill(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAjKill_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultPollOrderForceWithJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_order_force")
    public JAXBElement<FaultPollOrderForceWithJobsType> createFaultPollOrderForce(FaultPollOrderForceWithJobsType value) {
        return new JAXBElement<FaultPollOrderForceWithJobsType>(_FaultPollOrderForce_QNAME, FaultPollOrderForceWithJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestPollType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_poll")
    public JAXBElement<RequestPollType> createRequestPoll(RequestPollType value) {
        return new JAXBElement<RequestPollType>(_RequestPoll_QNAME, RequestPollType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_aj_free")
    public JAXBElement<RequestGenActionType> createRequestAjFree(RequestGenActionType value) {
        return new JAXBElement<RequestGenActionType>(_RequestAjFree_QNAME, RequestGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestUserRegistrationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_register")
    public JAXBElement<RequestUserRegistrationType> createRequestRegister(RequestUserRegistrationType value) {
        return new JAXBElement<RequestUserRegistrationType>(_RequestRegister_QNAME, RequestUserRegistrationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_order_force")
    public JAXBElement<SimpleTokenResponseType> createResponseOrderForce(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseOrderForce_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_aj_kill")
    public JAXBElement<SimpleTokenResponseType> createResponseAjKill(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAjKill_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseUserRegistrationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_register")
    public JAXBElement<ResponseUserRegistrationType> createResponseRegister(ResponseUserRegistrationType value) {
        return new JAXBElement<ResponseUserRegistrationType>(_ResponseRegister_QNAME, ResponseUserRegistrationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_client_keep_alive")
    public JAXBElement<FaultType> createFaultClientKeepAlive(FaultType value) {
        return new JAXBElement<FaultType>(_FaultClientKeepAlive_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_unregister")
    public JAXBElement<FaultType> createFaultUnregister(FaultType value) {
        return new JAXBElement<FaultType>(_FaultUnregister_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_def_delete_jobs")
    public JAXBElement<FaultType> createFaultDefDeleteJobs(FaultType value) {
        return new JAXBElement<FaultType>(_FaultDefDeleteJobs_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_aj_rerun")
    public JAXBElement<ResponsePollGenActionType> createResponsePollAjRerun(ResponsePollGenActionType value) {
        return new JAXBElement<ResponsePollGenActionType>(_ResponsePollAjRerun_QNAME, ResponsePollGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseDefAddFolderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_def_add_folder")
    public JAXBElement<ResponseDefAddFolderType> createResponseDefAddFolder(ResponseDefAddFolderType value) {
        return new JAXBElement<ResponseDefAddFolderType>(_ResponseDefAddFolder_QNAME, ResponseDefAddFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_aj_set_to_ok")
    public JAXBElement<ResponsePollGenActionType> createResponsePollAjSetToOk(ResponsePollGenActionType value) {
        return new JAXBElement<ResponsePollGenActionType>(_ResponsePollAjSetToOk_QNAME, ResponsePollGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_aj_hold")
    public JAXBElement<SimpleTokenResponseType> createResponseAjHold(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAjHold_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestActRetrieveJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_act_retrieve_jobs")
    public JAXBElement<RequestActRetrieveJobsType> createRequestActRetrieveJobs(RequestActRetrieveJobsType value) {
        return new JAXBElement<RequestActRetrieveJobsType>(_RequestActRetrieveJobs_QNAME, RequestActRetrieveJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponsePollGenActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_poll_aj_confirm")
    public JAXBElement<ResponsePollGenActionType> createResponsePollAjConfirm(ResponsePollGenActionType value) {
        return new JAXBElement<ResponsePollGenActionType>(_ResponsePollAjConfirm_QNAME, ResponsePollGenActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestUserUnregistrationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "request_unregister")
    public JAXBElement<RequestUserUnregistrationType> createRequestUnregister(RequestUserUnregistrationType value) {
        return new JAXBElement<RequestUserUnregistrationType>(_RequestUnregister_QNAME, RequestUserUnregistrationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_def_upload_folder")
    public JAXBElement<SimpleTokenResponseType> createResponseDefUploadFolder(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseDefUploadFolder_QNAME, SimpleTokenResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseDefAddJobsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_def_add_jobs")
    public JAXBElement<ResponseDefAddJobsType> createResponseDefAddJobs(ResponseDefAddJobsType value) {
        return new JAXBElement<ResponseDefAddJobsType>(_ResponseDefAddJobs_QNAME, ResponseDefAddJobsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_aj_rerun")
    public JAXBElement<FaultType> createFaultAjRerun(FaultType value) {
        return new JAXBElement<FaultType>(_FaultAjRerun_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "fault_poll_add_condition")
    public JAXBElement<FaultType> createFaultPollAddCondition(FaultType value) {
        return new JAXBElement<FaultType>(_FaultPollAddCondition_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleTokenResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bmc.com/ctmem/schema900", name = "response_aj_confirm")
    public JAXBElement<SimpleTokenResponseType> createResponseAjConfirm(SimpleTokenResponseType value) {
        return new JAXBElement<SimpleTokenResponseType>(_ResponseAjConfirm_QNAME, SimpleTokenResponseType.class, null, value);
    }

}
