//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for on_do_statements_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="on_do_statements_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="on_do_statement" type="{http://www.bmc.com/ctmem/schema900}on_do_statement_type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "on_do_statements_type", propOrder = {
    "onDoStatement"
})
public class OnDoStatementsType {

    @XmlElement(name = "on_do_statement", required = true)
    protected List<OnDoStatementType> onDoStatement;

    /**
     * Gets the value of the onDoStatement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onDoStatement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnDoStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnDoStatementType }
     * 
     * 
     */
    public List<OnDoStatementType> getOnDoStatement() {
        if (onDoStatement == null) {
            onDoStatement = new ArrayList<OnDoStatementType>();
        }
        return this.onDoStatement;
    }

	public void setOnDoStatement(List<OnDoStatementType> onDoStatement) {
		this.onDoStatement = onDoStatement;
	}

}
