//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for on_statement_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="on_statement_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="program_step" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="procedure_step" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="and_or" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "on_statement_type", propOrder = {
    "code",
    "statement",
    "programStep",
    "procedureStep",
    "andOr"
})
public class OnStatementType {

    @XmlElement(required = true)
    protected String code;
    protected String statement;
    @XmlElement(name = "program_step")
    protected String programStep;
    @XmlElement(name = "procedure_step")
    protected String procedureStep;
    @XmlElement(name = "and_or")
    protected String andOr;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the statement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatement() {
        return statement;
    }

    /**
     * Sets the value of the statement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatement(String value) {
        this.statement = value;
    }

    /**
     * Gets the value of the programStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramStep() {
        return programStep;
    }

    /**
     * Sets the value of the programStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramStep(String value) {
        this.programStep = value;
    }

    /**
     * Gets the value of the procedureStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureStep() {
        return procedureStep;
    }

    /**
     * Sets the value of the procedureStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureStep(String value) {
        this.procedureStep = value;
    }

    /**
     * Gets the value of the andOr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAndOr() {
        return andOr;
    }

    /**
     * Sets the value of the andOr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndOr(String value) {
        this.andOr = value;
    }

}
