//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for on_statement_output_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="on_statement_output_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="find_output_pattern" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="find_pattern_from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="find_pattern_to" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="and_or" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "on_statement_output_type", propOrder = {
    "findOutputPattern",
    "findPatternFrom",
    "findPatternTo",
    "andOr"
})
public class OnStatementOutputType {

    @XmlElement(name = "find_output_pattern")
    protected String findOutputPattern;
    @XmlElement(name = "find_pattern_from")
    protected String findPatternFrom;
    @XmlElement(name = "find_pattern_to")
    protected String findPatternTo;
    @XmlElement(name = "and_or")
    protected String andOr;

    /**
     * Gets the value of the findOutputPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFindOutputPattern() {
        return findOutputPattern;
    }

    /**
     * Sets the value of the findOutputPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFindOutputPattern(String value) {
        this.findOutputPattern = value;
    }

    /**
     * Gets the value of the findPatternFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFindPatternFrom() {
        return findPatternFrom;
    }

    /**
     * Sets the value of the findPatternFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFindPatternFrom(String value) {
        this.findPatternFrom = value;
    }

    /**
     * Gets the value of the findPatternTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFindPatternTo() {
        return findPatternTo;
    }

    /**
     * Sets the value of the findPatternTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFindPatternTo(String value) {
        this.findPatternTo = value;
    }

    /**
     * Gets the value of the andOr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAndOr() {
        return andOr;
    }

    /**
     * Sets the value of the andOr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndOr(String value) {
        this.andOr = value;
    }

}
