//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for on_statements_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="on_statements_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="on_statement" type="{http://www.bmc.com/ctmem/schema900}on_statement_type" maxOccurs="unbounded"/>
 *         &lt;element name="on_statement_output" type="{http://www.bmc.com/ctmem/schema900}on_statement_output_type" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "on_statements_type", propOrder = {
    "onStatement",
    "onStatementOutput"
})
public class OnStatementsType {

    @XmlElement(name = "on_statement")
    protected List<OnStatementType> onStatement;
    @XmlElement(name = "on_statement_output")
    protected List<OnStatementOutputType> onStatementOutput;

    /**
     * Gets the value of the onStatement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onStatement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnStatementType }
     * 
     * 
     */
    public List<OnStatementType> getOnStatement() {
        if (onStatement == null) {
            onStatement = new ArrayList<OnStatementType>();
        }
        return this.onStatement;
    }
    
    public void setOnStatement(List<OnStatementType> onStatement) {
        this.onStatement = onStatement;
    }

    /**
     * Gets the value of the onStatementOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onStatementOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnStatementOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnStatementOutputType }
     * 
     * 
     */
    public List<OnStatementOutputType> getOnStatementOutput() {
        if (onStatementOutput == null) {
            onStatementOutput = new ArrayList<OnStatementOutputType>();
        }
        return this.onStatementOutput;
    }
    
    public void setOnStatementOutput(List<OnStatementOutputType> onStatementOutput) {
        this.onStatementOutput = onStatementOutput;
    }

}
