//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request_act_retrieve_jobs_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="request_act_retrieve_jobs_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="max_returned_nodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retrieve_jobs_criterion" type="{http://www.bmc.com/ctmem/schema900}criterion_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request_act_retrieve_jobs_type", propOrder = {
    "userToken",
    "maxReturnedNodes",
    "retrieveJobsCriterion"
})

@XmlRootElement(name = "request_act_retrieve_jobs", namespace = "http://www.bmc.com/ctmem/schema900")
public class RequestActRetrieveJobsType {

    @XmlElement(name = "user_token", required = true)
    protected String userToken;
    @XmlElement(name = "max_returned_nodes")
    protected String maxReturnedNodes;
    @XmlElement(name = "retrieve_jobs_criterion", required = true)
    protected CriterionType retrieveJobsCriterion;

    /**
     * Gets the value of the userToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * Sets the value of the userToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserToken(String value) {
        this.userToken = value;
    }

    /**
     * Gets the value of the maxReturnedNodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxReturnedNodes() {
        return maxReturnedNodes;
    }

    /**
     * Sets the value of the maxReturnedNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxReturnedNodes(String value) {
        this.maxReturnedNodes = value;
    }

    /**
     * Gets the value of the retrieveJobsCriterion property.
     * 
     * @return
     *     possible object is
     *     {@link CriterionType }
     *     
     */
    public CriterionType getRetrieveJobsCriterion() {
        return retrieveJobsCriterion;
    }

    /**
     * Sets the value of the retrieveJobsCriterion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriterionType }
     *     
     */
    public void setRetrieveJobsCriterion(CriterionType value) {
        this.retrieveJobsCriterion = value;
    }

}
