//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request_order_force_job_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="request_order_force_job_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user_token" type="{http://www.bmc.com/ctmem/schema900}user_token_type"/>
 *         &lt;element name="force_it" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="control_m" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="job_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="folder_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="folder_library" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="odate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wait_for_odate" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="with_hold" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="variable_assignments" type="{http://www.bmc.com/ctmem/schema900}variable_assignments_type" minOccurs="0"/>
 *         &lt;element name="folder_info" type="{http://www.bmc.com/ctmem/schema900}folder_info_type" minOccurs="0"/>
 *         &lt;element name="max_returned_nodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unique_flow" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request_order_force_job_type", propOrder = {
    "userToken",
    "forceIt",
    "controlM",
    "jobId",
    "jobName",
    "folderName",
    "folderLibrary",
    "odate",
    "waitForOdate",
    "withHold",
    "variableAssignments",
    "folderInfo",
    "maxReturnedNodes",
    "uniqueFlow"
})

@XmlRootElement(name = "request_order_force", namespace = "http://www.bmc.com/ctmem/schema900")
public class RequestOrderForceJobType {

    @XmlElement(name = "user_token", required = true)
    protected String userToken;
    @XmlElement(name = "force_it", required = true)
    protected String forceIt;
    @XmlElement(name = "control_m", required = true)
    protected String controlM;
    @XmlElement(name = "job_id")
    protected String jobId;
    @XmlElement(name = "job_name")
    protected String jobName;
    @XmlElement(name = "folder_name", required = true)
    protected String folderName;
    @XmlElement(name = "folder_library")
    protected String folderLibrary;
    @XmlElement(required = true)
    protected String odate;
    @XmlElement(name = "wait_for_odate")
    protected YesNoType waitForOdate;
    @XmlElement(name = "with_hold")
    protected String withHold;
    @XmlElement(name = "variable_assignments")
    protected VariableAssignmentsType variableAssignments;
    @XmlElement(name = "folder_info")
    protected FolderInfoType folderInfo;
    @XmlElement(name = "max_returned_nodes")
    protected String maxReturnedNodes;
    @XmlElement(name = "unique_flow")
    protected YesNoType uniqueFlow;

    /**
     * Gets the value of the userToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * Sets the value of the userToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserToken(String value) {
        this.userToken = value;
    }

    /**
     * Gets the value of the forceIt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForceIt() {
        return forceIt;
    }

    /**
     * Sets the value of the forceIt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForceIt(String value) {
        this.forceIt = value;
    }

    /**
     * Gets the value of the controlM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlM() {
        return controlM;
    }

    /**
     * Sets the value of the controlM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlM(String value) {
        this.controlM = value;
    }

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobId(String value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the folderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * Sets the value of the folderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderName(String value) {
        this.folderName = value;
    }

    /**
     * Gets the value of the folderLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderLibrary() {
        return folderLibrary;
    }

    /**
     * Sets the value of the folderLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderLibrary(String value) {
        this.folderLibrary = value;
    }

    /**
     * Gets the value of the odate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdate() {
        return odate;
    }

    /**
     * Sets the value of the odate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdate(String value) {
        this.odate = value;
    }

    /**
     * Gets the value of the waitForOdate property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getWaitForOdate() {
        return waitForOdate;
    }

    /**
     * Sets the value of the waitForOdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setWaitForOdate(YesNoType value) {
        this.waitForOdate = value;
    }

    /**
     * Gets the value of the withHold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithHold() {
        return withHold;
    }

    /**
     * Sets the value of the withHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithHold(String value) {
        this.withHold = value;
    }

    /**
     * Gets the value of the variableAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link VariableAssignmentsType }
     *     
     */
    public VariableAssignmentsType getVariableAssignments() {
        return variableAssignments;
    }

    /**
     * Sets the value of the variableAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableAssignmentsType }
     *     
     */
    public void setVariableAssignments(VariableAssignmentsType value) {
        this.variableAssignments = value;
    }

    /**
     * Gets the value of the folderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FolderInfoType }
     *     
     */
    public FolderInfoType getFolderInfo() {
        return folderInfo;
    }

    /**
     * Sets the value of the folderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FolderInfoType }
     *     
     */
    public void setFolderInfo(FolderInfoType value) {
        this.folderInfo = value;
    }

    /**
     * Gets the value of the maxReturnedNodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxReturnedNodes() {
        return maxReturnedNodes;
    }

    /**
     * Sets the value of the maxReturnedNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxReturnedNodes(String value) {
        this.maxReturnedNodes = value;
    }

    /**
     * Gets the value of the uniqueFlow property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getUniqueFlow() {
        return uniqueFlow;
    }

    /**
     * Sets the value of the uniqueFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setUniqueFlow(YesNoType value) {
        this.uniqueFlow = value;
    }

}
