//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request_create_job_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="request_create_job_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user_token" type="{http://www.bmc.com/ctmem/schema900}user_token_type"/>
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="control_m" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="active_job" type="{http://www.bmc.com/ctmem/schema900}active_job_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "request_create_job_type", propOrder = {
    "userToken",
    "mode",
    "controlM",
    "activeJob"
})

@XmlRootElement(name = "request_create_aj", namespace = "http://www.bmc.com/ctmem/schema900")
public class RequestCreateJobType {

    @XmlElement(name = "user_token", required = true)
    protected String userToken;
    protected String mode;
    @XmlElement(name = "control_m", required = true)
    protected String controlM;
    @XmlElement(name = "active_job", required = true)
    protected ActiveJobType activeJob;

    /**
     * Gets the value of the userToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * Sets the value of the userToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserToken(String value) {
        this.userToken = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the controlM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlM() {
        return controlM;
    }

    /**
     * Sets the value of the controlM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlM(String value) {
        this.controlM = value;
    }

    /**
     * Gets the value of the activeJob property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveJobType }
     *     
     */
    public ActiveJobType getActiveJob() {
        return activeJob;
    }

    /**
     * Sets the value of the activeJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveJobType }
     *     
     */
    public void setActiveJob(ActiveJobType value) {
        this.activeJob = value;
    }

}
