//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response_job_data_act_retrieve_jobs_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_job_data_act_retrieve_jobs_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="control_m" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rba" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="folder_rba" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="application_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sub_application" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mem_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mem_lib" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order_folder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order_library" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="run_as" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="task_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="in_BIM_service" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state_digits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="otime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="next_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rerun_counter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="average_runtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="critical" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cyclic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emergency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_until" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_job_data_act_retrieve_jobs_type", propOrder = {
    "controlM",
    "orderId",
    "rba",
    "folderRba",
    "application",
    "applicationType",
    "subApplication",
    "jobName",
    "memName",
    "memLib",
    "orderFolder",
    "orderLibrary",
    "runAs",
    "description",
    "taskType",
    "timeZone",
    "inBIMService",
    "jobStatus",
    "jobState",
    "stateDigits",
    "odate",
    "otime",
    "nextTime",
    "rerunCounter",
    "averageRuntime",
    "startTime",
    "endTime",
    "critical",
    "cyclic",
    "emergency",
    "timeFrom",
    "timeUntil"
})

@XmlRootElement(name = "response_job_data_act_retrieve_jobs", namespace = "http://www.bmc.com/ctmem/schema900")
public class ResponseJobDataActRetrieveJobsType {

    @XmlElement(name = "control_m", required = true)
    protected String controlM;
    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(required = true)
    protected String rba;
    @XmlElement(name = "folder_rba", required = true)
    protected String folderRba;
    @XmlElement(required = true)
    protected String application;
    @XmlElement(name = "application_type", required = true)
    protected String applicationType;
    @XmlElement(name = "sub_application", required = true)
    protected String subApplication;
    @XmlElement(name = "job_name", required = true)
    protected String jobName;
    @XmlElement(name = "mem_name", required = true)
    protected String memName;
    @XmlElement(name = "mem_lib", required = true)
    protected String memLib;
    @XmlElement(name = "order_folder", required = true)
    protected String orderFolder;
    @XmlElement(name = "order_library")
    protected String orderLibrary;
    @XmlElement(name = "run_as", required = true)
    protected String runAs;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "task_type", required = true)
    protected String taskType;
    @XmlElement(name = "time_zone", required = true)
    protected String timeZone;
    @XmlElement(name = "in_BIM_service", required = true)
    protected String inBIMService;
    @XmlElement(name = "job_status", required = true)
    protected String jobStatus;
    @XmlElement(name = "job_state", required = true)
    protected String jobState;
    @XmlElement(name = "state_digits", required = true)
    protected String stateDigits;
    @XmlElement(required = true)
    protected String odate;
    @XmlElement(required = true)
    protected String otime;
    @XmlElement(name = "next_time", required = true)
    protected String nextTime;
    @XmlElement(name = "rerun_counter", required = true)
    protected String rerunCounter;
    @XmlElement(name = "average_runtime", required = true)
    protected String averageRuntime;
    @XmlElement(name = "start_time", required = true)
    protected String startTime;
    @XmlElement(name = "end_time", required = true)
    protected String endTime;
    @XmlElement(required = true)
    protected String critical;
    @XmlElement(required = true)
    protected String cyclic;
    @XmlElement(required = true)
    protected String emergency;
    @XmlElement(name = "time_from", required = true)
    protected String timeFrom;
    @XmlElement(name = "time_until", required = true)
    protected String timeUntil;

    /**
     * Gets the value of the controlM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlM() {
        return controlM;
    }

    /**
     * Sets the value of the controlM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlM(String value) {
        this.controlM = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the rba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRba() {
        return rba;
    }

    /**
     * Sets the value of the rba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRba(String value) {
        this.rba = value;
    }

    /**
     * Gets the value of the folderRba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderRba() {
        return folderRba;
    }

    /**
     * Sets the value of the folderRba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderRba(String value) {
        this.folderRba = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the applicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * Sets the value of the applicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationType(String value) {
        this.applicationType = value;
    }

    /**
     * Gets the value of the subApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubApplication() {
        return subApplication;
    }

    /**
     * Sets the value of the subApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubApplication(String value) {
        this.subApplication = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the memName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemName() {
        return memName;
    }

    /**
     * Sets the value of the memName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemName(String value) {
        this.memName = value;
    }

    /**
     * Gets the value of the memLib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemLib() {
        return memLib;
    }

    /**
     * Sets the value of the memLib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemLib(String value) {
        this.memLib = value;
    }

    /**
     * Gets the value of the orderFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderFolder() {
        return orderFolder;
    }

    /**
     * Sets the value of the orderFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderFolder(String value) {
        this.orderFolder = value;
    }

    /**
     * Gets the value of the orderLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLibrary() {
        return orderLibrary;
    }

    /**
     * Sets the value of the orderLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLibrary(String value) {
        this.orderLibrary = value;
    }

    /**
     * Gets the value of the runAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunAs() {
        return runAs;
    }

    /**
     * Sets the value of the runAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunAs(String value) {
        this.runAs = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the taskType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * Sets the value of the taskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskType(String value) {
        this.taskType = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the inBIMService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBIMService() {
        return inBIMService;
    }

    /**
     * Sets the value of the inBIMService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBIMService(String value) {
        this.inBIMService = value;
    }

    /**
     * Gets the value of the jobStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * Sets the value of the jobStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobStatus(String value) {
        this.jobStatus = value;
    }

    /**
     * Gets the value of the jobState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobState() {
        return jobState;
    }

    /**
     * Sets the value of the jobState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobState(String value) {
        this.jobState = value;
    }

    /**
     * Gets the value of the stateDigits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateDigits() {
        return stateDigits;
    }

    /**
     * Sets the value of the stateDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateDigits(String value) {
        this.stateDigits = value;
    }

    /**
     * Gets the value of the odate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdate() {
        return odate;
    }

    /**
     * Sets the value of the odate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdate(String value) {
        this.odate = value;
    }

    /**
     * Gets the value of the otime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtime() {
        return otime;
    }

    /**
     * Sets the value of the otime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtime(String value) {
        this.otime = value;
    }

    /**
     * Gets the value of the nextTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextTime() {
        return nextTime;
    }

    /**
     * Sets the value of the nextTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextTime(String value) {
        this.nextTime = value;
    }

    /**
     * Gets the value of the rerunCounter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerunCounter() {
        return rerunCounter;
    }

    /**
     * Sets the value of the rerunCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerunCounter(String value) {
        this.rerunCounter = value;
    }

    /**
     * Gets the value of the averageRuntime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAverageRuntime() {
        return averageRuntime;
    }

    /**
     * Sets the value of the averageRuntime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAverageRuntime(String value) {
        this.averageRuntime = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCritical(String value) {
        this.critical = value;
    }

    /**
     * Gets the value of the cyclic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyclic() {
        return cyclic;
    }

    /**
     * Sets the value of the cyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyclic(String value) {
        this.cyclic = value;
    }

    /**
     * Gets the value of the emergency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmergency() {
        return emergency;
    }

    /**
     * Sets the value of the emergency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmergency(String value) {
        this.emergency = value;
    }

    /**
     * Gets the value of the timeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeFrom() {
        return timeFrom;
    }

    /**
     * Sets the value of the timeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeFrom(String value) {
        this.timeFrom = value;
    }

    /**
     * Gets the value of the timeUntil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeUntil() {
        return timeUntil;
    }

    /**
     * Sets the value of the timeUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeUntil(String value) {
        this.timeUntil = value;
    }

}
