//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response_data_jobs_job_data_order_force_job_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_data_jobs_job_data_order_force_job_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rba" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mem_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="job_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="is_folder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ret_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_data_jobs_job_data_order_force_job_type", propOrder = {
    "rba",
    "orderId",
    "memName",
    "jobName",
    "isFolder",
    "retText"
})

@XmlRootElement(name = "response_data_jobs_job_data_order_force_job", namespace = "http://www.bmc.com/ctmem/schema900")
public class ResponseDataJobsJobDataOrderForceJobType {

    protected String rba;
    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(name = "mem_name")
    protected String memName;
    @XmlElement(name = "job_name")
    protected String jobName;
    @XmlElement(name = "is_folder")
    protected String isFolder;
    @XmlElement(name = "ret_text")
    protected String retText;

    /**
     * Gets the value of the rba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRba() {
        return rba;
    }

    /**
     * Sets the value of the rba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRba(String value) {
        this.rba = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the memName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemName() {
        return memName;
    }

    /**
     * Sets the value of the memName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemName(String value) {
        this.memName = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the isFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFolder() {
        return isFolder;
    }

    /**
     * Sets the value of the isFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFolder(String value) {
        this.isFolder = value;
    }

    /**
     * Gets the value of the retText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetText() {
        return retText;
    }

    /**
     * Sets the value of the retText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetText(String value) {
        this.retText = value;
    }

}
