//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response_act_retrieve_jobs_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_act_retrieve_jobs_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="retrieved_nodes_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jobs" type="{http://www.bmc.com/ctmem/schema900}response_jobs_act_retrieve_jobs_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_act_retrieve_jobs_type", propOrder = {
    "retrievedNodesNumber",
    "jobs"
})

@XmlRootElement(name = "response_act_retrieve_jobs", namespace = "http://www.bmc.com/ctmem/schema900")
public class ResponseActRetrieveJobsType {

    @XmlElement(name = "retrieved_nodes_number", required = true)
    protected String retrievedNodesNumber;
    @XmlElement(required = true)
    protected ResponseJobsActRetrieveJobsType jobs;

    /**
     * Gets the value of the retrievedNodesNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievedNodesNumber() {
        return retrievedNodesNumber;
    }

    /**
     * Sets the value of the retrievedNodesNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievedNodesNumber(String value) {
        this.retrievedNodesNumber = value;
    }

    /**
     * Gets the value of the jobs property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseJobsActRetrieveJobsType }
     *     
     */
    public ResponseJobsActRetrieveJobsType getJobs() {
        return jobs;
    }

    /**
     * Sets the value of the jobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseJobsActRetrieveJobsType }
     *     
     */
    public void setJobs(ResponseJobsActRetrieveJobsType value) {
        this.jobs = value;
    }

}
