//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response_job_act_retrieve_jobs_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_job_act_retrieve_jobs_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="job_data" type="{http://www.bmc.com/ctmem/schema900}response_job_data_act_retrieve_jobs_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_job_act_retrieve_jobs_type", propOrder = {
    "jobData"
})

@XmlRootElement(name = "response_job_act_retrieve_jobs", namespace = "http://www.bmc.com/ctmem/schema900")
public class ResponseJobActRetrieveJobsType {

    @XmlElement(name = "job_data", required = true)
    protected ResponseJobDataActRetrieveJobsType jobData;

    /**
     * Gets the value of the jobData property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseJobDataActRetrieveJobsType }
     *     
     */
    public ResponseJobDataActRetrieveJobsType getJobData() {
        return jobData;
    }

    /**
     * Sets the value of the jobData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseJobDataActRetrieveJobsType }
     *     
     */
    public void setJobData(ResponseJobDataActRetrieveJobsType value) {
        this.jobData = value;
    }

}
