//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response_jobs_job_job_data_job_track_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_jobs_job_job_data_job_track_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="control_m" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state_digits" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="odate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_jobs_job_job_data_job_track_type", propOrder = {
    "controlM",
    "orderId",
    "jobStatus",
    "stateDigits",
    "odate"
})

@XmlRootElement(name = "response_jobs_job_job_data_job_track", namespace = "http://www.bmc.com/ctmem/schema900")
public class ResponseJobsJobJobDataJobTrackType {

    @XmlElement(name = "control_m", required = true)
    protected String controlM;
    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(name = "job_status")
    protected String jobStatus;
    @XmlElement(name = "state_digits")
    protected String stateDigits;
    protected String odate;

    /**
     * Gets the value of the controlM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlM() {
        return controlM;
    }

    /**
     * Sets the value of the controlM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlM(String value) {
        this.controlM = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the jobStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * Sets the value of the jobStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobStatus(String value) {
        this.jobStatus = value;
    }

    /**
     * Gets the value of the stateDigits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateDigits() {
        return stateDigits;
    }

    /**
     * Sets the value of the stateDigits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateDigits(String value) {
        this.stateDigits = value;
    }

    /**
     * Gets the value of the odate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdate() {
        return odate;
    }

    /**
     * Sets the value of the odate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdate(String value) {
        this.odate = value;
    }

}
