//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rule_based_cal_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rule_based_cal_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rule_based_cal_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max_wait" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="and_or" type="{http://www.bmc.com/ctmem/schema900}and_or_type" minOccurs="0"/>
 *         &lt;element name="days_cal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="weeks_cal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="conf_cal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="retro" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="shift" type="{http://www.bmc.com/ctmem/schema900}shift_option_type" minOccurs="0"/>
 *         &lt;element name="shift_num" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="active_from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="active_till" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="month_days" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="week_days" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dates" type="{http://www.bmc.com/ctmem/schema900}dates_type" minOccurs="0"/>
 *         &lt;element name="JAN" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="FEB" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="MAR" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="APR" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="MAY" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="JUN" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="JUL" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="AUG" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="SEP" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="OCT" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="NOV" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="DEC" type="{http://www.bmc.com/ctmem/schema900}yes_no_type" minOccurs="0"/>
 *         &lt;element name="level" type="{http://www.bmc.com/ctmem/schema900}rbc_level_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rule_based_cal_type", propOrder = {
    "ruleBasedCalName",
    "maxWait",
    "andOr",
    "daysCal",
    "weeksCal",
    "confCal",
    "retro",
    "shift",
    "shiftNum",
    "activeFrom",
    "activeTill",
    "monthDays",
    "weekDays",
    "dates",
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
    "level"
})
public class RuleBasedCalType {

    @XmlElement(name = "rule_based_cal_name")
    protected String ruleBasedCalName;
    @XmlElement(name = "max_wait")
    protected String maxWait;
    @XmlElement(name = "and_or")
    protected AndOrType andOr;
    @XmlElement(name = "days_cal")
    protected String daysCal;
    @XmlElement(name = "weeks_cal")
    protected String weeksCal;
    @XmlElement(name = "conf_cal")
    protected String confCal;
    protected YesNoType retro;
    protected String shift;
    @XmlElement(name = "shift_num")
    protected String shiftNum;
    @XmlElement(name = "active_from")
    protected String activeFrom;
    @XmlElement(name = "active_till")
    protected String activeTill;
    @XmlElement(name = "month_days")
    protected String monthDays;
    @XmlElement(name = "week_days")
    protected String weekDays;
    protected DatesType dates;
    @XmlElement(name = "JAN")
    protected YesNoType jan;
    @XmlElement(name = "FEB")
    protected YesNoType feb;
    @XmlElement(name = "MAR")
    protected YesNoType mar;
    @XmlElement(name = "APR")
    protected YesNoType apr;
    @XmlElement(name = "MAY")
    protected YesNoType may;
    @XmlElement(name = "JUN")
    protected YesNoType jun;
    @XmlElement(name = "JUL")
    protected YesNoType jul;
    @XmlElement(name = "AUG")
    protected YesNoType aug;
    @XmlElement(name = "SEP")
    protected YesNoType sep;
    @XmlElement(name = "OCT")
    protected YesNoType oct;
    @XmlElement(name = "NOV")
    protected YesNoType nov;
    @XmlElement(name = "DEC")
    protected YesNoType dec;
    protected RbcLevelType level;

    /**
     * Gets the value of the ruleBasedCalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleBasedCalName() {
        return ruleBasedCalName;
    }

    /**
     * Sets the value of the ruleBasedCalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleBasedCalName(String value) {
        this.ruleBasedCalName = value;
    }

    /**
     * Gets the value of the maxWait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWait() {
        return maxWait;
    }

    /**
     * Sets the value of the maxWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWait(String value) {
        this.maxWait = value;
    }

    /**
     * Gets the value of the andOr property.
     * 
     * @return
     *     possible object is
     *     {@link AndOrType }
     *     
     */
    public AndOrType getAndOr() {
        return andOr;
    }

    /**
     * Sets the value of the andOr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AndOrType }
     *     
     */
    public void setAndOr(AndOrType value) {
        this.andOr = value;
    }

    /**
     * Gets the value of the daysCal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysCal() {
        return daysCal;
    }

    /**
     * Sets the value of the daysCal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysCal(String value) {
        this.daysCal = value;
    }

    /**
     * Gets the value of the weeksCal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeeksCal() {
        return weeksCal;
    }

    /**
     * Sets the value of the weeksCal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeeksCal(String value) {
        this.weeksCal = value;
    }

    /**
     * Gets the value of the confCal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfCal() {
        return confCal;
    }

    /**
     * Sets the value of the confCal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfCal(String value) {
        this.confCal = value;
    }

    /**
     * Gets the value of the retro property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getRetro() {
        return retro;
    }

    /**
     * Sets the value of the retro property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setRetro(YesNoType value) {
        this.retro = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     * @return
     *     possible object is
     *     {@link ShiftOptionType }
     *     
     */
    public String getShift() {
    	return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShiftOptionType }
     *     
     */
    public void setShift(String value) {
        this.shift = value;
    }

    /**
     * Gets the value of the shiftNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShiftNum() {
        return shiftNum;
    }

    /**
     * Sets the value of the shiftNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShiftNum(String value) {
        this.shiftNum = value;
    }

    /**
     * Gets the value of the activeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFrom() {
        return activeFrom;
    }

    /**
     * Sets the value of the activeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFrom(String value) {
        this.activeFrom = value;
    }

    /**
     * Gets the value of the activeTill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveTill() {
        return activeTill;
    }

    /**
     * Sets the value of the activeTill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveTill(String value) {
        this.activeTill = value;
    }

    /**
     * Gets the value of the monthDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthDays() {
        return monthDays;
    }

    /**
     * Sets the value of the monthDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthDays(String value) {
        this.monthDays = value;
    }

    /**
     * Gets the value of the weekDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeekDays() {
        return weekDays;
    }

    /**
     * Sets the value of the weekDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekDays(String value) {
        this.weekDays = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link DatesType }
     *     
     */
    public DatesType getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatesType }
     *     
     */
    public void setDates(DatesType value) {
        this.dates = value;
    }

    /**
     * Gets the value of the jan property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getJAN() {
        return jan;
    }

    /**
     * Sets the value of the jan property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setJAN(YesNoType value) {
        this.jan = value;
    }

    /**
     * Gets the value of the feb property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getFEB() {
        return feb;
    }

    /**
     * Sets the value of the feb property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setFEB(YesNoType value) {
        this.feb = value;
    }

    /**
     * Gets the value of the mar property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getMAR() {
        return mar;
    }

    /**
     * Sets the value of the mar property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setMAR(YesNoType value) {
        this.mar = value;
    }

    /**
     * Gets the value of the apr property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAPR() {
        return apr;
    }

    /**
     * Sets the value of the apr property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAPR(YesNoType value) {
        this.apr = value;
    }

    /**
     * Gets the value of the may property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getMAY() {
        return may;
    }

    /**
     * Sets the value of the may property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setMAY(YesNoType value) {
        this.may = value;
    }

    /**
     * Gets the value of the jun property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getJUN() {
        return jun;
    }

    /**
     * Sets the value of the jun property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setJUN(YesNoType value) {
        this.jun = value;
    }

    /**
     * Gets the value of the jul property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getJUL() {
        return jul;
    }

    /**
     * Sets the value of the jul property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setJUL(YesNoType value) {
        this.jul = value;
    }

    /**
     * Gets the value of the aug property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAUG() {
        return aug;
    }

    /**
     * Sets the value of the aug property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAUG(YesNoType value) {
        this.aug = value;
    }

    /**
     * Gets the value of the sep property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getSEP() {
        return sep;
    }

    /**
     * Sets the value of the sep property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setSEP(YesNoType value) {
        this.sep = value;
    }

    /**
     * Gets the value of the oct property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getOCT() {
        return oct;
    }

    /**
     * Sets the value of the oct property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setOCT(YesNoType value) {
        this.oct = value;
    }

    /**
     * Gets the value of the nov property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getNOV() {
        return nov;
    }

    /**
     * Sets the value of the nov property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setNOV(YesNoType value) {
        this.nov = value;
    }

    /**
     * Gets the value of the dec property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getDEC() {
        return dec;
    }

    /**
     * Sets the value of the dec property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setDEC(YesNoType value) {
        this.dec = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link RbcLevelType }
     *     
     */
    public RbcLevelType getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link RbcLevelType }
     *     
     */
    public void setLevel(RbcLevelType value) {
        this.level = value;
    }

}
