//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shift_option_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shift_option_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ignore_job"/>
 *     &lt;enumeration value="next_day"/>
 *     &lt;enumeration value="prev_day"/>
 *     &lt;enumeration value="no_confcal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "shift_option_type")
@XmlEnum
public enum ShiftOptionType {

    @XmlEnumValue("ignore_job")
    IGNORE_JOB("ignore_job"),
    @XmlEnumValue("next_day")
    NEXT_DAY("next_day"),
    @XmlEnumValue("prev_day")
    PREV_DAY("prev_day"),
    @XmlEnumValue("no_confcal")
    NO_CONFCAL("no_confcal");
    private final String value;

    ShiftOptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShiftOptionType fromValue(String v) {
        for (ShiftOptionType c: ShiftOptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
