//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sub_folder_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sub_folder_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="folder_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="folder_attributes" type="{http://www.bmc.com/ctmem/schema900}sub_folder_attributes_type"/>
 *         &lt;element name="sub_folders" type="{http://www.bmc.com/ctmem/schema900}sub_folders_type" minOccurs="0"/>
 *         &lt;element name="jobs" type="{http://www.bmc.com/ctmem/schema900}def_jobs_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sub_folder_type", propOrder = {
    "folderName",
    "folderAttributes",
    "subFolders",
    "jobs"
})
public class SubFolderType {

    @XmlElement(name = "folder_name", required = true)
    protected String folderName;
    @XmlElement(name = "folder_attributes", required = true)
    protected SubFolderAttributesType folderAttributes;
    @XmlElement(name = "sub_folders")
    protected SubFoldersType subFolders;
    protected DefJobsType jobs;

    /**
     * Gets the value of the folderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * Sets the value of the folderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderName(String value) {
        this.folderName = value;
    }

    /**
     * Gets the value of the folderAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SubFolderAttributesType }
     *     
     */
    public SubFolderAttributesType getFolderAttributes() {
        return folderAttributes;
    }

    /**
     * Sets the value of the folderAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubFolderAttributesType }
     *     
     */
    public void setFolderAttributes(SubFolderAttributesType value) {
        this.folderAttributes = value;
    }

    /**
     * Gets the value of the subFolders property.
     * 
     * @return
     *     possible object is
     *     {@link SubFoldersType }
     *     
     */
    public SubFoldersType getSubFolders() {
        return subFolders;
    }

    /**
     * Sets the value of the subFolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubFoldersType }
     *     
     */
    public void setSubFolders(SubFoldersType value) {
        this.subFolders = value;
    }

    /**
     * Gets the value of the jobs property.
     * 
     * @return
     *     possible object is
     *     {@link DefJobsType }
     *     
     */
    public DefJobsType getJobs() {
        return jobs;
    }

    /**
     * Sets the value of the jobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefJobsType }
     *     
     */
    public void setJobs(DefJobsType value) {
        this.jobs = value;
    }

}
