//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 03:50:52 PM KST 
//


package com.bmc.ctmem.schema900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sub_folder_attributes_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sub_folder_attributes_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.bmc.com/ctmem/schema900}general_smart_folder_attributes_type"/>
 *         &lt;element name="sub_folder_rule_based_cals" type="{http://www.bmc.com/ctmem/schema900}sub_rule_based_cal_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sub_folder_attributes_type", propOrder = {
    "jobName",
    "memName",
    "memLib",
    "application",
    "subApplication",
    "command",
    "runAs",
    "createdBy",
    "maxWait",
    "description",
    "preventNct2",
    "docMember",
    "docLib",
    "timeFrom",
    "timeUntil",
    "timeFromDaysOffset",
    "timeUntilDaysOffset",
    "rerunInterval",
    "rerunMember",
    "priority",
    "critical",
    "cyclic",
    "cyclicType",
    "intervalSequence",
    "specificTimes",
    "tolerance",
    "confirmFlag",
    "autoArchive",
    "sysDb",
    "archMaxDays",
    "archMaxRuns",
    "rerunMax",
    "overridePath",
    "timeDueOut",
    "daysDueOutOffset",
    "statisticCalendar",
    "countCyclicFrom",
    "retenDays",
    "retenGen",
    "timeZone",
    "applicationType",
    "applicationVersion",
    "applicationForm",
    "applicationCmVersion",
    "multiagent",
    "scheduleEnvironment",
    "systemAffinity",
    "requestNje",
    "outputOption",
    "outputFromClass",
    "outputParameter",
    "adjustCondition",
    "nodeId",
    "ctldCategory",
    "pds",
    "minPdsTracks",
    "sac",
    "instreamJcl",
    "useInstreamJcl",
    "removeatonce",
    "dayskeepinnotok",
    "variableAssignments",
    "inConditions",
    "controlResources",
    "outConditions",
    "stepRanges",
    "shouts",
    "onDoStatements",
    "subFolderRuleBasedCals"
})
public class SubFolderAttributesType {

    @XmlElement(name = "job_name")
    protected String jobName;
    @XmlElement(name = "mem_name")
    protected String memName;
    @XmlElement(name = "mem_lib")
    protected String memLib;
    @XmlElement(required = true)
    protected String application;
    @XmlElement(name = "sub_application", required = true)
    protected String subApplication;
    protected String command;
    @XmlElement(name = "run_as")
    protected String runAs;
    @XmlElement(name = "created_by")
    protected String createdBy;
    @XmlElement(name = "max_wait")
    protected String maxWait;
    protected String description;
    @XmlElement(name = "prevent_nct2")
    protected PreventNct2OptionType preventNct2;
    @XmlElement(name = "doc_member")
    protected String docMember;
    @XmlElement(name = "doc_lib")
    protected String docLib;
    @XmlElement(name = "time_from")
    protected String timeFrom;
    @XmlElement(name = "time_until")
    protected String timeUntil;
    @XmlElement(name = "time_from_days_offset")
    protected String timeFromDaysOffset;
    @XmlElement(name = "time_until_days_offset")
    protected String timeUntilDaysOffset;
    @XmlElement(name = "rerun_interval")
    protected String rerunInterval;
    @XmlElement(name = "rerun_member")
    protected String rerunMember;
    protected String priority;
    protected YesNoType critical;
    protected YesNoType cyclic;
    @XmlElement(name = "cyclic_type")
    protected CyclicTypeType cyclicType;
    @XmlElement(name = "interval_sequence")
    protected IntervalSequenceType intervalSequence;
    @XmlElement(name = "specific_times")
    protected SpecificTimesType specificTimes;
    protected String tolerance;
    @XmlElement(name = "confirm_flag")
    protected YesNoType confirmFlag;
    @XmlElement(name = "auto_archive")
    protected YesNoType autoArchive;
    @XmlElement(name = "sys_db")
    protected YesNoType sysDb;
    @XmlElement(name = "arch_max_days")
    protected String archMaxDays;
    @XmlElement(name = "arch_max_runs")
    protected String archMaxRuns;
    @XmlElement(name = "rerun_max")
    protected String rerunMax;
    @XmlElement(name = "override_path")
    protected String overridePath;
    @XmlElement(name = "time_due_out")
    protected String timeDueOut;
    @XmlElement(name = "days_due_out_offset")
    protected String daysDueOutOffset;
    @XmlElement(name = "statistic_calendar")
    protected String statisticCalendar;
    @XmlElement(name = "count_cyclic_from")
    protected StartEndTargetType countCyclicFrom;
    @XmlElement(name = "reten_days")
    protected String retenDays;
    @XmlElement(name = "reten_gen")
    protected String retenGen;
    @XmlElement(name = "time_zone")
    protected String timeZone;
    @XmlElement(name = "application_type")
    protected String applicationType;
    @XmlElement(name = "application_version")
    protected String applicationVersion;
    @XmlElement(name = "application_form")
    protected String applicationForm;
    @XmlElement(name = "application_cm_version")
    protected String applicationCmVersion;
    protected YesNoType multiagent;
    @XmlElement(name = "schedule_environment")
    protected String scheduleEnvironment;
    @XmlElement(name = "system_affinity")
    protected String systemAffinity;
    @XmlElement(name = "request_nje")
    protected String requestNje;
    @XmlElement(name = "output_option")
    protected String outputOption;
    @XmlElement(name = "output_from_class")
    protected String outputFromClass;
    @XmlElement(name = "output_parameter")
    protected String outputParameter;
    @XmlElement(name = "adjust_condition")
    protected YesNoDummyType adjustCondition;
    @XmlElement(name = "node_id")
    protected String nodeId;
    @XmlElement(name = "ctld_category")
    protected String ctldCategory;
    protected String pds;
    @XmlElement(name = "min_pds_tracks")
    protected String minPdsTracks;
    protected Sac4SgOptionType sac;
    @XmlElement(name = "instream_jcl")
    protected String instreamJcl;
    @XmlElement(name = "use_instream_jcl")
    protected YesNoType useInstreamJcl;
    protected YesNoType removeatonce;
    protected String dayskeepinnotok;
    @XmlElement(name = "variable_assignments")
    protected VariableAssignmentsType variableAssignments;
    @XmlElement(name = "in_conditions")
    protected InConditionsType inConditions;
    @XmlElement(name = "control_resources")
    protected ControlResourcesType controlResources;
    @XmlElement(name = "out_conditions")
    protected OutConditionsType outConditions;
    @XmlElement(name = "step_ranges")
    protected StepRangesType stepRanges;
    protected ShoutsType shouts;
    @XmlElement(name = "on_do_statements")
    protected OnDoStatementsType onDoStatements;
    @XmlElement(name = "sub_folder_rule_based_cals", required = true)
    protected SubRuleBasedCalType subFolderRuleBasedCals;

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the memName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemName() {
        return memName;
    }

    /**
     * Sets the value of the memName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemName(String value) {
        this.memName = value;
    }

    /**
     * Gets the value of the memLib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemLib() {
        return memLib;
    }

    /**
     * Sets the value of the memLib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemLib(String value) {
        this.memLib = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the subApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubApplication() {
        return subApplication;
    }

    /**
     * Sets the value of the subApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubApplication(String value) {
        this.subApplication = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the runAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunAs() {
        return runAs;
    }

    /**
     * Sets the value of the runAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunAs(String value) {
        this.runAs = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the maxWait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWait() {
        return maxWait;
    }

    /**
     * Sets the value of the maxWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWait(String value) {
        this.maxWait = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the preventNct2 property.
     * 
     * @return
     *     possible object is
     *     {@link PreventNct2OptionType }
     *     
     */
    public PreventNct2OptionType getPreventNct2() {
        return preventNct2;
    }

    /**
     * Sets the value of the preventNct2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreventNct2OptionType }
     *     
     */
    public void setPreventNct2(PreventNct2OptionType value) {
        this.preventNct2 = value;
    }

    /**
     * Gets the value of the docMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocMember() {
        return docMember;
    }

    /**
     * Sets the value of the docMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocMember(String value) {
        this.docMember = value;
    }

    /**
     * Gets the value of the docLib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocLib() {
        return docLib;
    }

    /**
     * Sets the value of the docLib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocLib(String value) {
        this.docLib = value;
    }

    /**
     * Gets the value of the timeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeFrom() {
        return timeFrom;
    }

    /**
     * Sets the value of the timeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeFrom(String value) {
        this.timeFrom = value;
    }

    /**
     * Gets the value of the timeUntil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeUntil() {
        return timeUntil;
    }

    /**
     * Sets the value of the timeUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeUntil(String value) {
        this.timeUntil = value;
    }

    /**
     * Gets the value of the timeFromDaysOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeFromDaysOffset() {
        return timeFromDaysOffset;
    }

    /**
     * Sets the value of the timeFromDaysOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeFromDaysOffset(String value) {
        this.timeFromDaysOffset = value;
    }

    /**
     * Gets the value of the timeUntilDaysOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeUntilDaysOffset() {
        return timeUntilDaysOffset;
    }

    /**
     * Sets the value of the timeUntilDaysOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeUntilDaysOffset(String value) {
        this.timeUntilDaysOffset = value;
    }

    /**
     * Gets the value of the rerunInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerunInterval() {
        return rerunInterval;
    }

    /**
     * Sets the value of the rerunInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerunInterval(String value) {
        this.rerunInterval = value;
    }

    /**
     * Gets the value of the rerunMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerunMember() {
        return rerunMember;
    }

    /**
     * Sets the value of the rerunMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerunMember(String value) {
        this.rerunMember = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setCritical(YesNoType value) {
        this.critical = value;
    }

    /**
     * Gets the value of the cyclic property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getCyclic() {
        return cyclic;
    }

    /**
     * Sets the value of the cyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setCyclic(YesNoType value) {
        this.cyclic = value;
    }

    /**
     * Gets the value of the cyclicType property.
     * 
     * @return
     *     possible object is
     *     {@link CyclicTypeType }
     *     
     */
    public CyclicTypeType getCyclicType() {
        return cyclicType;
    }

    /**
     * Sets the value of the cyclicType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CyclicTypeType }
     *     
     */
    public void setCyclicType(CyclicTypeType value) {
        this.cyclicType = value;
    }

    /**
     * Gets the value of the intervalSequence property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalSequenceType }
     *     
     */
    public IntervalSequenceType getIntervalSequence() {
        return intervalSequence;
    }

    /**
     * Sets the value of the intervalSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalSequenceType }
     *     
     */
    public void setIntervalSequence(IntervalSequenceType value) {
        this.intervalSequence = value;
    }

    /**
     * Gets the value of the specificTimes property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificTimesType }
     *     
     */
    public SpecificTimesType getSpecificTimes() {
        return specificTimes;
    }

    /**
     * Sets the value of the specificTimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificTimesType }
     *     
     */
    public void setSpecificTimes(SpecificTimesType value) {
        this.specificTimes = value;
    }

    /**
     * Gets the value of the tolerance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTolerance() {
        return tolerance;
    }

    /**
     * Sets the value of the tolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTolerance(String value) {
        this.tolerance = value;
    }

    /**
     * Gets the value of the confirmFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getConfirmFlag() {
        return confirmFlag;
    }

    /**
     * Sets the value of the confirmFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setConfirmFlag(YesNoType value) {
        this.confirmFlag = value;
    }

    /**
     * Gets the value of the autoArchive property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAutoArchive() {
        return autoArchive;
    }

    /**
     * Sets the value of the autoArchive property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAutoArchive(YesNoType value) {
        this.autoArchive = value;
    }

    /**
     * Gets the value of the sysDb property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getSysDb() {
        return sysDb;
    }

    /**
     * Sets the value of the sysDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setSysDb(YesNoType value) {
        this.sysDb = value;
    }

    /**
     * Gets the value of the archMaxDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchMaxDays() {
        return archMaxDays;
    }

    /**
     * Sets the value of the archMaxDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchMaxDays(String value) {
        this.archMaxDays = value;
    }

    /**
     * Gets the value of the archMaxRuns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchMaxRuns() {
        return archMaxRuns;
    }

    /**
     * Sets the value of the archMaxRuns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchMaxRuns(String value) {
        this.archMaxRuns = value;
    }

    /**
     * Gets the value of the rerunMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRerunMax() {
        return rerunMax;
    }

    /**
     * Sets the value of the rerunMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRerunMax(String value) {
        this.rerunMax = value;
    }

    /**
     * Gets the value of the overridePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverridePath() {
        return overridePath;
    }

    /**
     * Sets the value of the overridePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverridePath(String value) {
        this.overridePath = value;
    }

    /**
     * Gets the value of the timeDueOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeDueOut() {
        return timeDueOut;
    }

    /**
     * Sets the value of the timeDueOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeDueOut(String value) {
        this.timeDueOut = value;
    }

    /**
     * Gets the value of the daysDueOutOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysDueOutOffset() {
        return daysDueOutOffset;
    }

    /**
     * Sets the value of the daysDueOutOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysDueOutOffset(String value) {
        this.daysDueOutOffset = value;
    }

    /**
     * Gets the value of the statisticCalendar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticCalendar() {
        return statisticCalendar;
    }

    /**
     * Sets the value of the statisticCalendar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticCalendar(String value) {
        this.statisticCalendar = value;
    }

    /**
     * Gets the value of the countCyclicFrom property.
     * 
     * @return
     *     possible object is
     *     {@link StartEndTargetType }
     *     
     */
    public StartEndTargetType getCountCyclicFrom() {
        return countCyclicFrom;
    }

    /**
     * Sets the value of the countCyclicFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartEndTargetType }
     *     
     */
    public void setCountCyclicFrom(StartEndTargetType value) {
        this.countCyclicFrom = value;
    }

    /**
     * Gets the value of the retenDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetenDays() {
        return retenDays;
    }

    /**
     * Sets the value of the retenDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetenDays(String value) {
        this.retenDays = value;
    }

    /**
     * Gets the value of the retenGen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetenGen() {
        return retenGen;
    }

    /**
     * Sets the value of the retenGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetenGen(String value) {
        this.retenGen = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the applicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * Sets the value of the applicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationType(String value) {
        this.applicationType = value;
    }

    /**
     * Gets the value of the applicationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationVersion() {
        return applicationVersion;
    }

    /**
     * Sets the value of the applicationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationVersion(String value) {
        this.applicationVersion = value;
    }

    /**
     * Gets the value of the applicationForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationForm() {
        return applicationForm;
    }

    /**
     * Sets the value of the applicationForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationForm(String value) {
        this.applicationForm = value;
    }

    /**
     * Gets the value of the applicationCmVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationCmVersion() {
        return applicationCmVersion;
    }

    /**
     * Sets the value of the applicationCmVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationCmVersion(String value) {
        this.applicationCmVersion = value;
    }

    /**
     * Gets the value of the multiagent property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getMultiagent() {
        return multiagent;
    }

    /**
     * Sets the value of the multiagent property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setMultiagent(YesNoType value) {
        this.multiagent = value;
    }

    /**
     * Gets the value of the scheduleEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleEnvironment() {
        return scheduleEnvironment;
    }

    /**
     * Sets the value of the scheduleEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleEnvironment(String value) {
        this.scheduleEnvironment = value;
    }

    /**
     * Gets the value of the systemAffinity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemAffinity() {
        return systemAffinity;
    }

    /**
     * Sets the value of the systemAffinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemAffinity(String value) {
        this.systemAffinity = value;
    }

    /**
     * Gets the value of the requestNje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestNje() {
        return requestNje;
    }

    /**
     * Sets the value of the requestNje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestNje(String value) {
        this.requestNje = value;
    }

    /**
     * Gets the value of the outputOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputOption() {
        return outputOption;
    }

    /**
     * Sets the value of the outputOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputOption(String value) {
        this.outputOption = value;
    }

    /**
     * Gets the value of the outputFromClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFromClass() {
        return outputFromClass;
    }

    /**
     * Sets the value of the outputFromClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFromClass(String value) {
        this.outputFromClass = value;
    }

    /**
     * Gets the value of the outputParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputParameter() {
        return outputParameter;
    }

    /**
     * Sets the value of the outputParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputParameter(String value) {
        this.outputParameter = value;
    }

    /**
     * Gets the value of the adjustCondition property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoDummyType }
     *     
     */
    public YesNoDummyType getAdjustCondition() {
        return adjustCondition;
    }

    /**
     * Sets the value of the adjustCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoDummyType }
     *     
     */
    public void setAdjustCondition(YesNoDummyType value) {
        this.adjustCondition = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the ctldCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtldCategory() {
        return ctldCategory;
    }

    /**
     * Sets the value of the ctldCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtldCategory(String value) {
        this.ctldCategory = value;
    }

    /**
     * Gets the value of the pds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPds() {
        return pds;
    }

    /**
     * Sets the value of the pds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPds(String value) {
        this.pds = value;
    }

    /**
     * Gets the value of the minPdsTracks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinPdsTracks() {
        return minPdsTracks;
    }

    /**
     * Sets the value of the minPdsTracks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinPdsTracks(String value) {
        this.minPdsTracks = value;
    }

    /**
     * Gets the value of the sac property.
     * 
     * @return
     *     possible object is
     *     {@link Sac4SgOptionType }
     *     
     */
    public Sac4SgOptionType getSac() {
        return sac;
    }

    /**
     * Sets the value of the sac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sac4SgOptionType }
     *     
     */
    public void setSac(Sac4SgOptionType value) {
        this.sac = value;
    }

    /**
     * Gets the value of the instreamJcl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstreamJcl() {
        return instreamJcl;
    }

    /**
     * Sets the value of the instreamJcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstreamJcl(String value) {
        this.instreamJcl = value;
    }

    /**
     * Gets the value of the useInstreamJcl property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getUseInstreamJcl() {
        return useInstreamJcl;
    }

    /**
     * Sets the value of the useInstreamJcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setUseInstreamJcl(YesNoType value) {
        this.useInstreamJcl = value;
    }

    /**
     * Gets the value of the removeatonce property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getRemoveatonce() {
        return removeatonce;
    }

    /**
     * Sets the value of the removeatonce property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setRemoveatonce(YesNoType value) {
        this.removeatonce = value;
    }

    /**
     * Gets the value of the dayskeepinnotok property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayskeepinnotok() {
        return dayskeepinnotok;
    }

    /**
     * Sets the value of the dayskeepinnotok property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayskeepinnotok(String value) {
        this.dayskeepinnotok = value;
    }

    /**
     * Gets the value of the variableAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link VariableAssignmentsType }
     *     
     */
    public VariableAssignmentsType getVariableAssignments() {
        return variableAssignments;
    }

    /**
     * Sets the value of the variableAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableAssignmentsType }
     *     
     */
    public void setVariableAssignments(VariableAssignmentsType value) {
        this.variableAssignments = value;
    }

    /**
     * Gets the value of the inConditions property.
     * 
     * @return
     *     possible object is
     *     {@link InConditionsType }
     *     
     */
    public InConditionsType getInConditions() {
        return inConditions;
    }

    /**
     * Sets the value of the inConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InConditionsType }
     *     
     */
    public void setInConditions(InConditionsType value) {
        this.inConditions = value;
    }

    /**
     * Gets the value of the controlResources property.
     * 
     * @return
     *     possible object is
     *     {@link ControlResourcesType }
     *     
     */
    public ControlResourcesType getControlResources() {
        return controlResources;
    }

    /**
     * Sets the value of the controlResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlResourcesType }
     *     
     */
    public void setControlResources(ControlResourcesType value) {
        this.controlResources = value;
    }

    /**
     * Gets the value of the outConditions property.
     * 
     * @return
     *     possible object is
     *     {@link OutConditionsType }
     *     
     */
    public OutConditionsType getOutConditions() {
        return outConditions;
    }

    /**
     * Sets the value of the outConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutConditionsType }
     *     
     */
    public void setOutConditions(OutConditionsType value) {
        this.outConditions = value;
    }

    /**
     * Gets the value of the stepRanges property.
     * 
     * @return
     *     possible object is
     *     {@link StepRangesType }
     *     
     */
    public StepRangesType getStepRanges() {
        return stepRanges;
    }

    /**
     * Sets the value of the stepRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepRangesType }
     *     
     */
    public void setStepRanges(StepRangesType value) {
        this.stepRanges = value;
    }

    /**
     * Gets the value of the shouts property.
     * 
     * @return
     *     possible object is
     *     {@link ShoutsType }
     *     
     */
    public ShoutsType getShouts() {
        return shouts;
    }

    /**
     * Sets the value of the shouts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShoutsType }
     *     
     */
    public void setShouts(ShoutsType value) {
        this.shouts = value;
    }

    /**
     * Gets the value of the onDoStatements property.
     * 
     * @return
     *     possible object is
     *     {@link OnDoStatementsType }
     *     
     */
    public OnDoStatementsType getOnDoStatements() {
        return onDoStatements;
    }

    /**
     * Sets the value of the onDoStatements property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnDoStatementsType }
     *     
     */
    public void setOnDoStatements(OnDoStatementsType value) {
        this.onDoStatements = value;
    }

    /**
     * Gets the value of the subFolderRuleBasedCals property.
     * 
     * @return
     *     possible object is
     *     {@link SubRuleBasedCalType }
     *     
     */
    public SubRuleBasedCalType getSubFolderRuleBasedCals() {
        return subFolderRuleBasedCals;
    }

    /**
     * Sets the value of the subFolderRuleBasedCals property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubRuleBasedCalType }
     *     
     */
    public void setSubFolderRuleBasedCals(SubRuleBasedCalType value) {
        this.subFolderRuleBasedCals = value;
    }

}
